//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36460
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 结算单主表
    /// </summary>
    [Table("TbSettlementOrder")]
    [Serializable]
    public partial class TbSettlementOrder : Entity
    {
        #region Model
		private int _ID;
		private string _SettlementCode;
		private string _SiteCode;
		private decimal? _AmountOfMoney;
		private string _InsertUserCode;
		private DateTime _InsertTime;
		private string _Remark;
		private string _Examinestatus;
		private string _ProjectId;
		private DateTime _StartDate;
		private DateTime _EndDate;
		private string _Unit;
		private string _ProcessFactoryCode;
		private decimal? _TotalWeight;

		/// <summary>
		/// 结算单ID
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 计价单号
		/// </summary>
		[Field("SettlementCode")]
		public string SettlementCode
		{
			get{ return _SettlementCode; }
			set
			{
				this.OnPropertyValueChange("SettlementCode");
				this._SettlementCode = value;
			}
		}
		/// <summary>
		/// 站点编号
		/// </summary>
		[Field("SiteCode")]
		public string SiteCode
		{
			get{ return _SiteCode; }
			set
			{
				this.OnPropertyValueChange("SiteCode");
				this._SiteCode = value;
			}
		}
		/// <summary>
		/// 金额
		/// </summary>
		[Field("AmountOfMoney")]
		public decimal? AmountOfMoney
		{
			get{ return _AmountOfMoney; }
			set
			{
				this.OnPropertyValueChange("AmountOfMoney");
				this._AmountOfMoney = value;
			}
		}
		/// <summary>
		/// 录入人
		/// </summary>
		[Field("InsertUserCode")]
		public string InsertUserCode
		{
			get{ return _InsertUserCode; }
			set
			{
				this.OnPropertyValueChange("InsertUserCode");
				this._InsertUserCode = value;
			}
		}
		/// <summary>
		/// 录入时间
		/// </summary>
		[Field("InsertTime")]
		public DateTime InsertTime
		{
			get{ return _InsertTime; }
			set
			{
				this.OnPropertyValueChange("InsertTime");
				this._InsertTime = value;
			}
		}
		/// <summary>
		/// 备注
		/// </summary>
		[Field("Remark")]
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange("Remark");
				this._Remark = value;
			}
		}
		/// <summary>
		/// 审批状态
		/// </summary>
		[Field("Examinestatus")]
		public string Examinestatus
		{
			get{ return _Examinestatus; }
			set
			{
				this.OnPropertyValueChange("Examinestatus");
				this._Examinestatus = value;
			}
		}
		/// <summary>
		/// 项目id
		/// </summary>
		[Field("ProjectId")]
		public string ProjectId
		{
			get{ return _ProjectId; }
			set
			{
				this.OnPropertyValueChange("ProjectId");
				this._ProjectId = value;
			}
		}
		/// <summary>
		/// 开始日期
		/// </summary>
		[Field("StartDate")]
		public DateTime StartDate
		{
			get{ return _StartDate; }
			set
			{
				this.OnPropertyValueChange("StartDate");
				this._StartDate = value;
			}
		}
		/// <summary>
		/// 结束日期
		/// </summary>
		[Field("EndDate")]
		public DateTime EndDate
		{
			get{ return _EndDate; }
			set
			{
				this.OnPropertyValueChange("EndDate");
				this._EndDate = value;
			}
		}
		/// <summary>
		/// 单位
		/// </summary>
		[Field("Unit")]
		public string Unit
		{
			get{ return _Unit; }
			set
			{
				this.OnPropertyValueChange("Unit");
				this._Unit = value;
			}
		}
		/// <summary>
		/// 加工厂编号
		/// </summary>
		[Field("ProcessFactoryCode")]
		public string ProcessFactoryCode
		{
			get{ return _ProcessFactoryCode; }
			set
			{
				this.OnPropertyValueChange("ProcessFactoryCode");
				this._ProcessFactoryCode = value;
			}
		}
		/// <summary>
		/// 总重量
		/// </summary>
		[Field("TotalWeight")]
		public decimal? TotalWeight
		{
			get{ return _TotalWeight; }
			set
			{
				this.OnPropertyValueChange("TotalWeight");
				this._TotalWeight = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.SettlementCode,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.SettlementCode,
				_.SiteCode,
				_.AmountOfMoney,
				_.InsertUserCode,
				_.InsertTime,
				_.Remark,
				_.Examinestatus,
				_.ProjectId,
				_.StartDate,
				_.EndDate,
				_.Unit,
				_.ProcessFactoryCode,
				_.TotalWeight,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._SettlementCode,
				this._SiteCode,
				this._AmountOfMoney,
				this._InsertUserCode,
				this._InsertTime,
				this._Remark,
				this._Examinestatus,
				this._ProjectId,
				this._StartDate,
				this._EndDate,
				this._Unit,
				this._ProcessFactoryCode,
				this._TotalWeight,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbSettlementOrder");
            /// <summary>
			/// 结算单ID
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbSettlementOrder", "结算单ID");
            /// <summary>
			/// 计价单号
			/// </summary>
			public readonly static Field SettlementCode = new Field("SettlementCode", "TbSettlementOrder", "计价单号");
            /// <summary>
			/// 站点编号
			/// </summary>
			public readonly static Field SiteCode = new Field("SiteCode", "TbSettlementOrder", "站点编号");
            /// <summary>
			/// 金额
			/// </summary>
			public readonly static Field AmountOfMoney = new Field("AmountOfMoney", "TbSettlementOrder", "金额");
            /// <summary>
			/// 录入人
			/// </summary>
			public readonly static Field InsertUserCode = new Field("InsertUserCode", "TbSettlementOrder", "录入人");
            /// <summary>
			/// 录入时间
			/// </summary>
			public readonly static Field InsertTime = new Field("InsertTime", "TbSettlementOrder", "录入时间");
            /// <summary>
			/// 备注
			/// </summary>
			public readonly static Field Remark = new Field("Remark", "TbSettlementOrder", "备注");
            /// <summary>
			/// 审批状态
			/// </summary>
			public readonly static Field Examinestatus = new Field("Examinestatus", "TbSettlementOrder", "审批状态");
            /// <summary>
			/// 项目id
			/// </summary>
			public readonly static Field ProjectId = new Field("ProjectId", "TbSettlementOrder", "项目id");
            /// <summary>
			/// 开始日期
			/// </summary>
			public readonly static Field StartDate = new Field("StartDate", "TbSettlementOrder", "开始日期");
            /// <summary>
			/// 结束日期
			/// </summary>
			public readonly static Field EndDate = new Field("EndDate", "TbSettlementOrder", "结束日期");
            /// <summary>
			/// 单位
			/// </summary>
			public readonly static Field Unit = new Field("Unit", "TbSettlementOrder", "单位");
            /// <summary>
			/// 加工厂编号
			/// </summary>
			public readonly static Field ProcessFactoryCode = new Field("ProcessFactoryCode", "TbSettlementOrder", "加工厂编号");
            /// <summary>
			/// 总重量
			/// </summary>
			public readonly static Field TotalWeight = new Field("TotalWeight", "TbSettlementOrder", "总重量");
        }
        #endregion
	}
}