//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36450
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DomainEntity
{
    /// <summary>
    /// 实体类TbShortMessageTemplate。 短信模板 (属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("TbShortMessageTemplate")]
    [Serializable]
    public partial class TbShortMessageTemplate : Entity
    {
        #region Model
        private int _ID;
        private string _TemplateCode;
        private string _TemplateType;
        private string _TemplateContent;
        private string _Remarks;

        /// <summary>
        /// 标识ID
        /// </summary>
        [Field("ID")]
        public int ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }
        /// <summary>
        /// 模板编号
        /// </summary>
        [Field("TemplateCode")]
        public string TemplateCode
        {
            get { return _TemplateCode; }
            set
            {
                this.OnPropertyValueChange("TemplateCode");
                this._TemplateCode = value;
            }
        }
        /// <summary>
        /// 模板类型
        /// </summary>
        [Field("TemplateType")]
        public string TemplateType
        {
            get { return _TemplateType; }
            set
            {
                this.OnPropertyValueChange("TemplateType");
                this._TemplateType = value;
            }
        }
        /// <summary>
        /// 模板内容
        /// </summary>
        [Field("TemplateContent")]
        public string TemplateContent
        {
            get { return _TemplateContent; }
            set
            {
                this.OnPropertyValueChange("TemplateContent");
                this._TemplateContent = value;
            }
        }
        /// <summary>
        /// 备注
        /// </summary>
        [Field("Remarks")]
        public string Remarks
        {
            get { return _Remarks; }
            set
            {
                this.OnPropertyValueChange("Remarks");
                this._Remarks = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
				_.TemplateCode,
			};
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.TemplateCode,
				_.TemplateType,
				_.TemplateContent,
				_.Remarks,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._TemplateCode,
				this._TemplateType,
				this._TemplateContent,
				this._Remarks,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "TbShortMessageTemplate");
            /// <summary>
            /// 标识ID
            /// </summary>
            public readonly static Field ID = new Field("ID", "TbShortMessageTemplate", "标识ID");
            /// <summary>
            /// 模板编号
            /// </summary>
            public readonly static Field TemplateCode = new Field("TemplateCode", "TbShortMessageTemplate", "模板编号");
            /// <summary>
            /// 模板类型
            /// </summary>
            public readonly static Field TemplateType = new Field("TemplateType", "TbShortMessageTemplate", "模板类型");
            /// <summary>
            /// 模板内容
            /// </summary>
            public readonly static Field TemplateContent = new Field("TemplateContent", "TbShortMessageTemplate", "模板内容");
            /// <summary>
            /// 模板备注
            /// </summary>
            public readonly static Field Remarks = new Field("Remarks", "TbShortMessageTemplate", "模板备注");
        }
        #endregion
    }
}