//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 实体类TbPermissionsTeamMember。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("TbPermissionsTeamMember")]
    [Serializable]
    public partial class TbPermissionsTeamMember : Entity
    {
        #region Model
		private int _ID;
		private string _TeamNumber;
		private string _UserCode;

		/// <summary>
		/// 
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("TeamNumber")]
		public string TeamNumber
		{
			get{ return _TeamNumber; }
			set
			{
				this.OnPropertyValueChange("TeamNumber");
				this._TeamNumber = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("UserCode")]
		public string UserCode
		{
			get{ return _UserCode; }
			set
			{
				this.OnPropertyValueChange("UserCode");
				this._UserCode = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.TeamNumber,
				_.UserCode,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._TeamNumber,
				this._UserCode,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbPermissionsTeamMember");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbPermissionsTeamMember", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field TeamNumber = new Field("TeamNumber", "TbPermissionsTeamMember", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field UserCode = new Field("UserCode", "TbPermissionsTeamMember", "");
        }
        #endregion
	}
}