//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36440
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 实体类TbSysMenuTable。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("TbSysMenuTable")]
    [Serializable]
    public partial class TbSysMenuTable : Entity
    {
        #region Model
		private int _ID;
		private string _MenuCode;
		private string _TableName;
		private string _IsMainTabel;

		/// <summary>
		/// 
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("MenuCode")]
		public string MenuCode
		{
			get{ return _MenuCode; }
			set
			{
				this.OnPropertyValueChange("MenuCode");
				this._MenuCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("TableName")]
		public string TableName
		{
			get{ return _TableName; }
			set
			{
				this.OnPropertyValueChange("TableName");
				this._TableName = value;
			}
		}
		/// <summary>
		/// 默认为0是，1否
		/// </summary>
		[Field("IsMainTabel")]
		public string IsMainTabel
		{
			get{ return _IsMainTabel; }
			set
			{
				this.OnPropertyValueChange("IsMainTabel");
				this._IsMainTabel = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.MenuCode,
				_.TableName,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.MenuCode,
				_.TableName,
				_.IsMainTabel,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._MenuCode,
				this._TableName,
				this._IsMainTabel,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbSysMenuTable");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbSysMenuTable", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field MenuCode = new Field("MenuCode", "TbSysMenuTable", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field TableName = new Field("TableName", "TbSysMenuTable", "");
            /// <summary>
			/// 默认为0是，1否
			/// </summary>
			public readonly static Field IsMainTabel = new Field("IsMainTabel", "TbSysMenuTable", "默认为0是，1否");
        }
        #endregion
	}
}