//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36460
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;
using PM.DataEntity.Base;

namespace PM.DataEntity
{
    /// <summary>
    /// 消防检查
    /// </summary>
    [Table("TbFireInspection")]
    [Serializable]
    public partial class TbFireInspection : BaseEntity
    {
        #region Model
		private int _ID;
		private string _CheckCode;
		private string _ProcessFactoryCode;
		private string _FireImplement;
		private string _FireSlogan;
		private string _FirePassageway;
		private string _FirePiping;
		private string _CheckUserCodes;
		private string _CheckUserNames;
		private DateTime? _CheckDate;
		private string _ProblemDescription;
		private string _Enclosure;
		private string _InsertUserCode;
		private DateTime _InsertTime;

		/// <summary>
		/// ID
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 检查编号
		/// </summary>
		[Field("CheckCode")]
		public string CheckCode
		{
			get{ return _CheckCode; }
			set
			{
				this.OnPropertyValueChange("CheckCode");
				this._CheckCode = value;
			}
		}
		/// <summary>
		/// 加工厂编号
		/// </summary>
		[Field("ProcessFactoryCode")]
		public string ProcessFactoryCode
		{
			get{ return _ProcessFactoryCode; }
			set
			{
				this.OnPropertyValueChange("ProcessFactoryCode");
				this._ProcessFactoryCode = value;
			}
		}
		/// <summary>
		/// 消防实施
		/// </summary>
		[Field("FireImplement")]
		public string FireImplement
		{
			get{ return _FireImplement; }
			set
			{
				this.OnPropertyValueChange("FireImplement");
				this._FireImplement = value;
			}
		}
		/// <summary>
		/// 消防标语
		/// </summary>
		[Field("FireSlogan")]
		public string FireSlogan
		{
			get{ return _FireSlogan; }
			set
			{
				this.OnPropertyValueChange("FireSlogan");
				this._FireSlogan = value;
			}
		}
		/// <summary>
		/// 消防通道
		/// </summary>
		[Field("FirePassageway")]
		public string FirePassageway
		{
			get{ return _FirePassageway; }
			set
			{
				this.OnPropertyValueChange("FirePassageway");
				this._FirePassageway = value;
			}
		}
		/// <summary>
		/// 消防管道
		/// </summary>
		[Field("FirePiping")]
		public string FirePiping
		{
			get{ return _FirePiping; }
			set
			{
				this.OnPropertyValueChange("FirePiping");
				this._FirePiping = value;
			}
		}
		/// <summary>
		/// 检查人员编号
		/// </summary>
		[Field("CheckUserCodes")]
		public string CheckUserCodes
		{
			get{ return _CheckUserCodes; }
			set
			{
				this.OnPropertyValueChange("CheckUserCodes");
				this._CheckUserCodes = value;
			}
		}
		/// <summary>
		/// 检查人员名称
		/// </summary>
		[Field("CheckUserNames")]
		public string CheckUserNames
		{
			get{ return _CheckUserNames; }
			set
			{
				this.OnPropertyValueChange("CheckUserNames");
				this._CheckUserNames = value;
			}
		}
		/// <summary>
		/// 检查时间
		/// </summary>
		[Field("CheckDate")]
		public DateTime? CheckDate
		{
			get{ return _CheckDate; }
			set
			{
				this.OnPropertyValueChange("CheckDate");
				this._CheckDate = value;
			}
		}
		/// <summary>
		/// 问题描述
		/// </summary>
		[Field("ProblemDescription")]
		public string ProblemDescription
		{
			get{ return _ProblemDescription; }
			set
			{
				this.OnPropertyValueChange("ProblemDescription");
				this._ProblemDescription = value;
			}
		}
		/// <summary>
		/// 附件
		/// </summary>
		[Field("Enclosure")]
		public string Enclosure
		{
			get{ return _Enclosure; }
			set
			{
				this.OnPropertyValueChange("Enclosure");
				this._Enclosure = value;
			}
		}
		/// <summary>
		/// 录入人编号
		/// </summary>
		[Field("InsertUserCode")]
		public string InsertUserCode
		{
			get{ return _InsertUserCode; }
			set
			{
				this.OnPropertyValueChange("InsertUserCode");
				this._InsertUserCode = value;
			}
		}
		/// <summary>
		/// 录入时间
		/// </summary>
		[Field("InsertTime")]
		public DateTime InsertTime
		{
			get{ return _InsertTime; }
			set
			{
				this.OnPropertyValueChange("InsertTime");
				this._InsertTime = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.CheckCode,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.CheckCode,
				_.ProcessFactoryCode,
				_.FireImplement,
				_.FireSlogan,
				_.FirePassageway,
				_.FirePiping,
				_.CheckUserCodes,
				_.CheckUserNames,
				_.CheckDate,
				_.ProblemDescription,
				_.Enclosure,
				_.InsertUserCode,
				_.InsertTime,
                _.ProjectId
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._CheckCode,
				this._ProcessFactoryCode,
				this._FireImplement,
				this._FireSlogan,
				this._FirePassageway,
				this._FirePiping,
				this._CheckUserCodes,
				this._CheckUserNames,
				this._CheckDate,
				this._ProblemDescription,
				this._Enclosure,
				this._InsertUserCode,
				this._InsertTime,
                this._ProjectId
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _ : BaseField<TbFireInspection>
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbFireInspection");
            /// <summary>
			/// ID
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbFireInspection", "ID");
            /// <summary>
			/// 检查编号
			/// </summary>
			public readonly static Field CheckCode = new Field("CheckCode", "TbFireInspection", "检查编号");
            /// <summary>
			/// 加工厂编号
			/// </summary>
			public readonly static Field ProcessFactoryCode = new Field("ProcessFactoryCode", "TbFireInspection", "加工厂编号");
            /// <summary>
			/// 消防实施
			/// </summary>
			public readonly static Field FireImplement = new Field("FireImplement", "TbFireInspection", "消防实施");
            /// <summary>
			/// 消防标语
			/// </summary>
			public readonly static Field FireSlogan = new Field("FireSlogan", "TbFireInspection", "消防标语");
            /// <summary>
			/// 消防通道
			/// </summary>
			public readonly static Field FirePassageway = new Field("FirePassageway", "TbFireInspection", "消防通道");
            /// <summary>
			/// 消防管道
			/// </summary>
			public readonly static Field FirePiping = new Field("FirePiping", "TbFireInspection", "消防管道");
            /// <summary>
			/// 检查人员编号
			/// </summary>
			public readonly static Field CheckUserCodes = new Field("CheckUserCodes", "TbFireInspection", "检查人员编号");
            /// <summary>
			/// 检查人员名称
			/// </summary>
			public readonly static Field CheckUserNames = new Field("CheckUserNames", "TbFireInspection", "检查人员名称");
            /// <summary>
			/// 检查时间
			/// </summary>
			public readonly static Field CheckDate = new Field("CheckDate", "TbFireInspection", "检查时间");
            /// <summary>
			/// 问题描述
			/// </summary>
			public readonly static Field ProblemDescription = new Field("ProblemDescription", "TbFireInspection", "问题描述");
            /// <summary>
			/// 附件
			/// </summary>
			public readonly static Field Enclosure = new Field("Enclosure", "TbFireInspection", "附件");
            /// <summary>
			/// 录入人编号
			/// </summary>
			public readonly static Field InsertUserCode = new Field("InsertUserCode", "TbFireInspection", "录入人编号");
            /// <summary>
			/// 录入时间
			/// </summary>
			public readonly static Field InsertTime = new Field("InsertTime", "TbFireInspection", "录入时间");
        }
        #endregion

        #region 扩展字段
        public string ProcessFactoryName { get; set; }
        public string UserName { get; set; }

        #endregion
    }
}