//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36460
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 临时用电检查
    /// </summary>
    [Table("TbInterimUseElectricCheck")]
    [Serializable]
    public partial class TbInterimUseElectricCheck : Entity
    {
        #region Model
		private int _ID;
		private string _CheckCode;
		private string _ProcessFactoryCode;
		private string _epod;
		private string _gorlp;
		private string _drorps;
		private string _dorsb;
		private string _CheckUserCodes;
		private string _CheckUserNames;
		private DateTime? _CheckDate;
		private string _ProblemDescription;
		private string _Enclosure;
		private string _InsertUserCode;
		private DateTime _InsertTime;
		private string _ProjectId;

		/// <summary>
		/// ID
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 检查编号
		/// </summary>
		[Field("CheckCode")]
		public string CheckCode
		{
			get{ return _CheckCode; }
			set
			{
				this.OnPropertyValueChange("CheckCode");
				this._CheckCode = value;
			}
		}
		/// <summary>
		/// 加工厂编号
		/// </summary>
		[Field("ProcessFactoryCode")]
		public string ProcessFactoryCode
		{
			get{ return _ProcessFactoryCode; }
			set
			{
				this.OnPropertyValueChange("ProcessFactoryCode");
				this._ProcessFactoryCode = value;
			}
		}
		/// <summary>
		/// 外电/配电
		/// </summary>
		[Field("epod")]
		public string epod
		{
			get{ return _epod; }
			set
			{
				this.OnPropertyValueChange("epod");
				this._epod = value;
			}
		}
		/// <summary>
		/// 接地/防雷
		/// </summary>
		[Field("gorlp")]
		public string gorlp
		{
			get{ return _gorlp; }
			set
			{
				this.OnPropertyValueChange("gorlp");
				this._gorlp = value;
			}
		}
		/// <summary>
		/// 配电室/备电
		/// </summary>
		[Field("drorps")]
		public string drorps
		{
			get{ return _drorps; }
			set
			{
				this.OnPropertyValueChange("drorps");
				this._drorps = value;
			}
		}
		/// <summary>
		/// 配电/开关箱
		/// </summary>
		[Field("dorsb")]
		public string dorsb
		{
			get{ return _dorsb; }
			set
			{
				this.OnPropertyValueChange("dorsb");
				this._dorsb = value;
			}
		}
		/// <summary>
		/// 检查人员编号
		/// </summary>
		[Field("CheckUserCodes")]
		public string CheckUserCodes
		{
			get{ return _CheckUserCodes; }
			set
			{
				this.OnPropertyValueChange("CheckUserCodes");
				this._CheckUserCodes = value;
			}
		}
		/// <summary>
		/// 检查人员名称
		/// </summary>
		[Field("CheckUserNames")]
		public string CheckUserNames
		{
			get{ return _CheckUserNames; }
			set
			{
				this.OnPropertyValueChange("CheckUserNames");
				this._CheckUserNames = value;
			}
		}
		/// <summary>
		/// 检查时间
		/// </summary>
		[Field("CheckDate")]
		public DateTime? CheckDate
		{
			get{ return _CheckDate; }
			set
			{
				this.OnPropertyValueChange("CheckDate");
				this._CheckDate = value;
			}
		}
		/// <summary>
		/// 问题描述
		/// </summary>
		[Field("ProblemDescription")]
		public string ProblemDescription
		{
			get{ return _ProblemDescription; }
			set
			{
				this.OnPropertyValueChange("ProblemDescription");
				this._ProblemDescription = value;
			}
		}
		/// <summary>
		/// 附件
		/// </summary>
		[Field("Enclosure")]
		public string Enclosure
		{
			get{ return _Enclosure; }
			set
			{
				this.OnPropertyValueChange("Enclosure");
				this._Enclosure = value;
			}
		}
		/// <summary>
		/// 录入人编号
		/// </summary>
		[Field("InsertUserCode")]
		public string InsertUserCode
		{
			get{ return _InsertUserCode; }
			set
			{
				this.OnPropertyValueChange("InsertUserCode");
				this._InsertUserCode = value;
			}
		}
		/// <summary>
		/// 录入时间
		/// </summary>
		[Field("InsertTime")]
		public DateTime InsertTime
		{
			get{ return _InsertTime; }
			set
			{
				this.OnPropertyValueChange("InsertTime");
				this._InsertTime = value;
			}
		}
		/// <summary>
		/// 项目id
		/// </summary>
		[Field("ProjectId")]
		public string ProjectId
		{
			get{ return _ProjectId; }
			set
			{
				this.OnPropertyValueChange("ProjectId");
				this._ProjectId = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.CheckCode,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.CheckCode,
				_.ProcessFactoryCode,
				_.epod,
				_.gorlp,
				_.drorps,
				_.dorsb,
				_.CheckUserCodes,
				_.CheckUserNames,
				_.CheckDate,
				_.ProblemDescription,
				_.Enclosure,
				_.InsertUserCode,
				_.InsertTime,
				_.ProjectId,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._CheckCode,
				this._ProcessFactoryCode,
				this._epod,
				this._gorlp,
				this._drorps,
				this._dorsb,
				this._CheckUserCodes,
				this._CheckUserNames,
				this._CheckDate,
				this._ProblemDescription,
				this._Enclosure,
				this._InsertUserCode,
				this._InsertTime,
				this._ProjectId,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbInterimUseElectricCheck");
            /// <summary>
			/// ID
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbInterimUseElectricCheck", "ID");
            /// <summary>
			/// 检查编号
			/// </summary>
			public readonly static Field CheckCode = new Field("CheckCode", "TbInterimUseElectricCheck", "检查编号");
            /// <summary>
			/// 加工厂编号
			/// </summary>
			public readonly static Field ProcessFactoryCode = new Field("ProcessFactoryCode", "TbInterimUseElectricCheck", "加工厂编号");
            /// <summary>
			/// 外电/配电
			/// </summary>
			public readonly static Field epod = new Field("epod", "TbInterimUseElectricCheck", "外电/配电");
            /// <summary>
			/// 接地/防雷
			/// </summary>
			public readonly static Field gorlp = new Field("gorlp", "TbInterimUseElectricCheck", "接地/防雷");
            /// <summary>
			/// 配电室/备电
			/// </summary>
			public readonly static Field drorps = new Field("drorps", "TbInterimUseElectricCheck", "配电室/备电");
            /// <summary>
			/// 配电/开关箱
			/// </summary>
			public readonly static Field dorsb = new Field("dorsb", "TbInterimUseElectricCheck", "配电/开关箱");
            /// <summary>
			/// 检查人员编号
			/// </summary>
			public readonly static Field CheckUserCodes = new Field("CheckUserCodes", "TbInterimUseElectricCheck", "检查人员编号");
            /// <summary>
			/// 检查人员名称
			/// </summary>
			public readonly static Field CheckUserNames = new Field("CheckUserNames", "TbInterimUseElectricCheck", "检查人员名称");
            /// <summary>
			/// 检查时间
			/// </summary>
			public readonly static Field CheckDate = new Field("CheckDate", "TbInterimUseElectricCheck", "检查时间");
            /// <summary>
			/// 问题描述
			/// </summary>
			public readonly static Field ProblemDescription = new Field("ProblemDescription", "TbInterimUseElectricCheck", "问题描述");
            /// <summary>
			/// 附件
			/// </summary>
			public readonly static Field Enclosure = new Field("Enclosure", "TbInterimUseElectricCheck", "附件");
            /// <summary>
			/// 录入人编号
			/// </summary>
			public readonly static Field InsertUserCode = new Field("InsertUserCode", "TbInterimUseElectricCheck", "录入人编号");
            /// <summary>
			/// 录入时间
			/// </summary>
			public readonly static Field InsertTime = new Field("InsertTime", "TbInterimUseElectricCheck", "录入时间");
            /// <summary>
			/// 项目id
			/// </summary>
			public readonly static Field ProjectId = new Field("ProjectId", "TbInterimUseElectricCheck", "项目id");
        }
        #endregion

        #region 扩展字段
        public string ProcessFactoryName { get; set; }
        public string UserName { get; set; }

        #endregion
	}
}