//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36450
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;
using PM.DataEntity.Base;

namespace PM.DataEntity
{
    /// <summary>
    /// 班前讲话 实体类TbSafeDatumManage。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("TbSafeDatumManage")]
    [Serializable]
    public partial class TbSafeDatumManage : BaseEntity
    {
        #region Model
        private int _ID;
        private string _ContentCode;
        private string _ProcessFactoryCode;
        private string _SpeechTheme;
        private DateTime _StartTime;
        private string _SpeechContent;
        private string _SpeechUser;
        private string _InsertUserCode;
        private DateTime _InsertTime;
        private string _Remarks;
        private int _BrowseCount;

        /// <summary>
        /// 班前讲话 标识ID
        /// </summary>
        [Field("ID")]
        public int ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }

        /// <summary>
        /// 浏览次数
        /// </summary>
        [Field("BrowseCount")]
        public int BrowseCount 
        {
            get { return _BrowseCount; }
            set
            {
                this.OnPropertyValueChange("BrowseCount");
                this._BrowseCount = value;
            }
        }
        /// <summary>
        /// 内容编号
        /// </summary>
        [Field("ContentCode")]
        public string ContentCode
        {
            get { return _ContentCode; }
            set
            {
                this.OnPropertyValueChange("ContentCode");
                this._ContentCode = value;
            }
        }
        /// <summary>
        /// 加工厂Code
        /// </summary>
        [Field("ProcessFactoryCode")]
        public string ProcessFactoryCode
        {
            get { return _ProcessFactoryCode; }
            set
            {
                this.OnPropertyValueChange("ProcessFactoryCode");
                this._ProcessFactoryCode = value;
            }
        }
        /// <summary>
        /// 讲话主题
        /// </summary>
        [Field("SpeechTheme")]
        public string SpeechTheme
        {
            get { return _SpeechTheme; }
            set
            {
                this.OnPropertyValueChange("SpeechTheme");
                this._SpeechTheme = value;
            }
        }
        /// <summary>
        /// 开始时间
        /// </summary>
        [Field("StartTime")]
        public DateTime StartTime
        {
            get { return _StartTime; }
            set
            {
                this.OnPropertyValueChange("StartTime");
                this._StartTime = value;
            }
        }
        /// <summary>
        /// 讲话内容
        /// </summary>
        [Field("SpeechContent")]
        public string SpeechContent
        {
            get { return _SpeechContent; }
            set
            {
                this.OnPropertyValueChange("SpeechContent");
                this._SpeechContent = value;
            }
        }
        /// <summary>
        /// 讲话人
        /// </summary>
        [Field("SpeechUser")]
        public string SpeechUser
        {
            get { return _SpeechUser; }
            set
            {
                this.OnPropertyValueChange("SpeechUser");
                this._SpeechUser = value;
            }
        }
        /// <summary>
        /// 录入人Code
        /// </summary>
        [Field("InsertUserCode")]
        public string InsertUserCode
        {
            get { return _InsertUserCode; }
            set
            {
                this.OnPropertyValueChange("InsertUserCode");
                this._InsertUserCode = value;
            }
        }
        /// <summary>
        /// 录入时间
        /// </summary>
        [Field("InsertTime")]
        public DateTime InsertTime
        {
            get { return _InsertTime; }
            set
            {
                this.OnPropertyValueChange("InsertTime");
                this._InsertTime = value;
            }
        }
        /// <summary>
        /// 备注
        /// </summary>
        [Field("Remarks")]
        public string Remarks
        {
            get { return _Remarks; }
            set
            {
                this.OnPropertyValueChange("Remarks");
                this._Remarks = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ContentCode,
			};
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.ContentCode,
				_.ProcessFactoryCode,
				_.SpeechTheme,
				_.StartTime,
				_.SpeechContent,
				_.SpeechUser,
				_.InsertUserCode,
				_.InsertTime,
				_.Remarks,
                _.BrowseCount,
                _.ProjectId
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._ContentCode,
				this._ProcessFactoryCode,
				this._SpeechTheme,
				this._StartTime,
				this._SpeechContent,
				this._SpeechUser,
				this._InsertUserCode,
				this._InsertTime,
				this._Remarks,
                this._BrowseCount,
                this._ProjectId
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _ : BaseField<TbSafeDatumManage>
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "TbSafeDatumManage");
            /// <summary>
            /// 班前讲话 标识ID
            /// </summary>
            public readonly static Field ID = new Field("ID", "TbSafeDatumManage", "班前讲话 标识ID");
            /// <summary>
            /// 内容编号
            /// </summary>
            public readonly static Field ContentCode = new Field("ContentCode", "TbSafeDatumManage", "内容编号");
            /// <summary>
            /// 加工厂Code
            /// </summary>
            public readonly static Field ProcessFactoryCode = new Field("ProcessFactoryCode", "TbSafeDatumManage", "加工厂Code");
            /// <summary>
            /// 讲话主题
            /// </summary>
            public readonly static Field SpeechTheme = new Field("SpeechTheme", "TbSafeDatumManage", "讲话主题");
            /// <summary>
            /// 开始时间
            /// </summary>
            public readonly static Field StartTime = new Field("StartTime", "TbSafeDatumManage", "开始时间");
            /// <summary>
            /// 讲话内容
            /// </summary>
            public readonly static Field SpeechContent = new Field("SpeechContent", "TbSafeDatumManage", "讲话内容");
            /// <summary>
            /// 讲话人
            /// </summary>
            public readonly static Field SpeechUser = new Field("SpeechUser", "TbSafeDatumManage", "讲话人");
            /// <summary>
            /// 录入人Code
            /// </summary>
            public readonly static Field InsertUserCode = new Field("InsertUserCode", "TbSafeDatumManage", "录入人Code");
            /// <summary>
            /// 录入时间
            /// </summary>
            public readonly static Field InsertTime = new Field("InsertTime", "TbSafeDatumManage", "录入时间");
            /// <summary>
            /// 备注
            /// </summary>
            public readonly static Field Remarks = new Field("Remarks", "TbSafeDatumManage", "备注");
            /// <summary>
            /// 浏览次数
            /// </summary>
            public readonly static Field BrowseCount = new Field("BrowseCount", "TbSafeDatumManage", "浏览次数");
        }
        #endregion
    }
}