//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;
using PM.DataEntity.Base;

namespace PM.DataEntity
{
    /// <summary>
    /// 安全检查
    /// </summary>
    [Table("TbSafeCheck")]
    [Serializable]
    public partial class TbSafeCheck : BaseEntity
    {
        #region Model
		private int _ID;
		private string _SafeCheckCode;
		private string _CheckType;
		private string _Theme;
		private string _Content;
		private string _PartInUsers;
		private string _ProcessFactoryCode;
		private string _CheckUser;
		private DateTime? _CheckTime;
		private string _Remark;
		private string _Examinestatus;
		private string _Enclosure;
		private string _InsertUserCode;
        private DateTime _InsertTime;

		/// <summary>
		/// ID
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 检查编号
		/// </summary>
		[Field("SafeCheckCode")]
		public string SafeCheckCode
		{
			get{ return _SafeCheckCode; }
			set
			{
				this.OnPropertyValueChange("SafeCheckCode");
				this._SafeCheckCode = value;
			}
		}
		/// <summary>
		/// 检查类型
		/// </summary>
		[Field("CheckType")]
		public string CheckType
		{
			get{ return _CheckType; }
			set
			{
				this.OnPropertyValueChange("CheckType");
				this._CheckType = value;
			}
		}
		/// <summary>
		/// 检查主题
		/// </summary>
		[Field("Theme")]
		public string Theme
		{
			get{ return _Theme; }
			set
			{
				this.OnPropertyValueChange("Theme");
				this._Theme = value;
			}
		}
		/// <summary>
		/// 检查内容
		/// </summary>
		[Field("Content")]
		public string Content
		{
			get{ return _Content; }
			set
			{
				this.OnPropertyValueChange("Content");
				this._Content = value;
			}
		}
		/// <summary>
		/// 参与人员
		/// </summary>
		[Field("PartInUsers")]
		public string PartInUsers
		{
			get{ return _PartInUsers; }
			set
			{
				this.OnPropertyValueChange("PartInUsers");
				this._PartInUsers = value;
			}
		}
		/// <summary>
		/// 加工厂编号
		/// </summary>
		[Field("ProcessFactoryCode")]
		public string ProcessFactoryCode
		{
			get{ return _ProcessFactoryCode; }
			set
			{
				this.OnPropertyValueChange("ProcessFactoryCode");
				this._ProcessFactoryCode = value;
			}
		}
		/// <summary>
		/// 检查人
		/// </summary>
		[Field("CheckUser")]
		public string CheckUser
		{
			get{ return _CheckUser; }
			set
			{
				this.OnPropertyValueChange("CheckUser");
				this._CheckUser = value;
			}
		}
		/// <summary>
		/// 检查时间
		/// </summary>
		[Field("CheckTime")]
		public DateTime? CheckTime
		{
			get{ return _CheckTime; }
			set
			{
				this.OnPropertyValueChange("CheckTime");
				this._CheckTime = value;
			}
		}
		/// <summary>
		/// 问题描述
		/// </summary>
		[Field("Remark")]
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange("Remark");
				this._Remark = value;
			}
		}
		/// <summary>
		/// 审批状态
		/// </summary>
		[Field("Examinestatus")]
		public string Examinestatus
		{
			get{ return _Examinestatus; }
			set
			{
				this.OnPropertyValueChange("Examinestatus");
				this._Examinestatus = value;
			}
		}
		/// <summary>
		/// 附件
		/// </summary>
		[Field("Enclosure")]
		public string Enclosure
		{
			get{ return _Enclosure; }
			set
			{
				this.OnPropertyValueChange("Enclosure");
				this._Enclosure = value;
			}
		}
		/// <summary>
		/// 录入人
		/// </summary>
		[Field("InsertUserCode")]
		public string InsertUserCode
		{
			get{ return _InsertUserCode; }
			set
			{
				this.OnPropertyValueChange("InsertUserCode");
				this._InsertUserCode = value;
			}
		}
		/// <summary>
		/// 录入时间
		/// </summary>
		[Field("InsertTime")]
        public DateTime InsertTime
		{
			get{ return _InsertTime; }
			set
			{
				this.OnPropertyValueChange("InsertTime");
				this._InsertTime = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.SafeCheckCode,
				_.CheckType,
				_.Theme,
				_.Content,
				_.PartInUsers,
				_.ProcessFactoryCode,
				_.CheckUser,
				_.CheckTime,
				_.Remark,
				_.Examinestatus,
				_.Enclosure,
				_.InsertUserCode,
				_.InsertTime,
                _.ProjectId
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._SafeCheckCode,
				this._CheckType,
				this._Theme,
				this._Content,
				this._PartInUsers,
				this._ProcessFactoryCode,
				this._CheckUser,
				this._CheckTime,
				this._Remark,
				this._Examinestatus,
				this._Enclosure,
				this._InsertUserCode,
				this._InsertTime,
                this._ProjectId
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _ : BaseField<TbSafeCheck>
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbSafeCheck");
            /// <summary>
			/// ID
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbSafeCheck", "ID");
            /// <summary>
			/// 检查编号
			/// </summary>
			public readonly static Field SafeCheckCode = new Field("SafeCheckCode", "TbSafeCheck", "检查编号");
            /// <summary>
			/// 检查类型
			/// </summary>
			public readonly static Field CheckType = new Field("CheckType", "TbSafeCheck", "检查类型");
            /// <summary>
			/// 检查主题
			/// </summary>
			public readonly static Field Theme = new Field("Theme", "TbSafeCheck", "检查主题");
            /// <summary>
			/// 检查内容
			/// </summary>
			public readonly static Field Content = new Field("Content", "TbSafeCheck", "检查内容");
            /// <summary>
			/// 参与人员
			/// </summary>
			public readonly static Field PartInUsers = new Field("PartInUsers", "TbSafeCheck", "参与人员");
            /// <summary>
			/// 加工厂编号
			/// </summary>
			public readonly static Field ProcessFactoryCode = new Field("ProcessFactoryCode", "TbSafeCheck", "加工厂编号");
            /// <summary>
			/// 检查人
			/// </summary>
			public readonly static Field CheckUser = new Field("CheckUser", "TbSafeCheck", "检查人");
            /// <summary>
			/// 检查时间
			/// </summary>
			public readonly static Field CheckTime = new Field("CheckTime", "TbSafeCheck", "检查时间");
            /// <summary>
			/// 问题描述
			/// </summary>
			public readonly static Field Remark = new Field("Remark", "TbSafeCheck", "问题描述");
            /// <summary>
			/// 审批状态
			/// </summary>
			public readonly static Field Examinestatus = new Field("Examinestatus", "TbSafeCheck", "审批状态");
            /// <summary>
			/// 附件
			/// </summary>
			public readonly static Field Enclosure = new Field("Enclosure", "TbSafeCheck", "附件");
            /// <summary>
			/// 录入人
			/// </summary>
			public readonly static Field InsertUserCode = new Field("InsertUserCode", "TbSafeCheck", "录入人");
            /// <summary>
			/// 录入时间
			/// </summary>
			public readonly static Field InsertTime = new Field("InsertTime", "TbSafeCheck", "录入时间");
        }
        #endregion
	}
}