//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36460
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 实体类TbNoticeNewsOrg。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("TbNoticeNewsOrg")]
    [Serializable]
    public partial class TbNoticeNewsOrg : Entity
    {
        #region Model
		private int _ID;
		private string _NoticeNewsCode;
		private string _OrgType;
		private string _ProjectId;
		private string _PersonnelSource;
		private string _PersonnelCode;
		private string _DeptId;
		private string _RoleId;
		private int? _NewsType;

		/// <summary>
		/// ID
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 通知消息编号
		/// </summary>
		[Field("NoticeNewsCode")]
		public string NoticeNewsCode
		{
			get{ return _NoticeNewsCode; }
			set
			{
				this.OnPropertyValueChange("NoticeNewsCode");
				this._NoticeNewsCode = value;
			}
		}
		/// <summary>
		/// 组织机构类型
		/// </summary>
		[Field("OrgType")]
		public string OrgType
		{
			get{ return _OrgType; }
			set
			{
				this.OnPropertyValueChange("OrgType");
				this._OrgType = value;
			}
		}
		/// <summary>
		/// 项目ID
		/// </summary>
		[Field("ProjectId")]
		public string ProjectId
		{
			get{ return _ProjectId; }
			set
			{
				this.OnPropertyValueChange("ProjectId");
				this._ProjectId = value;
			}
		}
		/// <summary>
		/// 通知人员来源
		/// </summary>
		[Field("PersonnelSource")]
		public string PersonnelSource
		{
			get{ return _PersonnelSource; }
			set
			{
				this.OnPropertyValueChange("PersonnelSource");
				this._PersonnelSource = value;
			}
		}
		/// <summary>
		/// 通知人员
		/// </summary>
		[Field("PersonnelCode")]
		public string PersonnelCode
		{
			get{ return _PersonnelCode; }
			set
			{
				this.OnPropertyValueChange("PersonnelCode");
				this._PersonnelCode = value;
			}
		}
		/// <summary>
		/// 部门id
		/// </summary>
		[Field("DeptId")]
		public string DeptId
		{
			get{ return _DeptId; }
			set
			{
				this.OnPropertyValueChange("DeptId");
				this._DeptId = value;
			}
		}
		/// <summary>
		/// 角色id
		/// </summary>
		[Field("RoleId")]
		public string RoleId
		{
			get{ return _RoleId; }
			set
			{
				this.OnPropertyValueChange("RoleId");
				this._RoleId = value;
			}
		}
		/// <summary>
		/// 消息类型(1:通知消息,2:预警消息)
		/// </summary>
		[Field("NewsType")]
		public int? NewsType
		{
			get{ return _NewsType; }
			set
			{
				this.OnPropertyValueChange("NewsType");
				this._NewsType = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.NoticeNewsCode,
				_.OrgType,
				_.ProjectId,
				_.PersonnelSource,
				_.PersonnelCode,
				_.DeptId,
				_.RoleId,
				_.NewsType,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._NoticeNewsCode,
				this._OrgType,
				this._ProjectId,
				this._PersonnelSource,
				this._PersonnelCode,
				this._DeptId,
				this._RoleId,
				this._NewsType,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbNoticeNewsOrg");
            /// <summary>
			/// ID
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbNoticeNewsOrg", "ID");
            /// <summary>
			/// 通知消息编号
			/// </summary>
			public readonly static Field NoticeNewsCode = new Field("NoticeNewsCode", "TbNoticeNewsOrg", "通知消息编号");
            /// <summary>
			/// 组织机构类型
			/// </summary>
			public readonly static Field OrgType = new Field("OrgType", "TbNoticeNewsOrg", "组织机构类型");
            /// <summary>
			/// 项目ID
			/// </summary>
			public readonly static Field ProjectId = new Field("ProjectId", "TbNoticeNewsOrg", "项目ID");
            /// <summary>
			/// 通知人员来源
			/// </summary>
			public readonly static Field PersonnelSource = new Field("PersonnelSource", "TbNoticeNewsOrg", "通知人员来源");
            /// <summary>
			/// 通知人员
			/// </summary>
			public readonly static Field PersonnelCode = new Field("PersonnelCode", "TbNoticeNewsOrg", "通知人员");
            /// <summary>
			/// 部门id
			/// </summary>
			public readonly static Field DeptId = new Field("DeptId", "TbNoticeNewsOrg", "部门id");
            /// <summary>
			/// 角色id
			/// </summary>
			public readonly static Field RoleId = new Field("RoleId", "TbNoticeNewsOrg", "角色id");
            /// <summary>
			/// 消息类型(1:通知消息,2:预警消息)
			/// </summary>
			public readonly static Field NewsType = new Field("NewsType", "TbNoticeNewsOrg", "消息类型(1:通知消息,2:预警消息)");
        }
        #endregion
	}
}