//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36460
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 实体类TbNoticeNewsSetUp。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("TbNoticeNewsSetUp")]
    [Serializable]
    public partial class TbNoticeNewsSetUp : Entity
    {
        #region Model
		private int _ID;
		private string _NoticeNewsCode;
		private string _MenuCode;
		private string _NoticeNewsName;
		private string _NoticeNewsQzTj;
		private string _NoticeContent;
		private int? _IsStart;
		private int? _NoticeNewsFrequency;
		private int? _App;
		private int? _Pc;

		/// <summary>
		/// ID
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 通知消息编号
		/// </summary>
		[Field("NoticeNewsCode")]
		public string NoticeNewsCode
		{
			get{ return _NoticeNewsCode; }
			set
			{
				this.OnPropertyValueChange("NoticeNewsCode");
				this._NoticeNewsCode = value;
			}
		}
		/// <summary>
		/// 菜单编号
		/// </summary>
		[Field("MenuCode")]
		public string MenuCode
		{
			get{ return _MenuCode; }
			set
			{
				this.OnPropertyValueChange("MenuCode");
				this._MenuCode = value;
			}
		}
		/// <summary>
		/// 通知消息名称
		/// </summary>
		[Field("NoticeNewsName")]
		public string NoticeNewsName
		{
			get{ return _NoticeNewsName; }
			set
			{
				this.OnPropertyValueChange("NoticeNewsName");
				this._NoticeNewsName = value;
			}
		}
		/// <summary>
		/// 通知前置条件
		/// </summary>
		[Field("NoticeNewsQzTj")]
		public string NoticeNewsQzTj
		{
			get{ return _NoticeNewsQzTj; }
			set
			{
				this.OnPropertyValueChange("NoticeNewsQzTj");
				this._NoticeNewsQzTj = value;
			}
		}
		/// <summary>
		/// 通知内容
		/// </summary>
		[Field("NoticeContent")]
		public string NoticeContent
		{
			get{ return _NoticeContent; }
			set
			{
				this.OnPropertyValueChange("NoticeContent");
				this._NoticeContent = value;
			}
		}
		/// <summary>
		/// 是否启动（0：不启动，1：启动）
		/// </summary>
		[Field("IsStart")]
		public int? IsStart
		{
			get{ return _IsStart; }
			set
			{
				this.OnPropertyValueChange("IsStart");
				this._IsStart = value;
			}
		}
		/// <summary>
		/// 消息推送频率
		/// </summary>
		[Field("NoticeNewsFrequency")]
		public int? NoticeNewsFrequency
		{
			get{ return _NoticeNewsFrequency; }
			set
			{
				this.OnPropertyValueChange("NoticeNewsFrequency");
				this._NoticeNewsFrequency = value;
			}
		}
		/// <summary>
		/// App
		/// </summary>
		[Field("App")]
		public int? App
		{
			get{ return _App; }
			set
			{
				this.OnPropertyValueChange("App");
				this._App = value;
			}
		}
		/// <summary>
		/// PC
		/// </summary>
		[Field("Pc")]
		public int? Pc
		{
			get{ return _Pc; }
			set
			{
				this.OnPropertyValueChange("Pc");
				this._Pc = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.NoticeNewsCode,
				_.MenuCode,
				_.NoticeNewsName,
				_.NoticeNewsQzTj,
				_.NoticeContent,
				_.IsStart,
				_.NoticeNewsFrequency,
				_.App,
				_.Pc,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._NoticeNewsCode,
				this._MenuCode,
				this._NoticeNewsName,
				this._NoticeNewsQzTj,
				this._NoticeContent,
				this._IsStart,
				this._NoticeNewsFrequency,
				this._App,
				this._Pc,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbNoticeNewsSetUp");
            /// <summary>
			/// ID
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbNoticeNewsSetUp", "ID");
            /// <summary>
			/// 通知消息编号
			/// </summary>
			public readonly static Field NoticeNewsCode = new Field("NoticeNewsCode", "TbNoticeNewsSetUp", "通知消息编号");
            /// <summary>
			/// 菜单编号
			/// </summary>
			public readonly static Field MenuCode = new Field("MenuCode", "TbNoticeNewsSetUp", "菜单编号");
            /// <summary>
			/// 通知消息名称
			/// </summary>
			public readonly static Field NoticeNewsName = new Field("NoticeNewsName", "TbNoticeNewsSetUp", "通知消息名称");
            /// <summary>
			/// 通知前置条件
			/// </summary>
			public readonly static Field NoticeNewsQzTj = new Field("NoticeNewsQzTj", "TbNoticeNewsSetUp", "通知前置条件");
            /// <summary>
			/// 通知内容
			/// </summary>
			public readonly static Field NoticeContent = new Field("NoticeContent", "TbNoticeNewsSetUp", "通知内容");
            /// <summary>
			/// 是否启动（0：不启动，1：启动）
			/// </summary>
			public readonly static Field IsStart = new Field("IsStart", "TbNoticeNewsSetUp", "是否启动（0：不启动，1：启动）");
            /// <summary>
			/// 消息推送频率
			/// </summary>
			public readonly static Field NoticeNewsFrequency = new Field("NoticeNewsFrequency", "TbNoticeNewsSetUp", "消息推送频率");
            /// <summary>
			/// App
			/// </summary>
			public readonly static Field App = new Field("App", "TbNoticeNewsSetUp", "App");
            /// <summary>
			/// PC
			/// </summary>
			public readonly static Field Pc = new Field("Pc", "TbNoticeNewsSetUp", "PC");
        }
        #endregion
	}
}