//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36460
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 加工厂批次需求计划
    /// </summary>
    [Table("TbFactoryBatchNeedPlan")]
    [Serializable]
    public partial class TbFactoryBatchNeedPlan : Entity
    {
        #region Model
		private int _ID;
		private string _BatchPlanNum;
		private string _RawMaterialDemandNum;
		private string _SteelsTypeCode;
		private string _BranchCode;
		private string _SiteCode;
		private string _SupplierCode;
		private string _DeliveryPlace;
		private string _Acceptor;
		private string _ContactWay;
		private string _ProcessFactoryCode;
		private decimal? _BatchPlanTotal;
		private string _InsertUserCode;
		private DateTime _InsertTime;
		private string _Remarks;
		private string _Examinestatus;
		private string _Enclosure;
		private string _SiteStaffCode;
		private DateTime? _ArrivalDate;
		private string _ProjectId;
		private string _WorkAreaCode;
		private int? _IsDefault;

		/// <summary>
		/// 加工厂批次需求计划   标识ID
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 批次计划编号
		/// </summary>
		[Field("BatchPlanNum")]
		public string BatchPlanNum
		{
			get{ return _BatchPlanNum; }
			set
			{
				this.OnPropertyValueChange("BatchPlanNum");
				this._BatchPlanNum = value;
			}
		}
		/// <summary>
		/// 原材需求编号
		/// </summary>
		[Field("RawMaterialDemandNum")]
		public string RawMaterialDemandNum
		{
			get{ return _RawMaterialDemandNum; }
			set
			{
				this.OnPropertyValueChange("RawMaterialDemandNum");
				this._RawMaterialDemandNum = value;
			}
		}
		/// <summary>
		/// 钢材类型Code
		/// </summary>
		[Field("SteelsTypeCode")]
		public string SteelsTypeCode
		{
			get{ return _SteelsTypeCode; }
			set
			{
				this.OnPropertyValueChange("SteelsTypeCode");
				this._SteelsTypeCode = value;
			}
		}
		/// <summary>
		/// 分部名称Code
		/// </summary>
		[Field("BranchCode")]
		public string BranchCode
		{
			get{ return _BranchCode; }
			set
			{
				this.OnPropertyValueChange("BranchCode");
				this._BranchCode = value;
			}
		}
		/// <summary>
		/// 站点名称Code
		/// </summary>
		[Field("SiteCode")]
		public string SiteCode
		{
			get{ return _SiteCode; }
			set
			{
				this.OnPropertyValueChange("SiteCode");
				this._SiteCode = value;
			}
		}
		/// <summary>
		/// 供应商名称Code
		/// </summary>
		[Field("SupplierCode")]
		public string SupplierCode
		{
			get{ return _SupplierCode; }
			set
			{
				this.OnPropertyValueChange("SupplierCode");
				this._SupplierCode = value;
			}
		}
		/// <summary>
		/// 交货地点
		/// </summary>
		[Field("DeliveryPlace")]
		public string DeliveryPlace
		{
			get{ return _DeliveryPlace; }
			set
			{
				this.OnPropertyValueChange("DeliveryPlace");
				this._DeliveryPlace = value;
			}
		}
		/// <summary>
		/// 验收人
		/// </summary>
		[Field("Acceptor")]
		public string Acceptor
		{
			get{ return _Acceptor; }
			set
			{
				this.OnPropertyValueChange("Acceptor");
				this._Acceptor = value;
			}
		}
		/// <summary>
		/// 联系方式
		/// </summary>
		[Field("ContactWay")]
		public string ContactWay
		{
			get{ return _ContactWay; }
			set
			{
				this.OnPropertyValueChange("ContactWay");
				this._ContactWay = value;
			}
		}
		/// <summary>
		/// 加工厂Code
		/// </summary>
		[Field("ProcessFactoryCode")]
		public string ProcessFactoryCode
		{
			get{ return _ProcessFactoryCode; }
			set
			{
				this.OnPropertyValueChange("ProcessFactoryCode");
				this._ProcessFactoryCode = value;
			}
		}
		/// <summary>
		/// 批次计划总量
		/// </summary>
		[Field("BatchPlanTotal")]
		public decimal? BatchPlanTotal
		{
			get{ return _BatchPlanTotal; }
			set
			{
				this.OnPropertyValueChange("BatchPlanTotal");
				this._BatchPlanTotal = value;
			}
		}
		/// <summary>
		/// 录入人Code
		/// </summary>
		[Field("InsertUserCode")]
		public string InsertUserCode
		{
			get{ return _InsertUserCode; }
			set
			{
				this.OnPropertyValueChange("InsertUserCode");
				this._InsertUserCode = value;
			}
		}
		/// <summary>
		/// 录入时间
		/// </summary>
		[Field("InsertTime")]
		public DateTime InsertTime
		{
			get{ return _InsertTime; }
			set
			{
				this.OnPropertyValueChange("InsertTime");
				this._InsertTime = value;
			}
		}
		/// <summary>
		/// 备注
		/// </summary>
		[Field("Remarks")]
		public string Remarks
		{
			get{ return _Remarks; }
			set
			{
				this.OnPropertyValueChange("Remarks");
				this._Remarks = value;
			}
		}
		/// <summary>
		/// 审批状态
		/// </summary>
		[Field("Examinestatus")]
		public string Examinestatus
		{
			get{ return _Examinestatus; }
			set
			{
				this.OnPropertyValueChange("Examinestatus");
				this._Examinestatus = value;
			}
		}
		/// <summary>
		/// 附件
		/// </summary>
		[Field("Enclosure")]
		public string Enclosure
		{
			get{ return _Enclosure; }
			set
			{
				this.OnPropertyValueChange("Enclosure");
				this._Enclosure = value;
			}
		}
		/// <summary>
		/// 站点人员
		/// </summary>
		[Field("SiteStaffCode")]
		public string SiteStaffCode
		{
			get{ return _SiteStaffCode; }
			set
			{
				this.OnPropertyValueChange("SiteStaffCode");
				this._SiteStaffCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ArrivalDate")]
		public DateTime? ArrivalDate
		{
			get{ return _ArrivalDate; }
			set
			{
				this.OnPropertyValueChange("ArrivalDate");
				this._ArrivalDate = value;
			}
		}
		/// <summary>
		/// 项目编号
		/// </summary>
		[Field("ProjectId")]
		public string ProjectId
		{
			get{ return _ProjectId; }
			set
			{
				this.OnPropertyValueChange("ProjectId");
				this._ProjectId = value;
			}
		}
		/// <summary>
		/// 工区
		/// </summary>
		[Field("WorkAreaCode")]
		public string WorkAreaCode
		{
			get{ return _WorkAreaCode; }
			set
			{
				this.OnPropertyValueChange("WorkAreaCode");
				this._WorkAreaCode = value;
			}
		}
		/// <summary>
		/// 是否默认
		/// </summary>
		[Field("IsDefault")]
		public int? IsDefault
		{
			get{ return _IsDefault; }
			set
			{
				this.OnPropertyValueChange("IsDefault");
				this._IsDefault = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.BatchPlanNum,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.BatchPlanNum,
				_.RawMaterialDemandNum,
				_.SteelsTypeCode,
				_.BranchCode,
				_.SiteCode,
				_.SupplierCode,
				_.DeliveryPlace,
				_.Acceptor,
				_.ContactWay,
				_.ProcessFactoryCode,
				_.BatchPlanTotal,
				_.InsertUserCode,
				_.InsertTime,
				_.Remarks,
				_.Examinestatus,
				_.Enclosure,
				_.SiteStaffCode,
				_.ArrivalDate,
				_.ProjectId,
				_.WorkAreaCode,
				_.IsDefault,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._BatchPlanNum,
				this._RawMaterialDemandNum,
				this._SteelsTypeCode,
				this._BranchCode,
				this._SiteCode,
				this._SupplierCode,
				this._DeliveryPlace,
				this._Acceptor,
				this._ContactWay,
				this._ProcessFactoryCode,
				this._BatchPlanTotal,
				this._InsertUserCode,
				this._InsertTime,
				this._Remarks,
				this._Examinestatus,
				this._Enclosure,
				this._SiteStaffCode,
				this._ArrivalDate,
				this._ProjectId,
				this._WorkAreaCode,
				this._IsDefault,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbFactoryBatchNeedPlan");
            /// <summary>
			/// 加工厂批次需求计划   标识ID
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbFactoryBatchNeedPlan", "加工厂批次需求计划   标识ID");
            /// <summary>
			/// 批次计划编号
			/// </summary>
			public readonly static Field BatchPlanNum = new Field("BatchPlanNum", "TbFactoryBatchNeedPlan", "批次计划编号");
            /// <summary>
			/// 原材需求编号
			/// </summary>
			public readonly static Field RawMaterialDemandNum = new Field("RawMaterialDemandNum", "TbFactoryBatchNeedPlan", "原材需求编号");
            /// <summary>
			/// 钢材类型Code
			/// </summary>
			public readonly static Field SteelsTypeCode = new Field("SteelsTypeCode", "TbFactoryBatchNeedPlan", "钢材类型Code");
            /// <summary>
			/// 分部名称Code
			/// </summary>
			public readonly static Field BranchCode = new Field("BranchCode", "TbFactoryBatchNeedPlan", "分部名称Code");
            /// <summary>
			/// 站点名称Code
			/// </summary>
			public readonly static Field SiteCode = new Field("SiteCode", "TbFactoryBatchNeedPlan", "站点名称Code");
            /// <summary>
			/// 供应商名称Code
			/// </summary>
			public readonly static Field SupplierCode = new Field("SupplierCode", "TbFactoryBatchNeedPlan", "供应商名称Code");
            /// <summary>
			/// 交货地点
			/// </summary>
			public readonly static Field DeliveryPlace = new Field("DeliveryPlace", "TbFactoryBatchNeedPlan", "交货地点");
            /// <summary>
			/// 验收人
			/// </summary>
			public readonly static Field Acceptor = new Field("Acceptor", "TbFactoryBatchNeedPlan", "验收人");
            /// <summary>
			/// 联系方式
			/// </summary>
			public readonly static Field ContactWay = new Field("ContactWay", "TbFactoryBatchNeedPlan", "联系方式");
            /// <summary>
			/// 加工厂Code
			/// </summary>
			public readonly static Field ProcessFactoryCode = new Field("ProcessFactoryCode", "TbFactoryBatchNeedPlan", "加工厂Code");
            /// <summary>
			/// 批次计划总量
			/// </summary>
			public readonly static Field BatchPlanTotal = new Field("BatchPlanTotal", "TbFactoryBatchNeedPlan", "批次计划总量");
            /// <summary>
			/// 录入人Code
			/// </summary>
			public readonly static Field InsertUserCode = new Field("InsertUserCode", "TbFactoryBatchNeedPlan", "录入人Code");
            /// <summary>
			/// 录入时间
			/// </summary>
			public readonly static Field InsertTime = new Field("InsertTime", "TbFactoryBatchNeedPlan", "录入时间");
            /// <summary>
			/// 备注
			/// </summary>
			public readonly static Field Remarks = new Field("Remarks", "TbFactoryBatchNeedPlan", "备注");
            /// <summary>
			/// 审批状态
			/// </summary>
			public readonly static Field Examinestatus = new Field("Examinestatus", "TbFactoryBatchNeedPlan", "审批状态");
            /// <summary>
			/// 附件
			/// </summary>
			public readonly static Field Enclosure = new Field("Enclosure", "TbFactoryBatchNeedPlan", "附件");
            /// <summary>
			/// 站点人员
			/// </summary>
			public readonly static Field SiteStaffCode = new Field("SiteStaffCode", "TbFactoryBatchNeedPlan", "站点人员");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ArrivalDate = new Field("ArrivalDate", "TbFactoryBatchNeedPlan", "");
            /// <summary>
			/// 项目编号
			/// </summary>
			public readonly static Field ProjectId = new Field("ProjectId", "TbFactoryBatchNeedPlan", "项目编号");
            /// <summary>
			/// 工区
			/// </summary>
			public readonly static Field WorkAreaCode = new Field("WorkAreaCode", "TbFactoryBatchNeedPlan", "工区");
            /// <summary>
			/// 是否默认
			/// </summary>
			public readonly static Field IsDefault = new Field("IsDefault", "TbFactoryBatchNeedPlan", "是否默认");
        }
        #endregion
	}
}