//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 入库单
    /// </summary>
    [Table("TbInOrder")]
    [Serializable]
    public partial class TbInOrder : Entity
    {
        #region Model
		private int _ID;
		private string _InOrderCode;
		private string _BatchPlanCode;
		private string _SiteCode;
		private string _StorageCode;
		private string _RebarType;
		private string _SupplierCode;
		private string _Tel;
		private string _Address;
		private decimal _InCount;
		private string _UserCode;
		private string _Remark;
		private string _Examinestatus;
		private string _Enclosure;
		private string _InsertUserCode;
		private DateTime _InsertTime;
		private string _InOrderState;
		private string _SampleOrderState;
		private string _ProjectId;
		private string _WorkAreaCode;
		private int? _ChackResult;
		private string _SiteUserTel;
		private decimal? _NoPassTotal;
		private DateTime? _SampleOrderTime;

		/// <summary>
		/// ID
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 入库单号
		/// </summary>
		[Field("InOrderCode")]
		public string InOrderCode
		{
			get{ return _InOrderCode; }
			set
			{
				this.OnPropertyValueChange("InOrderCode");
				this._InOrderCode = value;
			}
		}
		/// <summary>
		/// 批次计划编号
		/// </summary>
		[Field("BatchPlanCode")]
		public string BatchPlanCode
		{
			get{ return _BatchPlanCode; }
			set
			{
				this.OnPropertyValueChange("BatchPlanCode");
				this._BatchPlanCode = value;
			}
		}
		/// <summary>
		/// 站点名称
		/// </summary>
		[Field("SiteCode")]
		public string SiteCode
		{
			get{ return _SiteCode; }
			set
			{
				this.OnPropertyValueChange("SiteCode");
				this._SiteCode = value;
			}
		}
		/// <summary>
		/// 入库仓库
		/// </summary>
		[Field("StorageCode")]
		public string StorageCode
		{
			get{ return _StorageCode; }
			set
			{
				this.OnPropertyValueChange("StorageCode");
				this._StorageCode = value;
			}
		}
		/// <summary>
		/// 钢筋类型
		/// </summary>
		[Field("RebarType")]
		public string RebarType
		{
			get{ return _RebarType; }
			set
			{
				this.OnPropertyValueChange("RebarType");
				this._RebarType = value;
			}
		}
		/// <summary>
		/// 供应商编号
		/// </summary>
		[Field("SupplierCode")]
		public string SupplierCode
		{
			get{ return _SupplierCode; }
			set
			{
				this.OnPropertyValueChange("SupplierCode");
				this._SupplierCode = value;
			}
		}
		/// <summary>
		/// 联系方式
		/// </summary>
		[Field("Tel")]
		public string Tel
		{
			get{ return _Tel; }
			set
			{
				this.OnPropertyValueChange("Tel");
				this._Tel = value;
			}
		}
		/// <summary>
		/// 交货地点
		/// </summary>
		[Field("Address")]
		public string Address
		{
			get{ return _Address; }
			set
			{
				this.OnPropertyValueChange("Address");
				this._Address = value;
			}
		}
		/// <summary>
		/// 入库总量
		/// </summary>
		[Field("InCount")]
		public decimal InCount
		{
			get{ return _InCount; }
			set
			{
				this.OnPropertyValueChange("InCount");
				this._InCount = value;
			}
		}
		/// <summary>
		/// 站点人员
		/// </summary>
		[Field("UserCode")]
		public string UserCode
		{
			get{ return _UserCode; }
			set
			{
				this.OnPropertyValueChange("UserCode");
				this._UserCode = value;
			}
		}
		/// <summary>
		/// 备注
		/// </summary>
		[Field("Remark")]
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange("Remark");
				this._Remark = value;
			}
		}
		/// <summary>
		/// 审批状态
		/// </summary>
		[Field("Examinestatus")]
		public string Examinestatus
		{
			get{ return _Examinestatus; }
			set
			{
				this.OnPropertyValueChange("Examinestatus");
				this._Examinestatus = value;
			}
		}
		/// <summary>
		/// 附件
		/// </summary>
		[Field("Enclosure")]
		public string Enclosure
		{
			get{ return _Enclosure; }
			set
			{
				this.OnPropertyValueChange("Enclosure");
				this._Enclosure = value;
			}
		}
		/// <summary>
		/// 录入人
		/// </summary>
		[Field("InsertUserCode")]
		public string InsertUserCode
		{
			get{ return _InsertUserCode; }
			set
			{
				this.OnPropertyValueChange("InsertUserCode");
				this._InsertUserCode = value;
			}
		}
		/// <summary>
		/// 录入时间
		/// </summary>
		[Field("InsertTime")]
		public DateTime InsertTime
		{
			get{ return _InsertTime; }
			set
			{
				this.OnPropertyValueChange("InsertTime");
				this._InsertTime = value;
			}
		}
		/// <summary>
		/// 入库状态：完全入库 、部分入库
		/// </summary>
		[Field("InOrderState")]
		public string InOrderState
		{
			get{ return _InOrderState; }
			set
			{
				this.OnPropertyValueChange("InOrderState");
				this._InOrderState = value;
			}
		}
		/// <summary>
		/// 取样状态：取样未完成 、取样完成
		/// </summary>
		[Field("SampleOrderState")]
		public string SampleOrderState
		{
			get{ return _SampleOrderState; }
			set
			{
				this.OnPropertyValueChange("SampleOrderState");
				this._SampleOrderState = value;
			}
		}
		/// <summary>
		/// 项目id
		/// </summary>
		[Field("ProjectId")]
		public string ProjectId
		{
			get{ return _ProjectId; }
			set
			{
				this.OnPropertyValueChange("ProjectId");
				this._ProjectId = value;
			}
		}
		/// <summary>
		/// 工区
		/// </summary>
		[Field("WorkAreaCode")]
		public string WorkAreaCode
		{
			get{ return _WorkAreaCode; }
			set
			{
				this.OnPropertyValueChange("WorkAreaCode");
				this._WorkAreaCode = value;
			}
		}
		/// <summary>
		/// 检测结果（0未检测 1合格 2不合格 3部分合格）
		/// </summary>
		[Field("ChackResult")]
		public int? ChackResult
		{
			get{ return _ChackResult; }
			set
			{
				this.OnPropertyValueChange("ChackResult");
				this._ChackResult = value;
			}
		}
		/// <summary>
		/// 站点人员联系方式
		/// </summary>
		[Field("SiteUserTel")]
		public string SiteUserTel
		{
			get{ return _SiteUserTel; }
			set
			{
				this.OnPropertyValueChange("SiteUserTel");
				this._SiteUserTel = value;
			}
		}
		/// <summary>
		/// 不合格总量
		/// </summary>
		[Field("NoPassTotal")]
		public decimal? NoPassTotal
		{
			get{ return _NoPassTotal; }
			set
			{
				this.OnPropertyValueChange("NoPassTotal");
				this._NoPassTotal = value;
			}
		}
		/// <summary>
		/// 取样完成时间
		/// </summary>
		[Field("SampleOrderTime")]
		public DateTime? SampleOrderTime
		{
			get{ return _SampleOrderTime; }
			set
			{
				this.OnPropertyValueChange("SampleOrderTime");
				this._SampleOrderTime = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.InOrderCode,
				_.BatchPlanCode,
				_.SiteCode,
				_.StorageCode,
				_.RebarType,
				_.SupplierCode,
				_.Tel,
				_.Address,
				_.InCount,
				_.UserCode,
				_.Remark,
				_.Examinestatus,
				_.Enclosure,
				_.InsertUserCode,
				_.InsertTime,
				_.InOrderState,
				_.SampleOrderState,
				_.ProjectId,
				_.WorkAreaCode,
				_.ChackResult,
				_.SiteUserTel,
				_.NoPassTotal,
				_.SampleOrderTime,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._InOrderCode,
				this._BatchPlanCode,
				this._SiteCode,
				this._StorageCode,
				this._RebarType,
				this._SupplierCode,
				this._Tel,
				this._Address,
				this._InCount,
				this._UserCode,
				this._Remark,
				this._Examinestatus,
				this._Enclosure,
				this._InsertUserCode,
				this._InsertTime,
				this._InOrderState,
				this._SampleOrderState,
				this._ProjectId,
				this._WorkAreaCode,
				this._ChackResult,
				this._SiteUserTel,
				this._NoPassTotal,
				this._SampleOrderTime,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbInOrder");
            /// <summary>
			/// ID
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbInOrder", "ID");
            /// <summary>
			/// 入库单号
			/// </summary>
			public readonly static Field InOrderCode = new Field("InOrderCode", "TbInOrder", "入库单号");
            /// <summary>
			/// 批次计划编号
			/// </summary>
			public readonly static Field BatchPlanCode = new Field("BatchPlanCode", "TbInOrder", "批次计划编号");
            /// <summary>
			/// 站点名称
			/// </summary>
			public readonly static Field SiteCode = new Field("SiteCode", "TbInOrder", "站点名称");
            /// <summary>
			/// 入库仓库
			/// </summary>
			public readonly static Field StorageCode = new Field("StorageCode", "TbInOrder", "入库仓库");
            /// <summary>
			/// 钢筋类型
			/// </summary>
			public readonly static Field RebarType = new Field("RebarType", "TbInOrder", "钢筋类型");
            /// <summary>
			/// 供应商编号
			/// </summary>
			public readonly static Field SupplierCode = new Field("SupplierCode", "TbInOrder", "供应商编号");
            /// <summary>
			/// 联系方式
			/// </summary>
			public readonly static Field Tel = new Field("Tel", "TbInOrder", "联系方式");
            /// <summary>
			/// 交货地点
			/// </summary>
			public readonly static Field Address = new Field("Address", "TbInOrder", "交货地点");
            /// <summary>
			/// 入库总量
			/// </summary>
			public readonly static Field InCount = new Field("InCount", "TbInOrder", "入库总量");
            /// <summary>
			/// 站点人员
			/// </summary>
			public readonly static Field UserCode = new Field("UserCode", "TbInOrder", "站点人员");
            /// <summary>
			/// 备注
			/// </summary>
			public readonly static Field Remark = new Field("Remark", "TbInOrder", "备注");
            /// <summary>
			/// 审批状态
			/// </summary>
			public readonly static Field Examinestatus = new Field("Examinestatus", "TbInOrder", "审批状态");
            /// <summary>
			/// 附件
			/// </summary>
			public readonly static Field Enclosure = new Field("Enclosure", "TbInOrder", "附件");
            /// <summary>
			/// 录入人
			/// </summary>
			public readonly static Field InsertUserCode = new Field("InsertUserCode", "TbInOrder", "录入人");
            /// <summary>
			/// 录入时间
			/// </summary>
			public readonly static Field InsertTime = new Field("InsertTime", "TbInOrder", "录入时间");
            /// <summary>
			/// 入库状态：完全入库 、部分入库
			/// </summary>
			public readonly static Field InOrderState = new Field("InOrderState", "TbInOrder", "入库状态：完全入库 、部分入库");
            /// <summary>
			/// 取样状态：取样未完成 、取样完成
			/// </summary>
			public readonly static Field SampleOrderState = new Field("SampleOrderState", "TbInOrder", "取样状态：取样未完成 、取样完成");
            /// <summary>
			/// 项目id
			/// </summary>
			public readonly static Field ProjectId = new Field("ProjectId", "TbInOrder", "项目id");
            /// <summary>
			/// 工区
			/// </summary>
			public readonly static Field WorkAreaCode = new Field("WorkAreaCode", "TbInOrder", "工区");
            /// <summary>
			/// 检测结果（0未检测 1合格 2不合格 3部分合格）
			/// </summary>
			public readonly static Field ChackResult = new Field("ChackResult", "TbInOrder", "检测结果（0未检测 1合格 2不合格 3部分合格）");
            /// <summary>
			/// 站点人员联系方式
			/// </summary>
			public readonly static Field SiteUserTel = new Field("SiteUserTel", "TbInOrder", "站点人员联系方式");
            /// <summary>
			/// 不合格总量
			/// </summary>
			public readonly static Field NoPassTotal = new Field("NoPassTotal", "TbInOrder", "不合格总量");
            /// <summary>
			/// 取样完成时间
			/// </summary>
			public readonly static Field SampleOrderTime = new Field("SampleOrderTime", "TbInOrder", "取样完成时间");
        }
        #endregion
	}
}