//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36460
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    ///  原材料月度需求计划明细
    /// </summary>
    [Table("TbRawMaterialMonthDemandPlanDetail")]
    [Serializable]
    public partial class TbRawMaterialMonthDemandPlanDetail : Entity
    {
        #region Model
		private int _ID;
		private string _DemandPlanCode;
		private string _MaterialCode;
		private string _MaterialName;
		private string _SpecificationModel;
		private string _MeasurementUnit;
		private decimal _DemandNum;
		private string _SkillRequire;
		private string _Remark;

		/// <summary>
		/// ID
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 需求计划编号
		/// </summary>
		[Field("DemandPlanCode")]
		public string DemandPlanCode
		{
			get{ return _DemandPlanCode; }
			set
			{
				this.OnPropertyValueChange("DemandPlanCode");
				this._DemandPlanCode = value;
			}
		}
		/// <summary>
		/// 原材料编号
		/// </summary>
		[Field("MaterialCode")]
		public string MaterialCode
		{
			get{ return _MaterialCode; }
			set
			{
				this.OnPropertyValueChange("MaterialCode");
				this._MaterialCode = value;
			}
		}
		/// <summary>
		/// 原材料名称
		/// </summary>
		[Field("MaterialName")]
		public string MaterialName
		{
			get{ return _MaterialName; }
			set
			{
				this.OnPropertyValueChange("MaterialName");
				this._MaterialName = value;
			}
		}
		/// <summary>
		/// 规格
		/// </summary>
		[Field("SpecificationModel")]
		public string SpecificationModel
		{
			get{ return _SpecificationModel; }
			set
			{
				this.OnPropertyValueChange("SpecificationModel");
				this._SpecificationModel = value;
			}
		}
		/// <summary>
		/// 计量单位
		/// </summary>
		[Field("MeasurementUnit")]
		public string MeasurementUnit
		{
			get{ return _MeasurementUnit; }
			set
			{
				this.OnPropertyValueChange("MeasurementUnit");
				this._MeasurementUnit = value;
			}
		}
        public string MeasurementUnitText { get; set; }
		/// <summary>
		/// 需求数量
		/// </summary>
		[Field("DemandNum")]
		public decimal DemandNum
		{
			get{ return _DemandNum; }
			set
			{
				this.OnPropertyValueChange("DemandNum");
				this._DemandNum = value;
			}
		}
		/// <summary>
		/// 技术要求
		/// </summary>
		[Field("SkillRequire")]
		public string SkillRequire
		{
			get{ return _SkillRequire; }
			set
			{
				this.OnPropertyValueChange("SkillRequire");
				this._SkillRequire = value;
			}
		}
		/// <summary>
		/// 备注
		/// </summary>
		[Field("Remark")]
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange("Remark");
				this._Remark = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.DemandPlanCode,
				_.MaterialCode,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.DemandPlanCode,
				_.MaterialCode,
				_.MaterialName,
				_.SpecificationModel,
				_.MeasurementUnit,
				_.DemandNum,
				_.SkillRequire,
				_.Remark,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._DemandPlanCode,
				this._MaterialCode,
				this._MaterialName,
				this._SpecificationModel,
				this._MeasurementUnit,
				this._DemandNum,
				this._SkillRequire,
				this._Remark,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbRawMaterialMonthDemandPlanDetail");
            /// <summary>
			/// ID
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbRawMaterialMonthDemandPlanDetail", "ID");
            /// <summary>
			/// 需求计划编号
			/// </summary>
			public readonly static Field DemandPlanCode = new Field("DemandPlanCode", "TbRawMaterialMonthDemandPlanDetail", "需求计划编号");
            /// <summary>
			/// 原材料编号
			/// </summary>
			public readonly static Field MaterialCode = new Field("MaterialCode", "TbRawMaterialMonthDemandPlanDetail", "原材料编号");
            /// <summary>
			/// 原材料名称
			/// </summary>
			public readonly static Field MaterialName = new Field("MaterialName", "TbRawMaterialMonthDemandPlanDetail", "原材料名称");
            /// <summary>
			/// 规格
			/// </summary>
			public readonly static Field SpecificationModel = new Field("SpecificationModel", "TbRawMaterialMonthDemandPlanDetail", "规格");
            /// <summary>
			/// 计量单位
			/// </summary>
			public readonly static Field MeasurementUnit = new Field("MeasurementUnit", "TbRawMaterialMonthDemandPlanDetail", "计量单位");
            /// <summary>
			/// 需求数量
			/// </summary>
			public readonly static Field DemandNum = new Field("DemandNum", "TbRawMaterialMonthDemandPlanDetail", "需求数量");
            /// <summary>
			/// 技术要求
			/// </summary>
			public readonly static Field SkillRequire = new Field("SkillRequire", "TbRawMaterialMonthDemandPlanDetail", "技术要求");
            /// <summary>
			/// 备注
			/// </summary>
			public readonly static Field Remark = new Field("Remark", "TbRawMaterialMonthDemandPlanDetail", "备注");
        }
        #endregion
	}
}