//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 原材料生产领料明细
    /// </summary>
    [Table("TbRMProductionMaterialDetail")]
    [Serializable]
    public partial class TbRMProductionMaterialDetail : Entity
    {
        #region Model
		private int _ID;
		private string _CollarCode;
		private string _MaterialCode;
		private string _SpecificationModel;
		private decimal _MeasurementUnitZl;
		private decimal _ItemUseNum;
		private int _Number;
		private decimal _WeightSmallPlan;
		private string _RMTypeName;
		private decimal _SizeSelection;
		private int _RootNumber;
		private decimal _WeightSmallPlanN;
		private string _Manufactor;
		private string _HeatNo;
		private string _TestReportNo;
		private string _MaterialName;
		private string _ComponentName;
		private string _OrderCode;
		private string _CloutStockID;
		private int? _WorkOrderItemId;
		private string _InOrderItemId;
		private int? _NumberH;
		private string _SizeSelectionStr;
		private string _RootNumberStr;

		/// <summary>
		/// 主键ID
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 领用单号
		/// </summary>
		[Field("CollarCode")]
		public string CollarCode
		{
			get{ return _CollarCode; }
			set
			{
				this.OnPropertyValueChange("CollarCode");
				this._CollarCode = value;
			}
		}
		/// <summary>
		/// 原材料名称/编号
		/// </summary>
		[Field("MaterialCode")]
		public string MaterialCode
		{
			get{ return _MaterialCode; }
			set
			{
				this.OnPropertyValueChange("MaterialCode");
				this._MaterialCode = value;
			}
		}
		/// <summary>
		/// 规格型号
		/// </summary>
		[Field("SpecificationModel")]
		public string SpecificationModel
		{
			get{ return _SpecificationModel; }
			set
			{
				this.OnPropertyValueChange("SpecificationModel");
				this._SpecificationModel = value;
			}
		}
		/// <summary>
		/// 单位重量
		/// </summary>
		[Field("MeasurementUnitZl")]
		public decimal MeasurementUnitZl
		{
			get{ return _MeasurementUnitZl; }
			set
			{
				this.OnPropertyValueChange("MeasurementUnitZl");
				this._MeasurementUnitZl = value;
			}
		}
		/// <summary>
		/// 单位用量
		/// </summary>
		[Field("ItemUseNum")]
		public decimal ItemUseNum
		{
			get{ return _ItemUseNum; }
			set
			{
				this.OnPropertyValueChange("ItemUseNum");
				this._ItemUseNum = value;
			}
		}
		/// <summary>
		/// 件数
		/// </summary>
		[Field("Number")]
		public int Number
		{
			get{ return _Number; }
			set
			{
				this.OnPropertyValueChange("Number");
				this._Number = value;
			}
		}
		/// <summary>
		/// 重量小计
		/// </summary>
		[Field("WeightSmallPlan")]
		public decimal WeightSmallPlan
		{
			get{ return _WeightSmallPlan; }
			set
			{
				this.OnPropertyValueChange("WeightSmallPlan");
				this._WeightSmallPlan = value;
			}
		}
		/// <summary>
		/// 使用材料类型
		/// </summary>
		[Field("RMTypeName")]
		public string RMTypeName
		{
			get{ return _RMTypeName; }
			set
			{
				this.OnPropertyValueChange("RMTypeName");
				this._RMTypeName = value;
			}
		}
		/// <summary>
		/// 尺寸选择
		/// </summary>
		[Field("SizeSelection")]
		public decimal SizeSelection
		{
			get{ return _SizeSelection; }
			set
			{
				this.OnPropertyValueChange("SizeSelection");
				this._SizeSelection = value;
			}
		}
		/// <summary>
		/// 根数
		/// </summary>
		[Field("RootNumber")]
		public int RootNumber
		{
			get{ return _RootNumber; }
			set
			{
				this.OnPropertyValueChange("RootNumber");
				this._RootNumber = value;
			}
		}
		/// <summary>
		/// 尺寸选择后的重量小计
		/// </summary>
		[Field("WeightSmallPlanN")]
		public decimal WeightSmallPlanN
		{
			get{ return _WeightSmallPlanN; }
			set
			{
				this.OnPropertyValueChange("WeightSmallPlanN");
				this._WeightSmallPlanN = value;
			}
		}
		/// <summary>
		/// 厂家
		/// </summary>
		[Field("Manufactor")]
		public string Manufactor
		{
			get{ return _Manufactor; }
			set
			{
				this.OnPropertyValueChange("Manufactor");
				this._Manufactor = value;
			}
		}
		/// <summary>
		/// 炉批号
		/// </summary>
		[Field("HeatNo")]
		public string HeatNo
		{
			get{ return _HeatNo; }
			set
			{
				this.OnPropertyValueChange("HeatNo");
				this._HeatNo = value;
			}
		}
		/// <summary>
		/// 检测报告编号
		/// </summary>
		[Field("TestReportNo")]
		public string TestReportNo
		{
			get{ return _TestReportNo; }
			set
			{
				this.OnPropertyValueChange("TestReportNo");
				this._TestReportNo = value;
			}
		}
		/// <summary>
		/// 原材料名称/编号
		/// </summary>
		[Field("MaterialName")]
		public string MaterialName
		{
			get{ return _MaterialName; }
			set
			{
				this.OnPropertyValueChange("MaterialName");
				this._MaterialName = value;
			}
		}
		/// <summary>
		/// 构件名称
		/// </summary>
		[Field("ComponentName")]
		public string ComponentName
		{
			get{ return _ComponentName; }
			set
			{
				this.OnPropertyValueChange("ComponentName");
				this._ComponentName = value;
			}
		}
		/// <summary>
		/// 订单编号
		/// </summary>
		[Field("OrderCode")]
		public string OrderCode
		{
			get{ return _OrderCode; }
			set
			{
				this.OnPropertyValueChange("OrderCode");
				this._OrderCode = value;
			}
		}
		/// <summary>
		/// 余料库存
		/// </summary>
		[Field("CloutStockID")]
		public string CloutStockID
		{
			get{ return _CloutStockID; }
			set
			{
				this.OnPropertyValueChange("CloutStockID");
				this._CloutStockID = value;
			}
		}
		/// <summary>
		/// 加工订单明细Id
		/// </summary>
		[Field("WorkOrderItemId")]
		public int? WorkOrderItemId
		{
			get{ return _WorkOrderItemId; }
			set
			{
				this.OnPropertyValueChange("WorkOrderItemId");
				this._WorkOrderItemId = value;
			}
		}
		/// <summary>
		/// 库存记录Id
		/// </summary>
		[Field("InOrderItemId")]
		public string InOrderItemId
		{
			get{ return _InOrderItemId; }
			set
			{
				this.OnPropertyValueChange("InOrderItemId");
				this._InOrderItemId = value;
			}
		}
		/// <summary>
		/// 领料件数
		/// </summary>
		[Field("NumberH")]
		public int? NumberH
		{
			get{ return _NumberH; }
			set
			{
				this.OnPropertyValueChange("NumberH");
				this._NumberH = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SizeSelectionStr")]
		public string SizeSelectionStr
		{
			get{ return _SizeSelectionStr; }
			set
			{
				this.OnPropertyValueChange("SizeSelectionStr");
				this._SizeSelectionStr = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("RootNumberStr")]
		public string RootNumberStr
		{
			get{ return _RootNumberStr; }
			set
			{
				this.OnPropertyValueChange("RootNumberStr");
				this._RootNumberStr = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.CollarCode,
				_.MaterialCode,
				_.SpecificationModel,
				_.MeasurementUnitZl,
				_.ItemUseNum,
				_.Number,
				_.WeightSmallPlan,
				_.RMTypeName,
				_.SizeSelection,
				_.RootNumber,
				_.WeightSmallPlanN,
				_.Manufactor,
				_.HeatNo,
				_.TestReportNo,
				_.MaterialName,
				_.ComponentName,
				_.OrderCode,
				_.CloutStockID,
				_.WorkOrderItemId,
				_.InOrderItemId,
				_.NumberH,
				_.SizeSelectionStr,
				_.RootNumberStr,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._CollarCode,
				this._MaterialCode,
				this._SpecificationModel,
				this._MeasurementUnitZl,
				this._ItemUseNum,
				this._Number,
				this._WeightSmallPlan,
				this._RMTypeName,
				this._SizeSelection,
				this._RootNumber,
				this._WeightSmallPlanN,
				this._Manufactor,
				this._HeatNo,
				this._TestReportNo,
				this._MaterialName,
				this._ComponentName,
				this._OrderCode,
				this._CloutStockID,
				this._WorkOrderItemId,
				this._InOrderItemId,
				this._NumberH,
				this._SizeSelectionStr,
				this._RootNumberStr,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbRMProductionMaterialDetail");
            /// <summary>
			/// 主键ID
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbRMProductionMaterialDetail", "主键ID");
            /// <summary>
			/// 领用单号
			/// </summary>
			public readonly static Field CollarCode = new Field("CollarCode", "TbRMProductionMaterialDetail", "领用单号");
            /// <summary>
			/// 原材料名称/编号
			/// </summary>
			public readonly static Field MaterialCode = new Field("MaterialCode", "TbRMProductionMaterialDetail", "原材料名称/编号");
            /// <summary>
			/// 规格型号
			/// </summary>
			public readonly static Field SpecificationModel = new Field("SpecificationModel", "TbRMProductionMaterialDetail", "规格型号");
            /// <summary>
			/// 单位重量
			/// </summary>
			public readonly static Field MeasurementUnitZl = new Field("MeasurementUnitZl", "TbRMProductionMaterialDetail", "单位重量");
            /// <summary>
			/// 单位用量
			/// </summary>
			public readonly static Field ItemUseNum = new Field("ItemUseNum", "TbRMProductionMaterialDetail", "单位用量");
            /// <summary>
			/// 件数
			/// </summary>
			public readonly static Field Number = new Field("Number", "TbRMProductionMaterialDetail", "件数");
            /// <summary>
			/// 重量小计
			/// </summary>
			public readonly static Field WeightSmallPlan = new Field("WeightSmallPlan", "TbRMProductionMaterialDetail", "重量小计");
            /// <summary>
			/// 使用材料类型
			/// </summary>
			public readonly static Field RMTypeName = new Field("RMTypeName", "TbRMProductionMaterialDetail", "使用材料类型");
            /// <summary>
			/// 尺寸选择
			/// </summary>
			public readonly static Field SizeSelection = new Field("SizeSelection", "TbRMProductionMaterialDetail", "尺寸选择");
            /// <summary>
			/// 根数
			/// </summary>
			public readonly static Field RootNumber = new Field("RootNumber", "TbRMProductionMaterialDetail", "根数");
            /// <summary>
			/// 尺寸选择后的重量小计
			/// </summary>
			public readonly static Field WeightSmallPlanN = new Field("WeightSmallPlanN", "TbRMProductionMaterialDetail", "尺寸选择后的重量小计");
            /// <summary>
			/// 厂家
			/// </summary>
			public readonly static Field Manufactor = new Field("Manufactor", "TbRMProductionMaterialDetail", "厂家");
            /// <summary>
			/// 炉批号
			/// </summary>
			public readonly static Field HeatNo = new Field("HeatNo", "TbRMProductionMaterialDetail", "炉批号");
            /// <summary>
			/// 检测报告编号
			/// </summary>
			public readonly static Field TestReportNo = new Field("TestReportNo", "TbRMProductionMaterialDetail", "检测报告编号");
            /// <summary>
			/// 原材料名称/编号
			/// </summary>
			public readonly static Field MaterialName = new Field("MaterialName", "TbRMProductionMaterialDetail", "原材料名称/编号");
            /// <summary>
			/// 构件名称
			/// </summary>
			public readonly static Field ComponentName = new Field("ComponentName", "TbRMProductionMaterialDetail", "构件名称");
            /// <summary>
			/// 订单编号
			/// </summary>
			public readonly static Field OrderCode = new Field("OrderCode", "TbRMProductionMaterialDetail", "订单编号");
            /// <summary>
			/// 余料库存
			/// </summary>
			public readonly static Field CloutStockID = new Field("CloutStockID", "TbRMProductionMaterialDetail", "余料库存");
            /// <summary>
			/// 加工订单明细Id
			/// </summary>
			public readonly static Field WorkOrderItemId = new Field("WorkOrderItemId", "TbRMProductionMaterialDetail", "加工订单明细Id");
            /// <summary>
			/// 库存记录Id
			/// </summary>
			public readonly static Field InOrderItemId = new Field("InOrderItemId", "TbRMProductionMaterialDetail", "库存记录Id");
            /// <summary>
			/// 领料件数
			/// </summary>
			public readonly static Field NumberH = new Field("NumberH", "TbRMProductionMaterialDetail", "领料件数");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field SizeSelectionStr = new Field("SizeSelectionStr", "TbRMProductionMaterialDetail", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field RootNumberStr = new Field("RootNumberStr", "TbRMProductionMaterialDetail", "");
        }
        #endregion
	}
}