//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 领料单锁定库存数量
    /// </summary>
    [Table("TbRMProductionMaterialLockCount")]
    [Serializable]
    public partial class TbRMProductionMaterialLockCount : Entity
    {
        #region Model
		private int _ID;
		private string _CollarCode;
		private int? _StockRecordId;
		private decimal? _LockCount;
        private int? _SourceType;
        private int? _WorkOrderItemId;

		/// <summary>
		/// ID
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 领料单编号
		/// </summary>
		[Field("CollarCode")]
		public string CollarCode
		{
			get{ return _CollarCode; }
			set
			{
				this.OnPropertyValueChange("CollarCode");
				this._CollarCode = value;
			}
		}
		/// <summary>
		/// 库存记录Id
		/// </summary>
		[Field("StockRecordId")]
		public int? StockRecordId
		{
			get{ return _StockRecordId; }
			set
			{
				this.OnPropertyValueChange("StockRecordId");
				this._StockRecordId = value;
			}
		}
		/// <summary>
		/// 锁定数量
		/// </summary>
		[Field("LockCount")]
		public decimal? LockCount
		{
			get{ return _LockCount; }
			set
			{
				this.OnPropertyValueChange("LockCount");
				this._LockCount = value;
			}
		}
		/// <summary>
		/// 来源：1原材料，2余料
		/// </summary>
		[Field("SourceType")]
		public int? SourceType
		{
			get{ return _SourceType; }
			set
			{
				this.OnPropertyValueChange("SourceType");
				this._SourceType = value;
			}
		}
        /// <summary>
        /// 
        /// </summary>
        [Field("WorkOrderItemId")]
        public int? WorkOrderItemId
        {
            get { return _WorkOrderItemId; }
            set
            {
                this.OnPropertyValueChange("WorkOrderItemId");
                this._WorkOrderItemId = value;
            }
        }
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.CollarCode,
				_.StockRecordId,
				_.LockCount,
				_.SourceType, 
				_.WorkOrderItemId,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._CollarCode,
				this._StockRecordId,
				this._LockCount,
				this._SourceType,  
				this.WorkOrderItemId,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbRMProductionMaterialLockCount");
            /// <summary>
			/// ID
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbRMProductionMaterialLockCount", "ID");
            /// <summary>
			/// 领料单编号
			/// </summary>
			public readonly static Field CollarCode = new Field("CollarCode", "TbRMProductionMaterialLockCount", "领料单编号");
            /// <summary>
			/// 库存记录Id
			/// </summary>
			public readonly static Field StockRecordId = new Field("StockRecordId", "TbRMProductionMaterialLockCount", "库存记录Id");
            /// <summary>
			/// 锁定数量
			/// </summary>
			public readonly static Field LockCount = new Field("LockCount", "TbRMProductionMaterialLockCount", "锁定数量");
            /// <summary>
			/// 来源：1原材料，2余料
			/// </summary>
            public readonly static Field SourceType = new Field("SourceType", "TbRMProductionMaterialLockCount", "来源：1原材料，2余料");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field WorkOrderItemId = new Field("WorkOrderItemId", "TbRMProductionMaterialPlan", "");
        }
        #endregion
	}
}