//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 废料库存
    /// </summary>
    [Table("TbRubbishStock")]
    [Serializable]
    public partial class TbRubbishStock : Entity
    {
        #region Model
		private int _ID;
		private string _ProjectId;
		private string _SiteCode;
		private string _MaterialCode;
		private decimal? _Size;
		private int? _Number;
		private decimal? _WeightNot;
		private decimal? _WeightYes;
		private DateTime? _HandTime;
		private int? _State;
		private string _CollarCode;
		private string _Factory;
		private string _BatchNumber;

		/// <summary>
		/// ID
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 项目ID
		/// </summary>
		[Field("ProjectId")]
		public string ProjectId
		{
			get{ return _ProjectId; }
			set
			{
				this.OnPropertyValueChange("ProjectId");
				this._ProjectId = value;
			}
		}
		/// <summary>
		/// 站点编号
		/// </summary>
		[Field("SiteCode")]
		public string SiteCode
		{
			get{ return _SiteCode; }
			set
			{
				this.OnPropertyValueChange("SiteCode");
				this._SiteCode = value;
			}
		}
		/// <summary>
		/// 原材料编号
		/// </summary>
		[Field("MaterialCode")]
		public string MaterialCode
		{
			get{ return _MaterialCode; }
			set
			{
				this.OnPropertyValueChange("MaterialCode");
				this._MaterialCode = value;
			}
		}
		/// <summary>
		/// 尺寸（m）
		/// </summary>
		[Field("Size")]
		public decimal? Size
		{
			get{ return _Size; }
			set
			{
				this.OnPropertyValueChange("Size");
				this._Size = value;
			}
		}
		/// <summary>
		/// 数量
		/// </summary>
		[Field("Number")]
		public int? Number
		{
			get{ return _Number; }
			set
			{
				this.OnPropertyValueChange("Number");
				this._Number = value;
			}
		}
		/// <summary>
		/// 未处理重量
		/// </summary>
		[Field("WeightNot")]
		public decimal? WeightNot
		{
			get{ return _WeightNot; }
			set
			{
				this.OnPropertyValueChange("WeightNot");
				this._WeightNot = value;
			}
		}
		/// <summary>
		/// 已处理重量
		/// </summary>
		[Field("WeightYes")]
		public decimal? WeightYes
		{
			get{ return _WeightYes; }
			set
			{
				this.OnPropertyValueChange("WeightYes");
				this._WeightYes = value;
			}
		}
		/// <summary>
		/// 处理时间
		/// </summary>
		[Field("HandTime")]
		public DateTime? HandTime
		{
			get{ return _HandTime; }
			set
			{
				this.OnPropertyValueChange("HandTime");
				this._HandTime = value;
			}
		}
		/// <summary>
		/// _0未处理 1已处理
		/// </summary>
		[Field("State")]
		public int? State
		{
			get{ return _State; }
			set
			{
				this.OnPropertyValueChange("State");
				this._State = value;
			}
		}
		/// <summary>
		/// 领料单编号
		/// </summary>
		[Field("CollarCode")]
		public string CollarCode
		{
			get{ return _CollarCode; }
			set
			{
				this.OnPropertyValueChange("CollarCode");
				this._CollarCode = value;
			}
		}
		/// <summary>
		/// 厂家
		/// </summary>
		[Field("Factory")]
		public string Factory
		{
			get{ return _Factory; }
			set
			{
				this.OnPropertyValueChange("Factory");
				this._Factory = value;
			}
		}
		/// <summary>
		/// 炉批号
		/// </summary>
		[Field("BatchNumber")]
		public string BatchNumber
		{
			get{ return _BatchNumber; }
			set
			{
				this.OnPropertyValueChange("BatchNumber");
				this._BatchNumber = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.ProjectId,
				_.SiteCode,
				_.MaterialCode,
				_.Size,
				_.Number,
				_.WeightNot,
				_.WeightYes,
				_.HandTime,
				_.State,
				_.CollarCode,
				_.Factory,
				_.BatchNumber,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._ProjectId,
				this._SiteCode,
				this._MaterialCode,
				this._Size,
				this._Number,
				this._WeightNot,
				this._WeightYes,
				this._HandTime,
				this._State,
				this._CollarCode,
				this._Factory,
				this._BatchNumber,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbRubbishStock");
            /// <summary>
			/// ID
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbRubbishStock", "ID");
            /// <summary>
			/// 项目ID
			/// </summary>
			public readonly static Field ProjectId = new Field("ProjectId", "TbRubbishStock", "项目ID");
            /// <summary>
			/// 站点编号
			/// </summary>
			public readonly static Field SiteCode = new Field("SiteCode", "TbRubbishStock", "站点编号");
            /// <summary>
			/// 原材料编号
			/// </summary>
			public readonly static Field MaterialCode = new Field("MaterialCode", "TbRubbishStock", "原材料编号");
            /// <summary>
			/// 尺寸（m）
			/// </summary>
			public readonly static Field Size = new Field("Size", "TbRubbishStock", "尺寸（m）");
            /// <summary>
			/// 数量
			/// </summary>
			public readonly static Field Number = new Field("Number", "TbRubbishStock", "数量");
            /// <summary>
			/// 未处理重量
			/// </summary>
			public readonly static Field WeightNot = new Field("WeightNot", "TbRubbishStock", "未处理重量");
            /// <summary>
			/// 已处理重量
			/// </summary>
			public readonly static Field WeightYes = new Field("WeightYes", "TbRubbishStock", "已处理重量");
            /// <summary>
			/// 处理时间
			/// </summary>
			public readonly static Field HandTime = new Field("HandTime", "TbRubbishStock", "处理时间");
            /// <summary>
			/// _0未处理 1已处理
			/// </summary>
			public readonly static Field State = new Field("State", "TbRubbishStock", "_0未处理 1已处理");
            /// <summary>
			/// 领料单编号
			/// </summary>
			public readonly static Field CollarCode = new Field("CollarCode", "TbRubbishStock", "领料单编号");
            /// <summary>
			/// 厂家
			/// </summary>
			public readonly static Field Factory = new Field("Factory", "TbRubbishStock", "厂家");
            /// <summary>
			/// 炉批号
			/// </summary>
			public readonly static Field BatchNumber = new Field("BatchNumber", "TbRubbishStock", "炉批号");
        }
        #endregion
	}
}