//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36460
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 仓库管理
    /// </summary>
    [Table("TbStorage")]
    [Serializable]
    public partial class TbStorage : Entity
    {
        #region Model
		private int _ID;
		private string _StorageCode;
		private string _StorageName;
		private string _ProcessFactoryCode;
		private string _StorageAdd;
		private string _AreaCode;
		private string _UserCode;
		private string _Tel;
		private string _InsertUserCode;
		private DateTime _InsertTime;
		private string _Remark;
		private string _StorageAttribute;

		/// <summary>
		/// ID
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 仓库编号
		/// </summary>
		[Field("StorageCode")]
		public string StorageCode
		{
			get{ return _StorageCode; }
			set
			{
				this.OnPropertyValueChange("StorageCode");
				this._StorageCode = value;
			}
		}
		/// <summary>
		/// 仓库名称
		/// </summary>
		[Field("StorageName")]
		public string StorageName
		{
			get{ return _StorageName; }
			set
			{
				this.OnPropertyValueChange("StorageName");
				this._StorageName = value;
			}
		}
		/// <summary>
		/// 仓库归属
		/// </summary>
		[Field("ProcessFactoryCode")]
		public string ProcessFactoryCode
		{
			get{ return _ProcessFactoryCode; }
			set
			{
				this.OnPropertyValueChange("ProcessFactoryCode");
				this._ProcessFactoryCode = value;
			}
		}
		/// <summary>
		/// 仓库地址
		/// </summary>
		[Field("StorageAdd")]
		public string StorageAdd
		{
			get{ return _StorageAdd; }
			set
			{
				this.OnPropertyValueChange("StorageAdd");
				this._StorageAdd = value;
			}
		}
		/// <summary>
		/// 仓库区域
		/// </summary>
		[Field("AreaCode")]
		public string AreaCode
		{
			get{ return _AreaCode; }
			set
			{
				this.OnPropertyValueChange("AreaCode");
				this._AreaCode = value;
			}
		}
		/// <summary>
		/// 管理员编号
		/// </summary>
		[Field("UserCode")]
		public string UserCode
		{
			get{ return _UserCode; }
			set
			{
				this.OnPropertyValueChange("UserCode");
				this._UserCode = value;
			}
		}
		/// <summary>
		/// 联系方式
		/// </summary>
		[Field("Tel")]
		public string Tel
		{
			get{ return _Tel; }
			set
			{
				this.OnPropertyValueChange("Tel");
				this._Tel = value;
			}
		}
		/// <summary>
		/// 录入人编号
		/// </summary>
		[Field("InsertUserCode")]
		public string InsertUserCode
		{
			get{ return _InsertUserCode; }
			set
			{
				this.OnPropertyValueChange("InsertUserCode");
				this._InsertUserCode = value;
			}
		}
		/// <summary>
		/// 录入时间
		/// </summary>
		[Field("InsertTime")]
		public DateTime InsertTime
		{
			get{ return _InsertTime; }
			set
			{
				this.OnPropertyValueChange("InsertTime");
				this._InsertTime = value;
			}
		}
		/// <summary>
		/// 备注
		/// </summary>
		[Field("Remark")]
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange("Remark");
				this._Remark = value;
			}
		}
		/// <summary>
		/// 仓库属性
		/// </summary>
		[Field("StorageAttribute")]
		public string StorageAttribute
		{
			get{ return _StorageAttribute; }
			set
			{
				this.OnPropertyValueChange("StorageAttribute");
				this._StorageAttribute = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.StorageCode,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.StorageCode,
				_.StorageName,
				_.ProcessFactoryCode,
				_.StorageAdd,
				_.AreaCode,
				_.UserCode,
				_.Tel,
				_.InsertUserCode,
				_.InsertTime,
				_.Remark,
				_.StorageAttribute,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._StorageCode,
				this._StorageName,
				this._ProcessFactoryCode,
				this._StorageAdd,
				this._AreaCode,
				this._UserCode,
				this._Tel,
				this._InsertUserCode,
				this._InsertTime,
				this._Remark,
				this._StorageAttribute,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbStorage");
            /// <summary>
			/// ID
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbStorage", "ID");
            /// <summary>
			/// 仓库编号
			/// </summary>
			public readonly static Field StorageCode = new Field("StorageCode", "TbStorage", "仓库编号");
            /// <summary>
			/// 仓库名称
			/// </summary>
			public readonly static Field StorageName = new Field("StorageName", "TbStorage", "仓库名称");
            /// <summary>
			/// 仓库归属
			/// </summary>
			public readonly static Field ProcessFactoryCode = new Field("ProcessFactoryCode", "TbStorage", "仓库归属");
            /// <summary>
			/// 仓库地址
			/// </summary>
			public readonly static Field StorageAdd = new Field("StorageAdd", "TbStorage", "仓库地址");
            /// <summary>
			/// 仓库区域
			/// </summary>
			public readonly static Field AreaCode = new Field("AreaCode", "TbStorage", "仓库区域");
            /// <summary>
			/// 管理员编号
			/// </summary>
			public readonly static Field UserCode = new Field("UserCode", "TbStorage", "管理员编号");
            /// <summary>
			/// 联系方式
			/// </summary>
			public readonly static Field Tel = new Field("Tel", "TbStorage", "联系方式");
            /// <summary>
			/// 录入人编号
			/// </summary>
			public readonly static Field InsertUserCode = new Field("InsertUserCode", "TbStorage", "录入人编号");
            /// <summary>
			/// 录入时间
			/// </summary>
			public readonly static Field InsertTime = new Field("InsertTime", "TbStorage", "录入时间");
            /// <summary>
			/// 备注
			/// </summary>
			public readonly static Field Remark = new Field("Remark", "TbStorage", "备注");
            /// <summary>
			/// 仓库属性
			/// </summary>
			public readonly static Field StorageAttribute = new Field("StorageAttribute", "TbStorage", "仓库属性");
        }
        #endregion

        #region 扩展字段
        public string UserName { get; set; }
        #endregion
    }
}