//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 库存盘点明细
    /// </summary>
    [Table("TbStockTakingItem")]
    [Serializable]
    public partial class TbStockTakingItem : Entity
    {
        #region Model
        private int _ID;
        private int _EarnOrLosItem;
		private string _TakNum;
		private string _MaterialCode;
		private string _MaterialName;
		private string _SpecificationModel;
		private string _RebarType;
		private decimal? _lnventoryWeight;
		private decimal? _TakWeight;
		private decimal? _EarnOrLosWeight;
		private string _Remark;

		/// <summary>
		/// id
		/// </summary>
		[Field("ID")]
		public int ID
        {
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
        /// <summary>
        /// 盘盈/盘亏 0盘盈 1盘亏
        /// </summary>
        [Field("EarnOrLosItem")]
        public int EarnOrLosItem
        {
            get { return _EarnOrLosItem; }
            set
            {
                this.OnPropertyValueChange("EarnOrLosItem");
                this._EarnOrLosItem = value;
            }
        }
		/// <summary>
		/// 盘点单号
		/// </summary>
		[Field("TakNum")]
		public string TakNum
		{
			get{ return _TakNum; }
			set
			{
				this.OnPropertyValueChange("TakNum");
				this._TakNum = value;
			}
		}
		/// <summary>
		/// 原材料编号
		/// </summary>
		[Field("MaterialCode")]
		public string MaterialCode
		{
			get{ return _MaterialCode; }
			set
			{
				this.OnPropertyValueChange("MaterialCode");
				this._MaterialCode = value;
			}
		}
		/// <summary>
		/// 原材料名称
		/// </summary>
		[Field("MaterialName")]
		public string MaterialName
		{
			get{ return _MaterialName; }
			set
			{
				this.OnPropertyValueChange("MaterialName");
				this._MaterialName = value;
			}
		}
		/// <summary>
		/// 规格型号
		/// </summary>
		[Field("SpecificationModel")]
		public string SpecificationModel
		{
			get{ return _SpecificationModel; }
			set
			{
				this.OnPropertyValueChange("SpecificationModel");
				this._SpecificationModel = value;
			}
		}
		/// <summary>
		/// 钢筋类型
		/// </summary>
		[Field("RebarType")]
		public string RebarType
		{
			get{ return _RebarType; }
			set
			{
				this.OnPropertyValueChange("RebarType");
				this._RebarType = value;
			}
		}
		/// <summary>
		/// 库存重量
		/// </summary>
		[Field("lnventoryWeight")]
		public decimal? lnventoryWeight
		{
			get{ return _lnventoryWeight; }
			set
			{
				this.OnPropertyValueChange("lnventoryWeight");
				this._lnventoryWeight = value;
			}
		}
		/// <summary>
		/// 盘点重量
		/// </summary>
		[Field("TakWeight")]
		public decimal? TakWeight
		{
			get{ return _TakWeight; }
			set
			{
				this.OnPropertyValueChange("TakWeight");
				this._TakWeight = value;
			}
		}
		/// <summary>
		/// 盘赢盘亏
		/// </summary>
		[Field("EarnOrLosWeight")]
		public decimal? EarnOrLosWeight
		{
			get{ return _EarnOrLosWeight; }
			set
			{
				this.OnPropertyValueChange("EarnOrLosWeight");
				this._EarnOrLosWeight = value;
			}
		}
		/// <summary>
		/// 备注
		/// </summary>
		[Field("Remark")]
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange("Remark");
				this._Remark = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.EarnOrLosItem,  
				_.TakNum,
				_.MaterialCode,
				_.MaterialName,
				_.SpecificationModel,
				_.RebarType,
				_.lnventoryWeight,
				_.TakWeight,
				_.EarnOrLosWeight,
				_.Remark,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._EarnOrLosItem,  
				this._TakNum,
				this._MaterialCode,
				this._MaterialName,
				this._SpecificationModel,
				this._RebarType,
				this._lnventoryWeight,
				this._TakWeight,
				this._EarnOrLosWeight,
				this._Remark,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbStockTakingItem");
            /// <summary>
            /// 盘盈/盘亏 0盘盈 1盘亏
			/// </summary>
            public readonly static Field EarnOrLosItem = new Field("EarnOrLosItem", "TbStockTakingItem", "EarnOrLosItem");
            /// id
            /// </summary>
            public readonly static Field ID = new Field("ID", "TbStockTakingItem", "ID");
            /// <summary>
			/// 盘点单号
			/// </summary>
			public readonly static Field TakNum = new Field("TakNum", "TbStockTakingItem", "盘点单号");
            /// <summary>
			/// 原材料编号
			/// </summary>
			public readonly static Field MaterialCode = new Field("MaterialCode", "TbStockTakingItem", "原材料编号");
            /// <summary>
			/// 原材料名称
			/// </summary>
			public readonly static Field MaterialName = new Field("MaterialName", "TbStockTakingItem", "原材料名称");
            /// <summary>
			/// 规格型号
			/// </summary>
			public readonly static Field SpecificationModel = new Field("SpecificationModel", "TbStockTakingItem", "规格型号");
            /// <summary>
			/// 钢筋类型
			/// </summary>
			public readonly static Field RebarType = new Field("RebarType", "TbStockTakingItem", "钢筋类型");
            /// <summary>
			/// 库存重量
			/// </summary>
			public readonly static Field lnventoryWeight = new Field("lnventoryWeight", "TbStockTakingItem", "库存重量");
            /// <summary>
			/// 盘点重量
			/// </summary>
			public readonly static Field TakWeight = new Field("TakWeight", "TbStockTakingItem", "盘点重量");
            /// <summary>
			/// 盘赢盘亏
			/// </summary>
			public readonly static Field EarnOrLosWeight = new Field("EarnOrLosWeight", "TbStockTakingItem", "盘赢盘亏");
            /// <summary>
			/// 备注
			/// </summary>
			public readonly static Field Remark = new Field("Remark", "TbStockTakingItem", "备注");
        }
        #endregion
	}
}