//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36460
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 实体类TbFlowEarlyWarningInfo。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("TbFlowEarlyWarningInfo")]
    [Serializable]
    public partial class TbFlowEarlyWarningInfo : Entity
    {
        #region Model
		private int _ID;
		private string _EarlyWarningCode;
		private string _FlowCode;
		private string _FlowNodeCode;
		private string _FlowPerformID;
		private string _EarlyWarningContent;
		private int? _EarlyWarningStart;
		private string _EarlyWarningBTUser;
		private int? _EWFormDataCode;
		private string _EWFormCode;
		private DateTime? _EarlyWarningTime;
		private string _ProjectId;
		private string _SpYjType;
		private string _EarlyWarningOrder;
		private string _DataCode;

		/// <summary>
		/// ID
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 预警条件编号
		/// </summary>
		[Field("EarlyWarningCode")]
		public string EarlyWarningCode
		{
			get{ return _EarlyWarningCode; }
			set
			{
				this.OnPropertyValueChange("EarlyWarningCode");
				this._EarlyWarningCode = value;
			}
		}
		/// <summary>
		/// 流程编号
		/// </summary>
		[Field("FlowCode")]
		public string FlowCode
		{
			get{ return _FlowCode; }
			set
			{
				this.OnPropertyValueChange("FlowCode");
				this._FlowCode = value;
			}
		}
		/// <summary>
		/// 流程节点编号
		/// </summary>
		[Field("FlowNodeCode")]
		public string FlowNodeCode
		{
			get{ return _FlowNodeCode; }
			set
			{
				this.OnPropertyValueChange("FlowNodeCode");
				this._FlowNodeCode = value;
			}
		}
		/// <summary>
		/// 审批流程编号
		/// </summary>
		[Field("FlowPerformID")]
		public string FlowPerformID
		{
			get{ return _FlowPerformID; }
			set
			{
				this.OnPropertyValueChange("FlowPerformID");
				this._FlowPerformID = value;
			}
		}
		/// <summary>
		/// 预警内容
		/// </summary>
		[Field("EarlyWarningContent")]
		public string EarlyWarningContent
		{
			get{ return _EarlyWarningContent; }
			set
			{
				this.OnPropertyValueChange("EarlyWarningContent");
				this._EarlyWarningContent = value;
			}
		}
		/// <summary>
		/// 预警状态
		/// </summary>
		[Field("EarlyWarningStart")]
		public int? EarlyWarningStart
		{
			get{ return _EarlyWarningStart; }
			set
			{
				this.OnPropertyValueChange("EarlyWarningStart");
				this._EarlyWarningStart = value;
			}
		}
		/// <summary>
		/// 预警属于人员
		/// </summary>
		[Field("EarlyWarningBTUser")]
		public string EarlyWarningBTUser
		{
			get{ return _EarlyWarningBTUser; }
			set
			{
				this.OnPropertyValueChange("EarlyWarningBTUser");
				this._EarlyWarningBTUser = value;
			}
		}
		/// <summary>
		/// 预警数据id
		/// </summary>
		[Field("EWFormDataCode")]
		public int? EWFormDataCode
		{
			get{ return _EWFormDataCode; }
			set
			{
				this.OnPropertyValueChange("EWFormDataCode");
				this._EWFormDataCode = value;
			}
		}
		/// <summary>
		/// 预警表单
		/// </summary>
		[Field("EWFormCode")]
		public string EWFormCode
		{
			get{ return _EWFormCode; }
			set
			{
				this.OnPropertyValueChange("EWFormCode");
				this._EWFormCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("EarlyWarningTime")]
		public DateTime? EarlyWarningTime
		{
			get{ return _EarlyWarningTime; }
			set
			{
				this.OnPropertyValueChange("EarlyWarningTime");
				this._EarlyWarningTime = value;
			}
		}
		/// <summary>
		/// 项目id
		/// </summary>
		[Field("ProjectId")]
		public string ProjectId
		{
			get{ return _ProjectId; }
			set
			{
				this.OnPropertyValueChange("ProjectId");
				this._ProjectId = value;
			}
		}
		/// <summary>
		/// 审批预警类型
		/// </summary>
		[Field("SpYjType")]
		public string SpYjType
		{
			get{ return _SpYjType; }
			set
			{
				this.OnPropertyValueChange("SpYjType");
				this._SpYjType = value;
			}
		}
		/// <summary>
		/// 审批预警顺序
		/// </summary>
		[Field("EarlyWarningOrder")]
		public string EarlyWarningOrder
		{
			get{ return _EarlyWarningOrder; }
			set
			{
				this.OnPropertyValueChange("EarlyWarningOrder");
				this._EarlyWarningOrder = value;
			}
		}
		/// <summary>
		/// 预警数据编号
		/// </summary>
		[Field("DataCode")]
		public string DataCode
		{
			get{ return _DataCode; }
			set
			{
				this.OnPropertyValueChange("DataCode");
				this._DataCode = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.EarlyWarningCode,
				_.FlowCode,
				_.FlowNodeCode,
				_.FlowPerformID,
				_.EarlyWarningContent,
				_.EarlyWarningStart,
				_.EarlyWarningBTUser,
				_.EWFormDataCode,
				_.EWFormCode,
				_.EarlyWarningTime,
				_.ProjectId,
				_.SpYjType,
				_.EarlyWarningOrder,
				_.DataCode,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._EarlyWarningCode,
				this._FlowCode,
				this._FlowNodeCode,
				this._FlowPerformID,
				this._EarlyWarningContent,
				this._EarlyWarningStart,
				this._EarlyWarningBTUser,
				this._EWFormDataCode,
				this._EWFormCode,
				this._EarlyWarningTime,
				this._ProjectId,
				this._SpYjType,
				this._EarlyWarningOrder,
				this._DataCode,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbFlowEarlyWarningInfo");
            /// <summary>
			/// ID
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbFlowEarlyWarningInfo", "ID");
            /// <summary>
			/// 预警条件编号
			/// </summary>
			public readonly static Field EarlyWarningCode = new Field("EarlyWarningCode", "TbFlowEarlyWarningInfo", "预警条件编号");
            /// <summary>
			/// 流程编号
			/// </summary>
			public readonly static Field FlowCode = new Field("FlowCode", "TbFlowEarlyWarningInfo", "流程编号");
            /// <summary>
			/// 流程节点编号
			/// </summary>
			public readonly static Field FlowNodeCode = new Field("FlowNodeCode", "TbFlowEarlyWarningInfo", "流程节点编号");
            /// <summary>
			/// 审批流程编号
			/// </summary>
			public readonly static Field FlowPerformID = new Field("FlowPerformID", "TbFlowEarlyWarningInfo", "审批流程编号");
            /// <summary>
			/// 预警内容
			/// </summary>
			public readonly static Field EarlyWarningContent = new Field("EarlyWarningContent", "TbFlowEarlyWarningInfo", "预警内容");
            /// <summary>
			/// 预警状态
			/// </summary>
			public readonly static Field EarlyWarningStart = new Field("EarlyWarningStart", "TbFlowEarlyWarningInfo", "预警状态");
            /// <summary>
			/// 预警属于人员
			/// </summary>
			public readonly static Field EarlyWarningBTUser = new Field("EarlyWarningBTUser", "TbFlowEarlyWarningInfo", "预警属于人员");
            /// <summary>
			/// 预警数据id
			/// </summary>
			public readonly static Field EWFormDataCode = new Field("EWFormDataCode", "TbFlowEarlyWarningInfo", "预警数据id");
            /// <summary>
			/// 预警表单
			/// </summary>
			public readonly static Field EWFormCode = new Field("EWFormCode", "TbFlowEarlyWarningInfo", "预警表单");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field EarlyWarningTime = new Field("EarlyWarningTime", "TbFlowEarlyWarningInfo", "");
            /// <summary>
			/// 项目id
			/// </summary>
			public readonly static Field ProjectId = new Field("ProjectId", "TbFlowEarlyWarningInfo", "项目id");
            /// <summary>
			/// 审批预警类型
			/// </summary>
			public readonly static Field SpYjType = new Field("SpYjType", "TbFlowEarlyWarningInfo", "审批预警类型");
            /// <summary>
			/// 审批预警顺序
			/// </summary>
			public readonly static Field EarlyWarningOrder = new Field("EarlyWarningOrder", "TbFlowEarlyWarningInfo", "审批预警顺序");
            /// <summary>
			/// 预警数据编号
			/// </summary>
			public readonly static Field DataCode = new Field("DataCode", "TbFlowEarlyWarningInfo", "预警数据编号");
        }
        #endregion
	}
}