//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 实体类TbFlowPerformNodePersonnel。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("TbFlowPerformNodePersonnel")]
    [Serializable]
    public partial class TbFlowPerformNodePersonnel : Entity
    {
        #region Model
		private int _id;
		private string _FlowPerformID;
		private string _FlowCode;
		private string _FlowNodeCode;
		private int _ActionType;
		private string _PersonnelSource;
		private string _PersonnelCode;

		/// <summary>
		/// 
		/// </summary>
		[Field("id")]
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange("id");
				this._id = value;
			}
		}
		/// <summary>
		/// 流程执行流水号
		/// </summary>
		[Field("FlowPerformID")]
		public string FlowPerformID
		{
			get{ return _FlowPerformID; }
			set
			{
				this.OnPropertyValueChange("FlowPerformID");
				this._FlowPerformID = value;
			}
		}
		/// <summary>
		/// 流程代码
		/// </summary>
		[Field("FlowCode")]
		public string FlowCode
		{
			get{ return _FlowCode; }
			set
			{
				this.OnPropertyValueChange("FlowCode");
				this._FlowCode = value;
			}
		}
		/// <summary>
		/// 流程节点代码
		/// </summary>
		[Field("FlowNodeCode")]
		public string FlowNodeCode
		{
			get{ return _FlowNodeCode; }
			set
			{
				this.OnPropertyValueChange("FlowNodeCode");
				this._FlowNodeCode = value;
			}
		}
		/// <summary>
		/// 动作类型(0执行人1抄送人)
		/// </summary>
		[Field("ActionType")]
		public int ActionType
		{
			get{ return _ActionType; }
			set
			{
				this.OnPropertyValueChange("ActionType");
				this._ActionType = value;
			}
		}
		/// <summary>
		/// 人员来源(部门/角色/操作员/部门领导等)
		/// </summary>
		[Field("PersonnelSource")]
		public string PersonnelSource
		{
			get{ return _PersonnelSource; }
			set
			{
				this.OnPropertyValueChange("PersonnelSource");
				this._PersonnelSource = value;
			}
		}
		/// <summary>
		/// 人员代码
		/// </summary>
		[Field("PersonnelCode")]
		public string PersonnelCode
		{
			get{ return _PersonnelCode; }
			set
			{
				this.OnPropertyValueChange("PersonnelCode");
				this._PersonnelCode = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.FlowPerformID,
				_.FlowCode,
				_.FlowNodeCode,
				_.ActionType,
				_.PersonnelSource,
				_.PersonnelCode,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.id,
				_.FlowPerformID,
				_.FlowCode,
				_.FlowNodeCode,
				_.ActionType,
				_.PersonnelSource,
				_.PersonnelCode,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._id,
				this._FlowPerformID,
				this._FlowCode,
				this._FlowNodeCode,
				this._ActionType,
				this._PersonnelSource,
				this._PersonnelCode,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbFlowPerformNodePersonnel");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id", "TbFlowPerformNodePersonnel", "");
            /// <summary>
			/// 流程执行流水号
			/// </summary>
			public readonly static Field FlowPerformID = new Field("FlowPerformID", "TbFlowPerformNodePersonnel", "流程执行流水号");
            /// <summary>
			/// 流程代码
			/// </summary>
			public readonly static Field FlowCode = new Field("FlowCode", "TbFlowPerformNodePersonnel", "流程代码");
            /// <summary>
			/// 流程节点代码
			/// </summary>
			public readonly static Field FlowNodeCode = new Field("FlowNodeCode", "TbFlowPerformNodePersonnel", "流程节点代码");
            /// <summary>
			/// 动作类型(0执行人1抄送人)
			/// </summary>
			public readonly static Field ActionType = new Field("ActionType", "TbFlowPerformNodePersonnel", "动作类型(0执行人1抄送人)");
            /// <summary>
			/// 人员来源(部门/角色/操作员/部门领导等)
			/// </summary>
			public readonly static Field PersonnelSource = new Field("PersonnelSource", "TbFlowPerformNodePersonnel", "人员来源(部门/角色/操作员/部门领导等)");
            /// <summary>
			/// 人员代码
			/// </summary>
			public readonly static Field PersonnelCode = new Field("PersonnelCode", "TbFlowPerformNodePersonnel", "人员代码");
        }
        #endregion
	}
}