//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 实体类TbFlowPerform。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("TbFlowPerform")]
    [Serializable]
    public partial class TbFlowPerform : Entity
    {
        #region Model
		private int _id;
		private string _FlowPerformID;
		private string _UserCode;
		private string _FlowCode;
		private string _FormCode;
		private string _FormDataCode;
		private DateTime _BeginTime;
		private DateTime? _EndTime;
		private int _FlowState;
		private int _FlowLevel;
		private string _FlowTitle;
		private DateTime? _FinalCutoffTime;

		/// <summary>
		/// 
		/// </summary>
		[Field("id")]
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange("id");
				this._id = value;
			}
		}
		/// <summary>
		/// 流程执行流水号
		/// </summary>
		[Field("FlowPerformID")]
		public string FlowPerformID
		{
			get{ return _FlowPerformID; }
			set
			{
				this.OnPropertyValueChange("FlowPerformID");
				this._FlowPerformID = value;
			}
		}
		/// <summary>
		/// 用户代码(发起人)
		/// </summary>
		[Field("UserCode")]
		public string UserCode
		{
			get{ return _UserCode; }
			set
			{
				this.OnPropertyValueChange("UserCode");
				this._UserCode = value;
			}
		}
		/// <summary>
		/// 流程代码
		/// </summary>
		[Field("FlowCode")]
		public string FlowCode
		{
			get{ return _FlowCode; }
			set
			{
				this.OnPropertyValueChange("FlowCode");
				this._FlowCode = value;
			}
		}
		/// <summary>
		/// 表单代码
		/// </summary>
		[Field("FormCode")]
		public string FormCode
		{
			get{ return _FormCode; }
			set
			{
				this.OnPropertyValueChange("FormCode");
				this._FormCode = value;
			}
		}
		/// <summary>
		/// 单据号(表单数据代码)
		/// </summary>
		[Field("FormDataCode")]
		public string FormDataCode
		{
			get{ return _FormDataCode; }
			set
			{
				this.OnPropertyValueChange("FormDataCode");
				this._FormDataCode = value;
			}
		}
		/// <summary>
		/// 发起时间
		/// </summary>
		[Field("BeginTime")]
		public DateTime BeginTime
		{
			get{ return _BeginTime; }
			set
			{
				this.OnPropertyValueChange("BeginTime");
				this._BeginTime = value;
			}
		}
		/// <summary>
		/// 结束时间(执行中的流程结束时间为空)
		/// </summary>
		[Field("EndTime")]
		public DateTime? EndTime
		{
			get{ return _EndTime; }
			set
			{
				this.OnPropertyValueChange("EndTime");
				this._EndTime = value;
			}
		}
		/// <summary>
		/// 流程状态(-1未发出 0执行中1已撤消2已退回3已终止9已完成)
		/// </summary>
		[Field("FlowState")]
		public int FlowState
		{
			get{ return _FlowState; }
			set
			{
				this.OnPropertyValueChange("FlowState");
				this._FlowState = value;
			}
		}
		/// <summary>
		/// 级别0：普通；1加急；2：紧急
		/// </summary>
		[Field("FlowLevel")]
		public int FlowLevel
		{
			get{ return _FlowLevel; }
			set
			{
				this.OnPropertyValueChange("FlowLevel");
				this._FlowLevel = value;
			}
		}
		/// <summary>
		/// 主题
		/// </summary>
		[Field("FlowTitle")]
		public string FlowTitle
		{
			get{ return _FlowTitle; }
			set
			{
				this.OnPropertyValueChange("FlowTitle");
				this._FlowTitle = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FinalCutoffTime")]
		public DateTime? FinalCutoffTime
		{
			get{ return _FinalCutoffTime; }
			set
			{
				this.OnPropertyValueChange("FinalCutoffTime");
				this._FinalCutoffTime = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.FlowPerformID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.id,
				_.FlowPerformID,
				_.UserCode,
				_.FlowCode,
				_.FormCode,
				_.FormDataCode,
				_.BeginTime,
				_.EndTime,
				_.FlowState,
				_.FlowLevel,
				_.FlowTitle,
				_.FinalCutoffTime,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._id,
				this._FlowPerformID,
				this._UserCode,
				this._FlowCode,
				this._FormCode,
				this._FormDataCode,
				this._BeginTime,
				this._EndTime,
				this._FlowState,
				this._FlowLevel,
				this._FlowTitle,
				this._FinalCutoffTime,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbFlowPerform");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id", "TbFlowPerform", "");
            /// <summary>
			/// 流程执行流水号
			/// </summary>
			public readonly static Field FlowPerformID = new Field("FlowPerformID", "TbFlowPerform", "流程执行流水号");
            /// <summary>
			/// 用户代码(发起人)
			/// </summary>
			public readonly static Field UserCode = new Field("UserCode", "TbFlowPerform", "用户代码(发起人)");
            /// <summary>
			/// 流程代码
			/// </summary>
			public readonly static Field FlowCode = new Field("FlowCode", "TbFlowPerform", "流程代码");
            /// <summary>
			/// 表单代码
			/// </summary>
			public readonly static Field FormCode = new Field("FormCode", "TbFlowPerform", "表单代码");
            /// <summary>
			/// 单据号(表单数据代码)
			/// </summary>
			public readonly static Field FormDataCode = new Field("FormDataCode", "TbFlowPerform", "单据号(表单数据代码)");
            /// <summary>
			/// 发起时间
			/// </summary>
			public readonly static Field BeginTime = new Field("BeginTime", "TbFlowPerform", "发起时间");
            /// <summary>
			/// 结束时间(执行中的流程结束时间为空)
			/// </summary>
			public readonly static Field EndTime = new Field("EndTime", "TbFlowPerform", "结束时间(执行中的流程结束时间为空)");
            /// <summary>
			/// 流程状态(-1未发出 0执行中1已撤消2已退回3已终止9已完成)
			/// </summary>
			public readonly static Field FlowState = new Field("FlowState", "TbFlowPerform", "流程状态(-1未发出 0执行中1已撤消2已退回3已终止9已完成)");
            /// <summary>
			/// 级别0：普通；1加急；2：紧急
			/// </summary>
			public readonly static Field FlowLevel = new Field("FlowLevel", "TbFlowPerform", "级别0：普通；1加急；2：紧急");
            /// <summary>
			/// 主题
			/// </summary>
			public readonly static Field FlowTitle = new Field("FlowTitle", "TbFlowPerform", "主题");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field FinalCutoffTime = new Field("FinalCutoffTime", "TbFlowPerform", "");
        }
        #endregion
	}
}