//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 实体类TbFlowPerformNodeFormPart。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("TbFlowPerformNodeFormPart")]
    [Serializable]
    public partial class TbFlowPerformNodeFormPart : Entity
    {
        #region Model
		private int _id;
		private string _FlowPerformID;
		private string _FlowCode;
		private string _FlowNodeCode;
		private string _FormCode;
		private string _partSelector;
		private string _partSubmitFunction;
		private string _partName;

		/// <summary>
		/// 
		/// </summary>
		[Field("id")]
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange("id");
				this._id = value;
			}
		}
		/// <summary>
		/// 流程执行流水号
		/// </summary>
		[Field("FlowPerformID")]
		public string FlowPerformID
		{
			get{ return _FlowPerformID; }
			set
			{
				this.OnPropertyValueChange("FlowPerformID");
				this._FlowPerformID = value;
			}
		}
		/// <summary>
		/// 流程代码
		/// </summary>
		[Field("FlowCode")]
		public string FlowCode
		{
			get{ return _FlowCode; }
			set
			{
				this.OnPropertyValueChange("FlowCode");
				this._FlowCode = value;
			}
		}
		/// <summary>
		/// 流程节点代码
		/// </summary>
		[Field("FlowNodeCode")]
		public string FlowNodeCode
		{
			get{ return _FlowNodeCode; }
			set
			{
				this.OnPropertyValueChange("FlowNodeCode");
				this._FlowNodeCode = value;
			}
		}
		/// <summary>
		/// 表单代码(系统自动生成)
		/// </summary>
		[Field("FormCode")]
		public string FormCode
		{
			get{ return _FormCode; }
			set
			{
				this.OnPropertyValueChange("FormCode");
				this._FormCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("partSelector")]
		public string partSelector
		{
			get{ return _partSelector; }
			set
			{
				this.OnPropertyValueChange("partSelector");
				this._partSelector = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("partSubmitFunction")]
		public string partSubmitFunction
		{
			get{ return _partSubmitFunction; }
			set
			{
				this.OnPropertyValueChange("partSubmitFunction");
				this._partSubmitFunction = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("partName")]
		public string partName
		{
			get{ return _partName; }
			set
			{
				this.OnPropertyValueChange("partName");
				this._partName = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.FlowPerformID,
				_.FlowCode,
				_.FlowNodeCode,
				_.FormCode,
				_.partSelector,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.id,
				_.FlowPerformID,
				_.FlowCode,
				_.FlowNodeCode,
				_.FormCode,
				_.partSelector,
				_.partSubmitFunction,
				_.partName,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._id,
				this._FlowPerformID,
				this._FlowCode,
				this._FlowNodeCode,
				this._FormCode,
				this._partSelector,
				this._partSubmitFunction,
				this._partName,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbFlowPerformNodeFormPart");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id", "TbFlowPerformNodeFormPart", "");
            /// <summary>
			/// 流程执行流水号
			/// </summary>
			public readonly static Field FlowPerformID = new Field("FlowPerformID", "TbFlowPerformNodeFormPart", "流程执行流水号");
            /// <summary>
			/// 流程代码
			/// </summary>
			public readonly static Field FlowCode = new Field("FlowCode", "TbFlowPerformNodeFormPart", "流程代码");
            /// <summary>
			/// 流程节点代码
			/// </summary>
			public readonly static Field FlowNodeCode = new Field("FlowNodeCode", "TbFlowPerformNodeFormPart", "流程节点代码");
            /// <summary>
			/// 表单代码(系统自动生成)
			/// </summary>
			public readonly static Field FormCode = new Field("FormCode", "TbFlowPerformNodeFormPart", "表单代码(系统自动生成)");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field partSelector = new Field("partSelector", "TbFlowPerformNodeFormPart", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field partSubmitFunction = new Field("partSubmitFunction", "TbFlowPerformNodeFormPart", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field partName = new Field("partName", "TbFlowPerformNodeFormPart", "");
        }
        #endregion
	}
}