//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 交流互动评论
    /// </summary>
    [Table("TbArticleComment")]
    [Serializable]
    public partial class TbArticleComment : Entity
    {
        #region Model
		private int _ID;
		private int _ArticleID;
		private int _CommentID;
		private int _Type;
		private string _Content;
		private string _InsertUserCode;
		private DateTime _InsertTime;

		/// <summary>
		/// ID
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 文章ID
		/// </summary>
		[Field("ArticleID")]
		public int ArticleID
		{
			get{ return _ArticleID; }
			set
			{
				this.OnPropertyValueChange("ArticleID");
				this._ArticleID = value;
			}
		}
		/// <summary>
		/// 评论ID
		/// </summary>
		[Field("CommentID")]
		public int CommentID
		{
			get{ return _CommentID; }
			set
			{
				this.OnPropertyValueChange("CommentID");
				this._CommentID = value;
			}
		}
		/// <summary>
		/// 类型：1评论，2回复
		/// </summary>
		[Field("Type")]
		public int Type
		{
			get{ return _Type; }
			set
			{
				this.OnPropertyValueChange("Type");
				this._Type = value;
			}
		}
		/// <summary>
		/// 内容
		/// </summary>
		[Field("Content")]
		public string Content
		{
			get{ return _Content; }
			set
			{
				this.OnPropertyValueChange("Content");
				this._Content = value;
			}
		}
		/// <summary>
		/// 录入人
		/// </summary>
		[Field("InsertUserCode")]
		public string InsertUserCode
		{
			get{ return _InsertUserCode; }
			set
			{
				this.OnPropertyValueChange("InsertUserCode");
				this._InsertUserCode = value;
			}
		}
		/// <summary>
		/// 录入时间
		/// </summary>
		[Field("InsertTime")]
		public DateTime InsertTime
		{
			get{ return _InsertTime; }
			set
			{
				this.OnPropertyValueChange("InsertTime");
				this._InsertTime = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.ArticleID,
				_.CommentID,
				_.Type,
				_.Content,
				_.InsertUserCode,
				_.InsertTime,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._ArticleID,
				this._CommentID,
				this._Type,
				this._Content,
				this._InsertUserCode,
				this._InsertTime,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbArticleComment");
            /// <summary>
			/// ID
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbArticleComment", "ID");
            /// <summary>
			/// 文章ID
			/// </summary>
			public readonly static Field ArticleID = new Field("ArticleID", "TbArticleComment", "文章ID");
            /// <summary>
			/// 评论ID
			/// </summary>
			public readonly static Field CommentID = new Field("CommentID", "TbArticleComment", "评论ID");
            /// <summary>
			/// 类型：1评论，2回复
			/// </summary>
			public readonly static Field Type = new Field("Type", "TbArticleComment", "类型：1评论，2回复");
            /// <summary>
			/// 内容
			/// </summary>
			public readonly static Field Content = new Field("Content", "TbArticleComment", "内容");
            /// <summary>
			/// 录入人
			/// </summary>
			public readonly static Field InsertUserCode = new Field("InsertUserCode", "TbArticleComment", "录入人");
            /// <summary>
			/// 录入时间
			/// </summary>
			public readonly static Field InsertTime = new Field("InsertTime", "TbArticleComment", "录入时间");
        }
        #endregion

        #region 扩展字段
        public string UserName { get; set; }

        #endregion
	}
}