//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 产能填报
    /// </summary>
    [Table("TbCapacityFilling")]
    [Serializable]
    public partial class TbCapacityFilling : Entity
    {
        #region Model
		private int _ID;
		private string _CapacityMonth;
		private string _ProcessFactoryCode;
		private decimal? _Capacity;
		private decimal? _ActualOutputValue;
		private decimal? _ActualLoad;
		private string _Remark;
		private string _InsertUserCode;
		private DateTime? _InsertTiem;
		private int? _IsDefault;

		/// <summary>
		/// ID
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 产能填报月份
		/// </summary>
		[Field("CapacityMonth")]
		public string CapacityMonth
		{
			get{ return _CapacityMonth; }
			set
			{
				this.OnPropertyValueChange("CapacityMonth");
				this._CapacityMonth = value;
			}
		}
		/// <summary>
		/// 加工厂
		/// </summary>
		[Field("ProcessFactoryCode")]
		public string ProcessFactoryCode
		{
			get{ return _ProcessFactoryCode; }
			set
			{
				this.OnPropertyValueChange("ProcessFactoryCode");
				this._ProcessFactoryCode = value;
			}
		}
		/// <summary>
		/// 月产能
		/// </summary>
		[Field("Capacity")]
		public decimal? Capacity
		{
			get{ return _Capacity; }
			set
			{
				this.OnPropertyValueChange("Capacity");
				this._Capacity = value;
			}
		}
		/// <summary>
		/// 实际产值
		/// </summary>
		[Field("ActualOutputValue")]
		public decimal? ActualOutputValue
		{
			get{ return _ActualOutputValue; }
			set
			{
				this.OnPropertyValueChange("ActualOutputValue");
				this._ActualOutputValue = value;
			}
		}
		/// <summary>
		/// 实际负荷
		/// </summary>
		[Field("ActualLoad")]
		public decimal? ActualLoad
		{
			get{ return _ActualLoad; }
			set
			{
				this.OnPropertyValueChange("ActualLoad");
				this._ActualLoad = value;
			}
		}
		/// <summary>
		/// 备注
		/// </summary>
		[Field("Remark")]
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange("Remark");
				this._Remark = value;
			}
		}
		/// <summary>
		/// 填报人
		/// </summary>
		[Field("InsertUserCode")]
		public string InsertUserCode
		{
			get{ return _InsertUserCode; }
			set
			{
				this.OnPropertyValueChange("InsertUserCode");
				this._InsertUserCode = value;
			}
		}
		/// <summary>
		/// 填报时间
		/// </summary>
		[Field("InsertTiem")]
		public DateTime? InsertTiem
		{
			get{ return _InsertTiem; }
			set
			{
				this.OnPropertyValueChange("InsertTiem");
				this._InsertTiem = value;
			}
		}
		/// <summary>
		/// 是否默认
		/// </summary>
		[Field("IsDefault")]
		public int? IsDefault
		{
			get{ return _IsDefault; }
			set
			{
				this.OnPropertyValueChange("IsDefault");
				this._IsDefault = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.CapacityMonth,
				_.ProcessFactoryCode,
				_.Capacity,
				_.ActualOutputValue,
				_.ActualLoad,
				_.Remark,
				_.InsertUserCode,
				_.InsertTiem,
				_.IsDefault,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._CapacityMonth,
				this._ProcessFactoryCode,
				this._Capacity,
				this._ActualOutputValue,
				this._ActualLoad,
				this._Remark,
				this._InsertUserCode,
				this._InsertTiem,
				this._IsDefault,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbCapacityFilling");
            /// <summary>
			/// ID
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbCapacityFilling", "ID");
            /// <summary>
			/// 产能填报月份
			/// </summary>
			public readonly static Field CapacityMonth = new Field("CapacityMonth", "TbCapacityFilling", "产能填报月份");
            /// <summary>
			/// 加工厂
			/// </summary>
			public readonly static Field ProcessFactoryCode = new Field("ProcessFactoryCode", "TbCapacityFilling", "加工厂");
            /// <summary>
			/// 月产能
			/// </summary>
			public readonly static Field Capacity = new Field("Capacity", "TbCapacityFilling", "月产能");
            /// <summary>
			/// 实际产值
			/// </summary>
			public readonly static Field ActualOutputValue = new Field("ActualOutputValue", "TbCapacityFilling", "实际产值");
            /// <summary>
			/// 实际负荷
			/// </summary>
			public readonly static Field ActualLoad = new Field("ActualLoad", "TbCapacityFilling", "实际负荷");
            /// <summary>
			/// 备注
			/// </summary>
			public readonly static Field Remark = new Field("Remark", "TbCapacityFilling", "备注");
            /// <summary>
			/// 填报人
			/// </summary>
			public readonly static Field InsertUserCode = new Field("InsertUserCode", "TbCapacityFilling", "填报人");
            /// <summary>
			/// 填报时间
			/// </summary>
			public readonly static Field InsertTiem = new Field("InsertTiem", "TbCapacityFilling", "填报时间");
            /// <summary>
			/// 是否默认
			/// </summary>
			public readonly static Field IsDefault = new Field("IsDefault", "TbCapacityFilling", "是否默认");
        }
        #endregion
	}
}