//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36460
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 实体类TbOrderProgressDetail。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("TbOrderProgressDetail")]
    [Serializable]
    public partial class TbOrderProgressDetail : Entity
    {
        #region Model
		private int _ID;
		private string _OrderCode;
		private string _ComponentName;
		private string _LargePattern;
		private string _MaterialCode;
		private string _MaterialName;
		private string _SpecificationModel;
		private string _MeasurementUnit;
		private decimal? _MeasurementUnitZl;
		private decimal? _ItemUseNum;
		private int? _Number;
		private decimal? _WeightSmallPlan;
		private string _DaetailWorkStrat;
		private int? _PackNumber;
		private string _Manufactor;
		private string _HeatNo;
		private string _TestReportNo;
		private string _QRCode;
		private decimal? _TodayCompleted;
		private decimal? _AlreadyCompleted;
		private int? _WorkorderdetailId;
		private decimal? _NoCompleted;
		private string _RevokeStart;

		/// <summary>
		/// ID
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 订单编号
		/// </summary>
		[Field("OrderCode")]
		public string OrderCode
		{
			get{ return _OrderCode; }
			set
			{
				this.OnPropertyValueChange("OrderCode");
				this._OrderCode = value;
			}
		}
		/// <summary>
		/// 构建名称
		/// </summary>
		[Field("ComponentName")]
		public string ComponentName
		{
			get{ return _ComponentName; }
			set
			{
				this.OnPropertyValueChange("ComponentName");
				this._ComponentName = value;
			}
		}
		/// <summary>
		/// 大样图
		/// </summary>
		[Field("LargePattern")]
		public string LargePattern
		{
			get{ return _LargePattern; }
			set
			{
				this.OnPropertyValueChange("LargePattern");
				this._LargePattern = value;
			}
		}
		/// <summary>
		/// 原材料编号
		/// </summary>
		[Field("MaterialCode")]
		public string MaterialCode
		{
			get{ return _MaterialCode; }
			set
			{
				this.OnPropertyValueChange("MaterialCode");
				this._MaterialCode = value;
			}
		}
		/// <summary>
		/// 原材料名称
		/// </summary>
		[Field("MaterialName")]
		public string MaterialName
		{
			get{ return _MaterialName; }
			set
			{
				this.OnPropertyValueChange("MaterialName");
				this._MaterialName = value;
			}
		}
		/// <summary>
		/// 规格型号
		/// </summary>
		[Field("SpecificationModel")]
		public string SpecificationModel
		{
			get{ return _SpecificationModel; }
			set
			{
				this.OnPropertyValueChange("SpecificationModel");
				this._SpecificationModel = value;
			}
		}
		/// <summary>
		/// 计量单位
		/// </summary>
		[Field("MeasurementUnit")]
		public string MeasurementUnit
		{
			get{ return _MeasurementUnit; }
			set
			{
				this.OnPropertyValueChange("MeasurementUnit");
				this._MeasurementUnit = value;
			}
		}
		/// <summary>
		/// 单位重量
		/// </summary>
		[Field("MeasurementUnitZl")]
		public decimal? MeasurementUnitZl
		{
			get{ return _MeasurementUnitZl; }
			set
			{
				this.OnPropertyValueChange("MeasurementUnitZl");
				this._MeasurementUnitZl = value;
			}
		}
		/// <summary>
		/// 单件用量
		/// </summary>
		[Field("ItemUseNum")]
		public decimal? ItemUseNum
		{
			get{ return _ItemUseNum; }
			set
			{
				this.OnPropertyValueChange("ItemUseNum");
				this._ItemUseNum = value;
			}
		}
		/// <summary>
		/// 件数
		/// </summary>
		[Field("Number")]
		public int? Number
		{
			get{ return _Number; }
			set
			{
				this.OnPropertyValueChange("Number");
				this._Number = value;
			}
		}
		/// <summary>
		/// 重量小计
		/// </summary>
		[Field("WeightSmallPlan")]
		public decimal? WeightSmallPlan
		{
			get{ return _WeightSmallPlan; }
			set
			{
				this.OnPropertyValueChange("WeightSmallPlan");
				this._WeightSmallPlan = value;
			}
		}
		/// <summary>
		/// 加工状态
		/// </summary>
		[Field("DaetailWorkStrat")]
		public string DaetailWorkStrat
		{
			get{ return _DaetailWorkStrat; }
			set
			{
				this.OnPropertyValueChange("DaetailWorkStrat");
				this._DaetailWorkStrat = value;
			}
		}
		/// <summary>
		/// 打包件数
		/// </summary>
		[Field("PackNumber")]
		public int? PackNumber
		{
			get{ return _PackNumber; }
			set
			{
				this.OnPropertyValueChange("PackNumber");
				this._PackNumber = value;
			}
		}
		/// <summary>
		/// 厂家
		/// </summary>
		[Field("Manufactor")]
		public string Manufactor
		{
			get{ return _Manufactor; }
			set
			{
				this.OnPropertyValueChange("Manufactor");
				this._Manufactor = value;
			}
		}
		/// <summary>
		/// 炉批号
		/// </summary>
		[Field("HeatNo")]
		public string HeatNo
		{
			get{ return _HeatNo; }
			set
			{
				this.OnPropertyValueChange("HeatNo");
				this._HeatNo = value;
			}
		}
		/// <summary>
		/// 检测报告编号
		/// </summary>
		[Field("TestReportNo")]
		public string TestReportNo
		{
			get{ return _TestReportNo; }
			set
			{
				this.OnPropertyValueChange("TestReportNo");
				this._TestReportNo = value;
			}
		}
		/// <summary>
		/// 二维码编号
		/// </summary>
		[Field("QRCode")]
		public string QRCode
		{
			get{ return _QRCode; }
			set
			{
				this.OnPropertyValueChange("QRCode");
				this._QRCode = value;
			}
		}
		/// <summary>
		/// 当日完成量
		/// </summary>
		[Field("TodayCompleted")]
		public decimal? TodayCompleted
		{
			get{ return _TodayCompleted; }
			set
			{
				this.OnPropertyValueChange("TodayCompleted");
				this._TodayCompleted = value;
			}
		}
		/// <summary>
		/// 开累完成量
		/// </summary>
		[Field("AlreadyCompleted")]
		public decimal? AlreadyCompleted
		{
			get{ return _AlreadyCompleted; }
			set
			{
				this.OnPropertyValueChange("AlreadyCompleted");
				this._AlreadyCompleted = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("WorkorderdetailId")]
		public int? WorkorderdetailId
		{
			get{ return _WorkorderdetailId; }
			set
			{
				this.OnPropertyValueChange("WorkorderdetailId");
				this._WorkorderdetailId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("NoCompleted")]
		public decimal? NoCompleted
		{
			get{ return _NoCompleted; }
			set
			{
				this.OnPropertyValueChange("NoCompleted");
				this._NoCompleted = value;
			}
		}
		/// <summary>
		/// 撤销状态
		/// </summary>
		[Field("RevokeStart")]
		public string RevokeStart
		{
			get{ return _RevokeStart; }
			set
			{
				this.OnPropertyValueChange("RevokeStart");
				this._RevokeStart = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.OrderCode,
				_.ComponentName,
				_.LargePattern,
				_.MaterialCode,
				_.MaterialName,
				_.SpecificationModel,
				_.MeasurementUnit,
				_.MeasurementUnitZl,
				_.ItemUseNum,
				_.Number,
				_.WeightSmallPlan,
				_.DaetailWorkStrat,
				_.PackNumber,
				_.Manufactor,
				_.HeatNo,
				_.TestReportNo,
				_.QRCode,
				_.TodayCompleted,
				_.AlreadyCompleted,
				_.WorkorderdetailId,
				_.NoCompleted,
				_.RevokeStart,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._OrderCode,
				this._ComponentName,
				this._LargePattern,
				this._MaterialCode,
				this._MaterialName,
				this._SpecificationModel,
				this._MeasurementUnit,
				this._MeasurementUnitZl,
				this._ItemUseNum,
				this._Number,
				this._WeightSmallPlan,
				this._DaetailWorkStrat,
				this._PackNumber,
				this._Manufactor,
				this._HeatNo,
				this._TestReportNo,
				this._QRCode,
				this._TodayCompleted,
				this._AlreadyCompleted,
				this._WorkorderdetailId,
				this._NoCompleted,
				this._RevokeStart,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbOrderProgressDetail");
            /// <summary>
			/// ID
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbOrderProgressDetail", "ID");
            /// <summary>
			/// 订单编号
			/// </summary>
			public readonly static Field OrderCode = new Field("OrderCode", "TbOrderProgressDetail", "订单编号");
            /// <summary>
			/// 构建名称
			/// </summary>
			public readonly static Field ComponentName = new Field("ComponentName", "TbOrderProgressDetail", "构建名称");
            /// <summary>
			/// 大样图
			/// </summary>
			public readonly static Field LargePattern = new Field("LargePattern", "TbOrderProgressDetail", "大样图");
            /// <summary>
			/// 原材料编号
			/// </summary>
			public readonly static Field MaterialCode = new Field("MaterialCode", "TbOrderProgressDetail", "原材料编号");
            /// <summary>
			/// 原材料名称
			/// </summary>
			public readonly static Field MaterialName = new Field("MaterialName", "TbOrderProgressDetail", "原材料名称");
            /// <summary>
			/// 规格型号
			/// </summary>
			public readonly static Field SpecificationModel = new Field("SpecificationModel", "TbOrderProgressDetail", "规格型号");
            /// <summary>
			/// 计量单位
			/// </summary>
			public readonly static Field MeasurementUnit = new Field("MeasurementUnit", "TbOrderProgressDetail", "计量单位");
            /// <summary>
			/// 单位重量
			/// </summary>
			public readonly static Field MeasurementUnitZl = new Field("MeasurementUnitZl", "TbOrderProgressDetail", "单位重量");
            /// <summary>
			/// 单件用量
			/// </summary>
			public readonly static Field ItemUseNum = new Field("ItemUseNum", "TbOrderProgressDetail", "单件用量");
            /// <summary>
			/// 件数
			/// </summary>
			public readonly static Field Number = new Field("Number", "TbOrderProgressDetail", "件数");
            /// <summary>
			/// 重量小计
			/// </summary>
			public readonly static Field WeightSmallPlan = new Field("WeightSmallPlan", "TbOrderProgressDetail", "重量小计");
            /// <summary>
			/// 加工状态
			/// </summary>
			public readonly static Field DaetailWorkStrat = new Field("DaetailWorkStrat", "TbOrderProgressDetail", "加工状态");
            /// <summary>
			/// 打包件数
			/// </summary>
			public readonly static Field PackNumber = new Field("PackNumber", "TbOrderProgressDetail", "打包件数");
            /// <summary>
			/// 厂家
			/// </summary>
			public readonly static Field Manufactor = new Field("Manufactor", "TbOrderProgressDetail", "厂家");
            /// <summary>
			/// 炉批号
			/// </summary>
			public readonly static Field HeatNo = new Field("HeatNo", "TbOrderProgressDetail", "炉批号");
            /// <summary>
			/// 检测报告编号
			/// </summary>
			public readonly static Field TestReportNo = new Field("TestReportNo", "TbOrderProgressDetail", "检测报告编号");
            /// <summary>
			/// 二维码编号
			/// </summary>
			public readonly static Field QRCode = new Field("QRCode", "TbOrderProgressDetail", "二维码编号");
            /// <summary>
			/// 当日完成量
			/// </summary>
			public readonly static Field TodayCompleted = new Field("TodayCompleted", "TbOrderProgressDetail", "当日完成量");
            /// <summary>
			/// 开累完成量
			/// </summary>
			public readonly static Field AlreadyCompleted = new Field("AlreadyCompleted", "TbOrderProgressDetail", "开累完成量");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field WorkorderdetailId = new Field("WorkorderdetailId", "TbOrderProgressDetail", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field NoCompleted = new Field("NoCompleted", "TbOrderProgressDetail", "");
            /// <summary>
			/// 撤销状态
			/// </summary>
			public readonly static Field RevokeStart = new Field("RevokeStart", "TbOrderProgressDetail", "撤销状态");
        }
        #endregion
	}
}