//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36450
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;
using PM.DataEntity.Base;

namespace PM.DataEntity
{
    /// <summary>
    /// 人员工日消耗 主表 实体类TbPersonnelWorkDayConsume。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("TbPersonnelWorkDayConsume")]
    [Serializable]
    public partial class TbPersonnelWorkDayConsume : BaseEntity
    {
        #region Model
        private int _ID;
        private string _ConsumeCode;
        private string _SiteCode;
        private string _OrderCode;
        private string _TypeCode;
        private string _TypeName;
        private DateTime _OrderReceiveDate;
        private string _ProcessFactoryCode;
        private string _InsertUserCode;
        private DateTime _InsertTime;
        private string _Remarks;
        private string _Examinestatus;
        private string _Enclosure;

        /// <summary>
        /// 人员工日消耗 主表标识ID
        /// </summary>
        [Field("ID")]
        public int ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }
        /// <summary>
        /// 工日消耗单号
        /// </summary>
        [Field("ConsumeCode")]
        public string ConsumeCode
        {
            get { return _ConsumeCode; }
            set
            {
                this.OnPropertyValueChange("ConsumeCode");
                this._ConsumeCode = value;
            }
        }
        /// <summary>
        /// 站点名称Code
        /// </summary>
        [Field("SiteCode")]
        public string SiteCode
        {
            get { return _SiteCode; }
            set
            {
                this.OnPropertyValueChange("SiteCode");
                this._SiteCode = value;
            }
        }
        /// <summary>
        /// 订单编号
        /// </summary>
        [Field("OrderCode")]
        public string OrderCode
        {
            get { return _OrderCode; }
            set
            {
                this.OnPropertyValueChange("OrderCode");
                this._OrderCode = value;
            }
        }
        /// <summary>
        /// 订单类型
        /// </summary>
        [Field("TypeCode")]
        public string TypeCode
        {
            get { return _TypeCode; }
            set
            {
                this.OnPropertyValueChange("TypeCode");
                this._TypeCode = value;
            }
        }
        /// <summary>
        /// 订单名称
        /// </summary>
        [Field("TypeName")]
        public string TypeName
        {
            get { return _TypeName; }
            set
            {
                this.OnPropertyValueChange("TypeName");
                this._TypeName = value;
            }
        }
        /// <summary>
        /// 订单接收日期
        /// </summary>
        [Field("OrderReceiveDate")]
        public DateTime OrderReceiveDate
        {
            get { return _OrderReceiveDate; }
            set
            {
                this.OnPropertyValueChange("OrderReceiveDate");
                this._OrderReceiveDate = value;
            }
        }
        /// <summary>
        /// 加工厂名称Code
        /// </summary>
        [Field("ProcessFactoryCode")]
        public string ProcessFactoryCode
        {
            get { return _ProcessFactoryCode; }
            set
            {
                this.OnPropertyValueChange("ProcessFactoryCode");
                this._ProcessFactoryCode = value;
            }
        }
        /// <summary>
        /// 录入人Code
        /// </summary>
        [Field("InsertUserCode")]
        public string InsertUserCode
        {
            get { return _InsertUserCode; }
            set
            {
                this.OnPropertyValueChange("InsertUserCode");
                this._InsertUserCode = value;
            }
        }
        /// <summary>
        /// 录入时间
        /// </summary>
        [Field("InsertTime")]
        public DateTime InsertTime
        {
            get { return _InsertTime; }
            set
            {
                this.OnPropertyValueChange("InsertTime");
                this._InsertTime = value;
            }
        }
        /// <summary>
        /// 备注
        /// </summary>
        [Field("Remarks")]
        public string Remarks
        {
            get { return _Remarks; }
            set
            {
                this.OnPropertyValueChange("Remarks");
                this._Remarks = value;
            }
        }
        /// <summary>
        /// 审批状态
        /// </summary>
        [Field("Examinestatus")]
        public string Examinestatus
        {
            get { return _Examinestatus; }
            set
            {
                this.OnPropertyValueChange("Examinestatus");
                this._Examinestatus = value;
            }
        }
        /// <summary>
        /// 附件
        /// </summary>
        [Field("Enclosure")]
        public string Enclosure
        {
            get { return _Enclosure; }
            set
            {
                this.OnPropertyValueChange("Enclosure");
                this._Enclosure = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ConsumeCode,
			};
        }

        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }

        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.ConsumeCode,
				_.SiteCode,
				_.OrderCode,
				_.OrderReceiveDate,
				_.ProcessFactoryCode,
				_.InsertUserCode,
				_.InsertTime,
				_.Remarks,
				_.Examinestatus,
				_.Enclosure,
                _.TypeName,
                _.TypeCode,
                _.ProjectId
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._ConsumeCode,
				this._SiteCode,
				this._OrderCode,
				this._OrderReceiveDate,
				this._ProcessFactoryCode,
				this._InsertUserCode,
				this._InsertTime,
				this._Remarks,
				this._Examinestatus,
				this._Enclosure,
                this._TypeName,
                this._TypeCode,
                this._ProjectId
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _ : BaseField<TbPersonnelWorkDayConsume>
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "TbPersonnelWorkDayConsume");
            /// <summary>
            /// 人员工日消耗 主表标识ID
            /// </summary>
            public readonly static Field ID = new Field("ID", "TbPersonnelWorkDayConsume", "人员工日消耗 主表标识ID");
            /// <summary>
            /// 工日消耗单号
            /// </summary>
            public readonly static Field ConsumeCode = new Field("ConsumeCode", "TbPersonnelWorkDayConsume", "工日消耗单号");
            /// <summary>
            /// 站点名称Code
            /// </summary>
            public readonly static Field SiteCode = new Field("SiteCode", "TbPersonnelWorkDayConsume", "站点名称Code");
            /// <summary>
            /// 订单编号
            /// </summary>
            public readonly static Field OrderCode = new Field("OrderCode", "TbPersonnelWorkDayConsume", "订单编号");
            /// <summary>
            /// 订单接收日期
            /// </summary>
            public readonly static Field OrderReceiveDate = new Field("OrderReceiveDate", "TbPersonnelWorkDayConsume", "订单接收日期");
            /// <summary>
            /// 加工厂名称Code
            /// </summary>
            public readonly static Field ProcessFactoryCode = new Field("ProcessFactoryCode", "TbPersonnelWorkDayConsume", "加工厂名称Code");
            /// <summary>
            /// 录入人Code
            /// </summary>
            public readonly static Field InsertUserCode = new Field("InsertUserCode", "TbPersonnelWorkDayConsume", "录入人Code");
            /// <summary>
            /// 录入时间
            /// </summary>
            public readonly static Field InsertTime = new Field("InsertTime", "TbPersonnelWorkDayConsume", "录入时间");
            /// <summary>
            /// 备注
            /// </summary>
            public readonly static Field Remarks = new Field("Remarks", "TbPersonnelWorkDayConsume", "备注");
            /// <summary>
            /// 审批状态
            /// </summary>
            public readonly static Field Examinestatus = new Field("Examinestatus", "TbPersonnelWorkDayConsume", "审批状态");
            /// <summary>
            /// 附件
            /// </summary>
            public readonly static Field Enclosure = new Field("Enclosure", "TbPersonnelWorkDayConsume", "附件");
            /// <summary>
            /// 订单类型
            /// </summary>
            public readonly static Field TypeCode = new Field("TypeCode", "TbPersonnelWorkDayConsume", "订单类型");
            /// <summary>
            /// 订单名称
            /// </summary>
            public readonly static Field TypeName = new Field("TypeName", "TbPersonnelWorkDayConsume", "订单名称");
        }
        #endregion
    }
}