//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36450
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 人员工日消耗 明细表 实体类TbPersonnelWorkDayConsumeItem。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("TbPersonnelWorkDayConsumeItem")]
    [Serializable]
    public partial class TbPersonnelWorkDayConsumeItem : Entity
    {
        #region Model
        private int _ID;
        private string _ComponentCode;
        private string _MaterialCode;
        private string _Standard;
        private decimal _OrderProcessQuantity;
        private decimal _RawMaterialConsumeQuantity;
        private DateTime _ProcessStartTime;
        private DateTime _ProcessEndTime;
        private int _NumberOfPeople;
        private decimal _NumberOfDays;
        private decimal _UnitManpowerConsume;
        private string _ConsumeCode;
        private string _MaterialName;

        /// <summary>
        /// 人员工日消耗 明细表 标识ID
        /// </summary>
        [Field("ID")]
        public int ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }
        /// <summary>
        /// 构件名称Code
        /// </summary>
        [Field("ComponentCode")]
        public string ComponentCode
        {
            get { return _ComponentCode; }
            set
            {
                this.OnPropertyValueChange("ComponentCode");
                this._ComponentCode = value;
            }
        }
        /// <summary>
        /// 原材料编号Code
        /// </summary>
        [Field("MaterialCode")]
        public string MaterialCode
        {
            get { return _MaterialCode; }
            set
            {
                this.OnPropertyValueChange("MaterialCode");
                this._MaterialCode = value;
            }
        }
        /// <summary>
        /// 原材料名称
        /// </summary>
        [Field("MaterialName")]
        public string MaterialName
        {
            get { return _MaterialName; }
            set
            {
                this.OnPropertyValueChange("MaterialName");
                this._MaterialName = value;
            }
        }
        /// <summary>
        /// 规格
        /// </summary>
        [Field("Standard")]
        public string Standard
        {
            get { return _Standard; }
            set
            {
                this.OnPropertyValueChange("Standard");
                this._Standard = value;
            }
        }
        /// <summary>
        /// 订单加工量
        /// </summary>
        [Field("OrderProcessQuantity")]
        public decimal OrderProcessQuantity
        {
            get { return _OrderProcessQuantity; }
            set
            {
                this.OnPropertyValueChange("OrderProcessQuantity");
                this._OrderProcessQuantity = value;
            }
        }
        /// <summary>
        /// 原材料消耗量
        /// </summary>
        [Field("RawMaterialConsumeQuantity")]
        public decimal RawMaterialConsumeQuantity
        {
            get { return _RawMaterialConsumeQuantity; }
            set
            {
                this.OnPropertyValueChange("RawMaterialConsumeQuantity");
                this._RawMaterialConsumeQuantity = value;
            }
        }
        /// <summary>
        /// 加工开始时间
        /// </summary>
        [Field("ProcessStartTime")]
        public DateTime ProcessStartTime
        {
            get { return _ProcessStartTime; }
            set
            {
                this.OnPropertyValueChange("ProcessStartTime");
                this._ProcessStartTime = value;
            }
        }
        /// <summary>
        /// 加工结束时间
        /// </summary>
        [Field("ProcessEndTime")]
        public DateTime ProcessEndTime
        {
            get { return _ProcessEndTime; }
            set
            {
                this.OnPropertyValueChange("ProcessEndTime");
                this._ProcessEndTime = value;
            }
        }
        /// <summary>
        /// 人数
        /// </summary>
        [Field("NumberOfPeople")]
        public int NumberOfPeople
        {
            get { return _NumberOfPeople; }
            set
            {
                this.OnPropertyValueChange("NumberOfPeople");
                this._NumberOfPeople = value;
            }
        }
        /// <summary>
        /// 工日数
        /// </summary>
        [Field("NumberOfDays")]
        public decimal NumberOfDays
        {
            get { return _NumberOfDays; }
            set
            {
                this.OnPropertyValueChange("NumberOfDays");
                this._NumberOfDays = value;
            }
        }
        /// <summary>
        /// 单位人工消耗
        /// </summary>
        [Field("UnitManpowerConsume")]
        public decimal UnitManpowerConsume
        {
            get { return _UnitManpowerConsume; }
            set
            {
                this.OnPropertyValueChange("UnitManpowerConsume");
                this._UnitManpowerConsume = value;
            }
        }
        /// <summary>
        /// 工日消耗单号
        /// </summary>
        [Field("ConsumeCode")]
        public string ConsumeCode
        {
            get { return _ConsumeCode; }
            set
            {
                this.OnPropertyValueChange("ConsumeCode");
                this._ConsumeCode = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.ComponentCode,
				_.MaterialCode,
				_.Standard,
				_.OrderProcessQuantity,
				_.RawMaterialConsumeQuantity,
				_.ProcessStartTime,
				_.ProcessEndTime,
				_.NumberOfPeople,
				_.NumberOfDays,
				_.UnitManpowerConsume,
				_.ConsumeCode,
                _.MaterialName,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._ComponentCode,
				this._MaterialCode,
				this._Standard,
				this._OrderProcessQuantity,
				this._RawMaterialConsumeQuantity,
				this._ProcessStartTime,
				this._ProcessEndTime,
				this._NumberOfPeople,
				this._NumberOfDays,
				this._UnitManpowerConsume,
				this._ConsumeCode,
                this._MaterialName,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "TbPersonnelWorkDayConsumeItem");
            /// <summary>
            /// 人员工日消耗 明细表 标识ID
            /// </summary>
            public readonly static Field ID = new Field("ID", "TbPersonnelWorkDayConsumeItem", "人员工日消耗 明细表 标识ID");
            /// <summary>
            /// 构件名称Code
            /// </summary>
            public readonly static Field ComponentCode = new Field("ComponentCode", "TbPersonnelWorkDayConsumeItem", "构件名称Code");
            /// <summary>
            /// 原材料编号Code
            /// </summary>
            public readonly static Field MaterialCode = new Field("MaterialCode", "TbPersonnelWorkDayConsumeItem", "原材料编号Code");
            /// <summary>
            /// 规格
            /// </summary>
            public readonly static Field Standard = new Field("Standard", "TbPersonnelWorkDayConsumeItem", "规格");
            /// <summary>
            /// 订单加工量
            /// </summary>
            public readonly static Field OrderProcessQuantity = new Field("OrderProcessQuantity", "TbPersonnelWorkDayConsumeItem", "订单加工量");
            /// <summary>
            /// 原材料消耗量
            /// </summary>
            public readonly static Field RawMaterialConsumeQuantity = new Field("RawMaterialConsumeQuantity", "TbPersonnelWorkDayConsumeItem", "原材料消耗量");
            /// <summary>
            /// 加工开始时间
            /// </summary>
            public readonly static Field ProcessStartTime = new Field("ProcessStartTime", "TbPersonnelWorkDayConsumeItem", "加工开始时间");
            /// <summary>
            /// 加工结束时间
            /// </summary>
            public readonly static Field ProcessEndTime = new Field("ProcessEndTime", "TbPersonnelWorkDayConsumeItem", "加工结束时间");
            /// <summary>
            /// 人数
            /// </summary>
            public readonly static Field NumberOfPeople = new Field("NumberOfPeople", "TbPersonnelWorkDayConsumeItem", "人数");
            /// <summary>
            /// 工日数
            /// </summary>
            public readonly static Field NumberOfDays = new Field("NumberOfDays", "TbPersonnelWorkDayConsumeItem", "工日数");
            /// <summary>
            /// 单位人工消耗
            /// </summary>
            public readonly static Field UnitManpowerConsume = new Field("UnitManpowerConsume", "TbPersonnelWorkDayConsumeItem", "单位人工消耗");
            /// <summary>
            /// 工日消耗单号
            /// </summary>
            public readonly static Field ConsumeCode = new Field("ConsumeCode", "TbPersonnelWorkDayConsumeItem", "工日消耗单号");
            /// <summary>
            /// 原材料名称
            /// </summary>
            public readonly static Field MaterialName = new Field("MaterialName", "TbPersonnelWorkDayConsumeItem", "原材料名称");
        }
        #endregion
    }
}