//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36460
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 订单变更
    /// </summary>
    [Table("TbProblemOrder")]
    [Serializable]
    public partial class TbProblemOrder : Entity
    {
        #region Model
		private int _ID;
		private string _ProblemOrderCode;
		private string _OrderCode;
		private string _TypeCode;
		private string _TypeName;
		private string _ProcessFactoryCode;
		private string _SiteCode;
		private string _UsePart;
		private DateTime _DistributionTime;
		private string _ProcessingState;
		private decimal? _Total;
		private string _DistributionAddress;
		private string _RevokeStatus;
		private string _Examinestatus;
		private string _Enclosure;
		private string _InsertUserCode;
		private DateTime _InsertTime;
		private string _ProjectId;
		private decimal? _OldTotal;

		/// <summary>
		/// ID
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 问题订单编号
		/// </summary>
		[Field("ProblemOrderCode")]
		public string ProblemOrderCode
		{
			get{ return _ProblemOrderCode; }
			set
			{
				this.OnPropertyValueChange("ProblemOrderCode");
				this._ProblemOrderCode = value;
			}
		}
		/// <summary>
		/// 原订单编号
		/// </summary>
		[Field("OrderCode")]
		public string OrderCode
		{
			get{ return _OrderCode; }
			set
			{
				this.OnPropertyValueChange("OrderCode");
				this._OrderCode = value;
			}
		}
		/// <summary>
		/// 类型编码
		/// </summary>
		[Field("TypeCode")]
		public string TypeCode
		{
			get{ return _TypeCode; }
			set
			{
				this.OnPropertyValueChange("TypeCode");
				this._TypeCode = value;
			}
		}
		/// <summary>
		/// 类型名称
		/// </summary>
		[Field("TypeName")]
		public string TypeName
		{
			get{ return _TypeName; }
			set
			{
				this.OnPropertyValueChange("TypeName");
				this._TypeName = value;
			}
		}
		/// <summary>
		/// 加工厂名称
		/// </summary>
		[Field("ProcessFactoryCode")]
		public string ProcessFactoryCode
		{
			get{ return _ProcessFactoryCode; }
			set
			{
				this.OnPropertyValueChange("ProcessFactoryCode");
				this._ProcessFactoryCode = value;
			}
		}
		/// <summary>
		/// 站点名称
		/// </summary>
		[Field("SiteCode")]
		public string SiteCode
		{
			get{ return _SiteCode; }
			set
			{
				this.OnPropertyValueChange("SiteCode");
				this._SiteCode = value;
			}
		}
		/// <summary>
		/// 使用部位
		/// </summary>
		[Field("UsePart")]
		public string UsePart
		{
			get{ return _UsePart; }
			set
			{
				this.OnPropertyValueChange("UsePart");
				this._UsePart = value;
			}
		}
		/// <summary>
		/// 配送时间
		/// </summary>
		[Field("DistributionTime")]
		public DateTime DistributionTime
		{
			get{ return _DistributionTime; }
			set
			{
				this.OnPropertyValueChange("DistributionTime");
				this._DistributionTime = value;
			}
		}
		/// <summary>
		/// 加工状态
		/// </summary>
		[Field("ProcessingState")]
		public string ProcessingState
		{
			get{ return _ProcessingState; }
			set
			{
				this.OnPropertyValueChange("ProcessingState");
				this._ProcessingState = value;
			}
		}
		/// <summary>
		/// 总量合计
		/// </summary>
		[Field("Total")]
		public decimal? Total
		{
			get{ return _Total; }
			set
			{
				this.OnPropertyValueChange("Total");
				this._Total = value;
			}
		}
		/// <summary>
		/// 配送地址
		/// </summary>
		[Field("DistributionAddress")]
		public string DistributionAddress
		{
			get{ return _DistributionAddress; }
			set
			{
				this.OnPropertyValueChange("DistributionAddress");
				this._DistributionAddress = value;
			}
		}
		/// <summary>
		/// 撤销状态：未撤销，已撤销
		/// </summary>
		[Field("RevokeStatus")]
		public string RevokeStatus
		{
			get{ return _RevokeStatus; }
			set
			{
				this.OnPropertyValueChange("RevokeStatus");
				this._RevokeStatus = value;
			}
		}
		/// <summary>
		/// 审批状态
		/// </summary>
		[Field("Examinestatus")]
		public string Examinestatus
		{
			get{ return _Examinestatus; }
			set
			{
				this.OnPropertyValueChange("Examinestatus");
				this._Examinestatus = value;
			}
		}
		/// <summary>
		/// 附件
		/// </summary>
		[Field("Enclosure")]
		public string Enclosure
		{
			get{ return _Enclosure; }
			set
			{
				this.OnPropertyValueChange("Enclosure");
				this._Enclosure = value;
			}
		}
		/// <summary>
		/// 录入人
		/// </summary>
		[Field("InsertUserCode")]
		public string InsertUserCode
		{
			get{ return _InsertUserCode; }
			set
			{
				this.OnPropertyValueChange("InsertUserCode");
				this._InsertUserCode = value;
			}
		}
		/// <summary>
		/// 录入时间
		/// </summary>
		[Field("InsertTime")]
		public DateTime InsertTime
		{
			get{ return _InsertTime; }
			set
			{
				this.OnPropertyValueChange("InsertTime");
				this._InsertTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ProjectId")]
		public string ProjectId
		{
			get{ return _ProjectId; }
			set
			{
				this.OnPropertyValueChange("ProjectId");
				this._ProjectId = value;
			}
		}
		/// <summary>
		/// 原订单重量
		/// </summary>
		[Field("OldTotal")]
		public decimal? OldTotal
		{
			get{ return _OldTotal; }
			set
			{
				this.OnPropertyValueChange("OldTotal");
				this._OldTotal = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.ProblemOrderCode,
				_.OrderCode,
				_.TypeCode,
				_.TypeName,
				_.ProcessFactoryCode,
				_.SiteCode,
				_.UsePart,
				_.DistributionTime,
				_.ProcessingState,
				_.Total,
				_.DistributionAddress,
				_.RevokeStatus,
				_.Examinestatus,
				_.Enclosure,
				_.InsertUserCode,
				_.InsertTime,
				_.ProjectId,
				_.OldTotal,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._ProblemOrderCode,
				this._OrderCode,
				this._TypeCode,
				this._TypeName,
				this._ProcessFactoryCode,
				this._SiteCode,
				this._UsePart,
				this._DistributionTime,
				this._ProcessingState,
				this._Total,
				this._DistributionAddress,
				this._RevokeStatus,
				this._Examinestatus,
				this._Enclosure,
				this._InsertUserCode,
				this._InsertTime,
				this._ProjectId,
				this._OldTotal,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbProblemOrder");
            /// <summary>
			/// ID
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbProblemOrder", "ID");
            /// <summary>
			/// 问题订单编号
			/// </summary>
			public readonly static Field ProblemOrderCode = new Field("ProblemOrderCode", "TbProblemOrder", "问题订单编号");
            /// <summary>
			/// 原订单编号
			/// </summary>
			public readonly static Field OrderCode = new Field("OrderCode", "TbProblemOrder", "原订单编号");
            /// <summary>
			/// 类型编码
			/// </summary>
			public readonly static Field TypeCode = new Field("TypeCode", "TbProblemOrder", "类型编码");
            /// <summary>
			/// 类型名称
			/// </summary>
			public readonly static Field TypeName = new Field("TypeName", "TbProblemOrder", "类型名称");
            /// <summary>
			/// 加工厂名称
			/// </summary>
			public readonly static Field ProcessFactoryCode = new Field("ProcessFactoryCode", "TbProblemOrder", "加工厂名称");
            /// <summary>
			/// 站点名称
			/// </summary>
			public readonly static Field SiteCode = new Field("SiteCode", "TbProblemOrder", "站点名称");
            /// <summary>
			/// 使用部位
			/// </summary>
			public readonly static Field UsePart = new Field("UsePart", "TbProblemOrder", "使用部位");
            /// <summary>
			/// 配送时间
			/// </summary>
			public readonly static Field DistributionTime = new Field("DistributionTime", "TbProblemOrder", "配送时间");
            /// <summary>
			/// 加工状态
			/// </summary>
			public readonly static Field ProcessingState = new Field("ProcessingState", "TbProblemOrder", "加工状态");
            /// <summary>
			/// 总量合计
			/// </summary>
			public readonly static Field Total = new Field("Total", "TbProblemOrder", "总量合计");
            /// <summary>
			/// 配送地址
			/// </summary>
			public readonly static Field DistributionAddress = new Field("DistributionAddress", "TbProblemOrder", "配送地址");
            /// <summary>
			/// 撤销状态：未撤销，已撤销
			/// </summary>
			public readonly static Field RevokeStatus = new Field("RevokeStatus", "TbProblemOrder", "撤销状态：未撤销，已撤销");
            /// <summary>
			/// 审批状态
			/// </summary>
			public readonly static Field Examinestatus = new Field("Examinestatus", "TbProblemOrder", "审批状态");
            /// <summary>
			/// 附件
			/// </summary>
			public readonly static Field Enclosure = new Field("Enclosure", "TbProblemOrder", "附件");
            /// <summary>
			/// 录入人
			/// </summary>
			public readonly static Field InsertUserCode = new Field("InsertUserCode", "TbProblemOrder", "录入人");
            /// <summary>
			/// 录入时间
			/// </summary>
			public readonly static Field InsertTime = new Field("InsertTime", "TbProblemOrder", "录入时间");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ProjectId = new Field("ProjectId", "TbProblemOrder", "");
            /// <summary>
			/// 原订单重量
			/// </summary>
			public readonly static Field OldTotal = new Field("OldTotal", "TbProblemOrder", "原订单重量");
        }
        #endregion
	}
}