//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36460
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 实体类TbProcessingTechnology。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("TbProcessingTechnology")]
    [Serializable]
    public partial class TbProcessingTechnology : Entity
    {
        #region Model
		private int _ID;
		private int? _PID;
		private int? _Sort;
		private string _ProcessingTechnologyName;

		/// <summary>
		/// ID
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// PID
		/// </summary>
		[Field("PID")]
		public int? PID
		{
			get{ return _PID; }
			set
			{
				this.OnPropertyValueChange("PID");
				this._PID = value;
			}
		}
		/// <summary>
		/// 序号
		/// </summary>
		[Field("Sort")]
		public int? Sort
		{
			get{ return _Sort; }
			set
			{
				this.OnPropertyValueChange("Sort");
				this._Sort = value;
			}
		}
		/// <summary>
		/// 加工工艺名称
		/// </summary>
		[Field("ProcessingTechnologyName")]
		public string ProcessingTechnologyName
		{
			get{ return _ProcessingTechnologyName; }
			set
			{
				this.OnPropertyValueChange("ProcessingTechnologyName");
				this._ProcessingTechnologyName = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.PID,
				_.Sort,
				_.ProcessingTechnologyName,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._PID,
				this._Sort,
				this._ProcessingTechnologyName,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbProcessingTechnology");
            /// <summary>
			/// ID
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbProcessingTechnology", "ID");
            /// <summary>
			/// PID
			/// </summary>
			public readonly static Field PID = new Field("PID", "TbProcessingTechnology", "PID");
            /// <summary>
			/// 序号
			/// </summary>
			public readonly static Field Sort = new Field("Sort", "TbProcessingTechnology", "序号");
            /// <summary>
			/// 加工工艺名称
			/// </summary>
			public readonly static Field ProcessingTechnologyName = new Field("ProcessingTechnologyName", "TbProcessingTechnology", "加工工艺名称");
        }
        #endregion
	}
}