//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 问题订单明细
    /// </summary>
    [Table("TbProblemOrderItem")]
    [Serializable]
    public partial class TbProblemOrderItem : Entity
    {
        #region Model
		private int _ID;
		private string _ProblemOrderCode;
		private string _ComponentName;
		private string _LargePattern;
		private string _MaterialCode;
		private string _MaterialName;
		private string _SpecificationModel;
		private string _MeasurementUnit;
		private decimal _Weight;
		private decimal _UseCount;
		private decimal _Count;
		private decimal _WeightTotal;
		private string _ProcessingState;
        private int _PackCount;
		private string _Factory;
		private string _BatchNumber;
		private string _TestReportCode;
		private int? _WorkOrderDetailId;

		/// <summary>
		/// ID
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 问题订单编号
		/// </summary>
		[Field("ProblemOrderCode")]
		public string ProblemOrderCode
		{
			get{ return _ProblemOrderCode; }
			set
			{
				this.OnPropertyValueChange("ProblemOrderCode");
				this._ProblemOrderCode = value;
			}
		}
		/// <summary>
		/// 构件名称
		/// </summary>
		[Field("ComponentName")]
		public string ComponentName
		{
			get{ return _ComponentName; }
			set
			{
				this.OnPropertyValueChange("ComponentName");
				this._ComponentName = value;
			}
		}
		/// <summary>
		/// 大样图
		/// </summary>
		[Field("LargePattern")]
		public string LargePattern
		{
			get{ return _LargePattern; }
			set
			{
				this.OnPropertyValueChange("LargePattern");
				this._LargePattern = value;
			}
		}
		/// <summary>
		/// 原材编号
		/// </summary>
		[Field("MaterialCode")]
		public string MaterialCode
		{
			get{ return _MaterialCode; }
			set
			{
				this.OnPropertyValueChange("MaterialCode");
				this._MaterialCode = value;
			}
		}
		/// <summary>
		/// 原材料名称
		/// </summary>
		[Field("MaterialName")]
		public string MaterialName
		{
			get{ return _MaterialName; }
			set
			{
				this.OnPropertyValueChange("MaterialName");
				this._MaterialName = value;
			}
		}
		/// <summary>
		/// 规格
		/// </summary>
		[Field("SpecificationModel")]
		public string SpecificationModel
		{
			get{ return _SpecificationModel; }
			set
			{
				this.OnPropertyValueChange("SpecificationModel");
				this._SpecificationModel = value;
			}
		}
		/// <summary>
		/// 计量单位
		/// </summary>
		[Field("MeasurementUnit")]
		public string MeasurementUnit
		{
			get{ return _MeasurementUnit; }
			set
			{
				this.OnPropertyValueChange("MeasurementUnit");
				this._MeasurementUnit = value;
			}
		}
		/// <summary>
		/// 单位重量
		/// </summary>
		[Field("Weight")]
		public decimal Weight
		{
			get{ return _Weight; }
			set
			{
				this.OnPropertyValueChange("Weight");
				this._Weight = value;
			}
		}
		/// <summary>
		/// 单件用量
		/// </summary>
		[Field("UseCount")]
		public decimal UseCount
		{
			get{ return _UseCount; }
			set
			{
				this.OnPropertyValueChange("UseCount");
				this._UseCount = value;
			}
		}
		/// <summary>
		/// 件数
		/// </summary>
		[Field("Count")]
		public decimal Count
		{
			get{ return _Count; }
			set
			{
				this.OnPropertyValueChange("Count");
				this._Count = value;
			}
		}
		/// <summary>
		/// 重量小计
		/// </summary>
		[Field("WeightTotal")]
		public decimal WeightTotal
		{
			get{ return _WeightTotal; }
			set
			{
				this.OnPropertyValueChange("WeightTotal");
				this._WeightTotal = value;
			}
		}
		/// <summary>
		/// 加工状态
		/// </summary>
		[Field("ProcessingState")]
		public string ProcessingState
		{
			get{ return _ProcessingState; }
			set
			{
				this.OnPropertyValueChange("ProcessingState");
				this._ProcessingState = value;
			}
		}
		/// <summary>
		/// 打包数量
		/// </summary>
		[Field("PackCount")]
        public int PackCount
		{
			get{ return _PackCount; }
			set
			{
				this.OnPropertyValueChange("PackCount");
				this._PackCount = value;
			}
		}
		/// <summary>
		/// 厂家
		/// </summary>
		[Field("Factory")]
		public string Factory
		{
			get{ return _Factory; }
			set
			{
				this.OnPropertyValueChange("Factory");
				this._Factory = value;
			}
		}
		/// <summary>
		/// 炉批号
		/// </summary>
		[Field("BatchNumber")]
		public string BatchNumber
		{
			get{ return _BatchNumber; }
			set
			{
				this.OnPropertyValueChange("BatchNumber");
				this._BatchNumber = value;
			}
		}
		/// <summary>
		/// 检测报告编号
		/// </summary>
		[Field("TestReportCode")]
		public string TestReportCode
		{
			get{ return _TestReportCode; }
			set
			{
				this.OnPropertyValueChange("TestReportCode");
				this._TestReportCode = value;
			}
		}
		/// <summary>
		/// 加工订单明细Id
		/// </summary>
		[Field("WorkOrderDetailId")]
		public int? WorkOrderDetailId
		{
			get{ return _WorkOrderDetailId; }
			set
			{
				this.OnPropertyValueChange("WorkOrderDetailId");
				this._WorkOrderDetailId = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.ProblemOrderCode,
				_.ComponentName,
				_.LargePattern,
				_.MaterialCode,
				_.MaterialName,
				_.SpecificationModel,
				_.MeasurementUnit,
				_.Weight,
				_.UseCount,
				_.Count,
				_.WeightTotal,
				_.ProcessingState,
				_.PackCount,
				_.Factory,
				_.BatchNumber,
				_.TestReportCode,
				_.WorkOrderDetailId,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._ProblemOrderCode,
				this._ComponentName,
				this._LargePattern,
				this._MaterialCode,
				this._MaterialName,
				this._SpecificationModel,
				this._MeasurementUnit,
				this._Weight,
				this._UseCount,
				this._Count,
				this._WeightTotal,
				this._ProcessingState,
				this._PackCount,
				this._Factory,
				this._BatchNumber,
				this._TestReportCode,
				this._WorkOrderDetailId,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbProblemOrderItem");
            /// <summary>
			/// ID
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbProblemOrderItem", "ID");
            /// <summary>
			/// 问题订单编号
			/// </summary>
			public readonly static Field ProblemOrderCode = new Field("ProblemOrderCode", "TbProblemOrderItem", "问题订单编号");
            /// <summary>
			/// 构件名称
			/// </summary>
			public readonly static Field ComponentName = new Field("ComponentName", "TbProblemOrderItem", "构件名称");
            /// <summary>
			/// 大样图
			/// </summary>
			public readonly static Field LargePattern = new Field("LargePattern", "TbProblemOrderItem", "大样图");
            /// <summary>
			/// 原材编号
			/// </summary>
			public readonly static Field MaterialCode = new Field("MaterialCode", "TbProblemOrderItem", "原材编号");
            /// <summary>
			/// 原材料名称
			/// </summary>
			public readonly static Field MaterialName = new Field("MaterialName", "TbProblemOrderItem", "原材料名称");
            /// <summary>
			/// 规格
			/// </summary>
			public readonly static Field SpecificationModel = new Field("SpecificationModel", "TbProblemOrderItem", "规格");
            /// <summary>
			/// 计量单位
			/// </summary>
			public readonly static Field MeasurementUnit = new Field("MeasurementUnit", "TbProblemOrderItem", "计量单位");
            /// <summary>
			/// 单位重量
			/// </summary>
			public readonly static Field Weight = new Field("Weight", "TbProblemOrderItem", "单位重量");
            /// <summary>
			/// 单件用量
			/// </summary>
			public readonly static Field UseCount = new Field("UseCount", "TbProblemOrderItem", "单件用量");
            /// <summary>
			/// 件数
			/// </summary>
			public readonly static Field Count = new Field("Count", "TbProblemOrderItem", "件数");
            /// <summary>
			/// 重量小计
			/// </summary>
			public readonly static Field WeightTotal = new Field("WeightTotal", "TbProblemOrderItem", "重量小计");
            /// <summary>
			/// 加工状态
			/// </summary>
			public readonly static Field ProcessingState = new Field("ProcessingState", "TbProblemOrderItem", "加工状态");
            /// <summary>
			/// 打包数量
			/// </summary>
			public readonly static Field PackCount = new Field("PackCount", "TbProblemOrderItem", "打包数量");
            /// <summary>
			/// 厂家
			/// </summary>
			public readonly static Field Factory = new Field("Factory", "TbProblemOrderItem", "厂家");
            /// <summary>
			/// 炉批号
			/// </summary>
			public readonly static Field BatchNumber = new Field("BatchNumber", "TbProblemOrderItem", "炉批号");
            /// <summary>
			/// 检测报告编号
			/// </summary>
			public readonly static Field TestReportCode = new Field("TestReportCode", "TbProblemOrderItem", "检测报告编号");
            /// <summary>
			/// 加工订单明细Id
			/// </summary>
			public readonly static Field WorkOrderDetailId = new Field("WorkOrderDetailId", "TbProblemOrderItem", "加工订单明细Id");
        }
        #endregion
	}
}