//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 实体类TbWorkOrderDeliveryOverItem。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("TbWorkOrderDeliveryOverItem")]
    [Serializable]
    public partial class TbWorkOrderDeliveryOverItem : Entity
    {
        #region Model
		private int _ID;
		private string _OrderCode;
		private int? _OrderDetailId;
		private int? _ProcessingTechnology;
		private decimal? _WeightSmallPlan;
		private int? _Number;

		/// <summary>
		/// 
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 加工订单编号
		/// </summary>
		[Field("OrderCode")]
		public string OrderCode
		{
			get{ return _OrderCode; }
			set
			{
				this.OnPropertyValueChange("OrderCode");
				this._OrderCode = value;
			}
		}
		/// <summary>
		/// 加工订单明细Id
		/// </summary>
		[Field("OrderDetailId")]
		public int? OrderDetailId
		{
			get{ return _OrderDetailId; }
			set
			{
				this.OnPropertyValueChange("OrderDetailId");
				this._OrderDetailId = value;
			}
		}
		/// <summary>
		/// 加工工艺
		/// </summary>
		[Field("ProcessingTechnology")]
		public int? ProcessingTechnology
		{
			get{ return _ProcessingTechnology; }
			set
			{
				this.OnPropertyValueChange("ProcessingTechnology");
				this._ProcessingTechnology = value;
			}
		}
		/// <summary>
		/// 重量
		/// </summary>
		[Field("WeightSmallPlan")]
		public decimal? WeightSmallPlan
		{
			get{ return _WeightSmallPlan; }
			set
			{
				this.OnPropertyValueChange("WeightSmallPlan");
				this._WeightSmallPlan = value;
			}
		}
		/// <summary>
		/// 件数
		/// </summary>
		[Field("Number")]
		public int? Number
		{
			get{ return _Number; }
			set
			{
				this.OnPropertyValueChange("Number");
				this._Number = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.OrderCode,
				_.OrderDetailId,
				_.ProcessingTechnology,
				_.WeightSmallPlan,
				_.Number,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._OrderCode,
				this._OrderDetailId,
				this._ProcessingTechnology,
				this._WeightSmallPlan,
				this._Number,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbWorkOrderDeliveryOverItem");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbWorkOrderDeliveryOverItem", "");
            /// <summary>
			/// 加工订单编号
			/// </summary>
			public readonly static Field OrderCode = new Field("OrderCode", "TbWorkOrderDeliveryOverItem", "加工订单编号");
            /// <summary>
			/// 加工订单明细Id
			/// </summary>
			public readonly static Field OrderDetailId = new Field("OrderDetailId", "TbWorkOrderDeliveryOverItem", "加工订单明细Id");
            /// <summary>
			/// 加工工艺
			/// </summary>
			public readonly static Field ProcessingTechnology = new Field("ProcessingTechnology", "TbWorkOrderDeliveryOverItem", "加工工艺");
            /// <summary>
			/// 重量
			/// </summary>
			public readonly static Field WeightSmallPlan = new Field("WeightSmallPlan", "TbWorkOrderDeliveryOverItem", "重量");
            /// <summary>
			/// 件数
			/// </summary>
			public readonly static Field Number = new Field("Number", "TbWorkOrderDeliveryOverItem", "件数");
        }
        #endregion
	}
}