//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 设备类型
    /// </summary>
    [Table("EquipmentType")]
    [Serializable]
    public partial class EquipmentType : Entity
    {
        #region Model
		private int _id;
		private string _HigherTypeCode_F;
		private string _HigherTypeCode;
		private string _TypeCode;
		private string _Type_Name;
		private int? _SortCode;
		private string _Remarks;

		/// <summary>
		/// 
		/// </summary>
		[Field("id")]
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange("id");
				this._id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("HigherTypeCode_F")]
		public string HigherTypeCode_F
		{
			get{ return _HigherTypeCode_F; }
			set
			{
				this.OnPropertyValueChange("HigherTypeCode_F");
				this._HigherTypeCode_F = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("HigherTypeCode")]
		public string HigherTypeCode
		{
			get{ return _HigherTypeCode; }
			set
			{
				this.OnPropertyValueChange("HigherTypeCode");
				this._HigherTypeCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("TypeCode")]
		public string TypeCode
		{
			get{ return _TypeCode; }
			set
			{
				this.OnPropertyValueChange("TypeCode");
				this._TypeCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Type_Name")]
		public string Type_Name
		{
			get{ return _Type_Name; }
			set
			{
				this.OnPropertyValueChange("Type_Name");
				this._Type_Name = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SortCode")]
		public int? SortCode
		{
			get{ return _SortCode; }
			set
			{
				this.OnPropertyValueChange("SortCode");
				this._SortCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Remarks")]
		public string Remarks
		{
			get{ return _Remarks; }
			set
			{
				this.OnPropertyValueChange("Remarks");
				this._Remarks = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.TypeCode,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.id,
				_.HigherTypeCode_F,
				_.HigherTypeCode,
				_.TypeCode,
				_.Type_Name,
				_.SortCode,
				_.Remarks,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._id,
				this._HigherTypeCode_F,
				this._HigherTypeCode,
				this._TypeCode,
				this._Type_Name,
				this._SortCode,
				this._Remarks,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "EquipmentType");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id", "EquipmentType", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field HigherTypeCode_F = new Field("HigherTypeCode_F", "EquipmentType", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field HigherTypeCode = new Field("HigherTypeCode", "EquipmentType", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field TypeCode = new Field("TypeCode", "EquipmentType", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Type_Name = new Field("Type_Name", "EquipmentType", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field SortCode = new Field("SortCode", "EquipmentType", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Remarks = new Field("Remarks", "EquipmentType", "");
        }
        #endregion
	}
}