//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 机械费用核算明细
    /// </summary>
    [Table("TbMachineCostItem")]
    [Serializable]
    public partial class TbMachineCostItem : Entity
    {
        #region Model
		private int _ID;
		private string _CheckCode;
		private string _DeviceCode;
		private string _DeviceName;
		private DateTime _StartTime;
		private DateTime _EndTime;
		private decimal _OilSauce;
		private decimal _OilPrice;
		private decimal _OilAmount;
		private decimal _ElectricSauce;
		private decimal _ElectricPrice;
		private decimal _ElectricAmount;
		private decimal _DepreciationCost;
		private decimal _TotalPrice;

		/// <summary>
		/// ID
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 核算编号
		/// </summary>
		[Field("CheckCode")]
		public string CheckCode
		{
			get{ return _CheckCode; }
			set
			{
				this.OnPropertyValueChange("CheckCode");
				this._CheckCode = value;
			}
		}
		/// <summary>
		/// 设备编号
		/// </summary>
		[Field("DeviceCode")]
		public string DeviceCode
		{
			get{ return _DeviceCode; }
			set
			{
				this.OnPropertyValueChange("DeviceCode");
				this._DeviceCode = value;
			}
		}
		/// <summary>
		/// 设备名称
		/// </summary>
		[Field("DeviceName")]
		public string DeviceName
		{
			get{ return _DeviceName; }
			set
			{
				this.OnPropertyValueChange("DeviceName");
				this._DeviceName = value;
			}
		}
		/// <summary>
		/// 开始时间
		/// </summary>
		[Field("StartTime")]
		public DateTime StartTime
		{
			get{ return _StartTime; }
			set
			{
				this.OnPropertyValueChange("StartTime");
				this._StartTime = value;
			}
		}
		/// <summary>
		/// 结束时间
		/// </summary>
		[Field("EndTime")]
		public DateTime EndTime
		{
			get{ return _EndTime; }
			set
			{
				this.OnPropertyValueChange("EndTime");
				this._EndTime = value;
			}
		}
		/// <summary>
		/// 耗油
		/// </summary>
		[Field("OilSauce")]
		public decimal OilSauce
		{
			get{ return _OilSauce; }
			set
			{
				this.OnPropertyValueChange("OilSauce");
				this._OilSauce = value;
			}
		}
		/// <summary>
		/// 单价(油)
		/// </summary>
		[Field("OilPrice")]
		public decimal OilPrice
		{
			get{ return _OilPrice; }
			set
			{
				this.OnPropertyValueChange("OilPrice");
				this._OilPrice = value;
			}
		}
		/// <summary>
		/// 金额(油)
		/// </summary>
		[Field("OilAmount")]
		public decimal OilAmount
		{
			get{ return _OilAmount; }
			set
			{
				this.OnPropertyValueChange("OilAmount");
				this._OilAmount = value;
			}
		}
		/// <summary>
		/// 耗电
		/// </summary>
		[Field("ElectricSauce")]
		public decimal ElectricSauce
		{
			get{ return _ElectricSauce; }
			set
			{
				this.OnPropertyValueChange("ElectricSauce");
				this._ElectricSauce = value;
			}
		}
		/// <summary>
		/// 单价(电)
		/// </summary>
		[Field("ElectricPrice")]
		public decimal ElectricPrice
		{
			get{ return _ElectricPrice; }
			set
			{
				this.OnPropertyValueChange("ElectricPrice");
				this._ElectricPrice = value;
			}
		}
		/// <summary>
		/// 金额(电)
		/// </summary>
		[Field("ElectricAmount")]
		public decimal ElectricAmount
		{
			get{ return _ElectricAmount; }
			set
			{
				this.OnPropertyValueChange("ElectricAmount");
				this._ElectricAmount = value;
			}
		}
		/// <summary>
		/// 折旧费用
		/// </summary>
		[Field("DepreciationCost")]
		public decimal DepreciationCost
		{
			get{ return _DepreciationCost; }
			set
			{
				this.OnPropertyValueChange("DepreciationCost");
				this._DepreciationCost = value;
			}
		}
		/// <summary>
		/// 总价合计
		/// </summary>
		[Field("TotalPrice")]
		public decimal TotalPrice
		{
			get{ return _TotalPrice; }
			set
			{
				this.OnPropertyValueChange("TotalPrice");
				this._TotalPrice = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.CheckCode,
				_.DeviceCode,
				_.DeviceName,
				_.StartTime,
				_.EndTime,
				_.OilSauce,
				_.OilPrice,
				_.OilAmount,
				_.ElectricSauce,
				_.ElectricPrice,
				_.ElectricAmount,
				_.DepreciationCost,
				_.TotalPrice,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._CheckCode,
				this._DeviceCode,
				this._DeviceName,
				this._StartTime,
				this._EndTime,
				this._OilSauce,
				this._OilPrice,
				this._OilAmount,
				this._ElectricSauce,
				this._ElectricPrice,
				this._ElectricAmount,
				this._DepreciationCost,
				this._TotalPrice,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbMachineCostItem");
            /// <summary>
			/// ID
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbMachineCostItem", "ID");
            /// <summary>
			/// 核算编号
			/// </summary>
			public readonly static Field CheckCode = new Field("CheckCode", "TbMachineCostItem", "核算编号");
            /// <summary>
			/// 设备编号
			/// </summary>
			public readonly static Field DeviceCode = new Field("DeviceCode", "TbMachineCostItem", "设备编号");
            /// <summary>
			/// 设备名称
			/// </summary>
			public readonly static Field DeviceName = new Field("DeviceName", "TbMachineCostItem", "设备名称");
            /// <summary>
			/// 开始时间
			/// </summary>
			public readonly static Field StartTime = new Field("StartTime", "TbMachineCostItem", "开始时间");
            /// <summary>
			/// 结束时间
			/// </summary>
			public readonly static Field EndTime = new Field("EndTime", "TbMachineCostItem", "结束时间");
            /// <summary>
			/// 耗油
			/// </summary>
			public readonly static Field OilSauce = new Field("OilSauce", "TbMachineCostItem", "耗油");
            /// <summary>
			/// 单价(油)
			/// </summary>
			public readonly static Field OilPrice = new Field("OilPrice", "TbMachineCostItem", "单价(油)");
            /// <summary>
			/// 金额(油)
			/// </summary>
			public readonly static Field OilAmount = new Field("OilAmount", "TbMachineCostItem", "金额(油)");
            /// <summary>
			/// 耗电
			/// </summary>
			public readonly static Field ElectricSauce = new Field("ElectricSauce", "TbMachineCostItem", "耗电");
            /// <summary>
			/// 单价(电)
			/// </summary>
			public readonly static Field ElectricPrice = new Field("ElectricPrice", "TbMachineCostItem", "单价(电)");
            /// <summary>
			/// 金额(电)
			/// </summary>
			public readonly static Field ElectricAmount = new Field("ElectricAmount", "TbMachineCostItem", "金额(电)");
            /// <summary>
			/// 折旧费用
			/// </summary>
			public readonly static Field DepreciationCost = new Field("DepreciationCost", "TbMachineCostItem", "折旧费用");
            /// <summary>
			/// 总价合计
			/// </summary>
			public readonly static Field TotalPrice = new Field("TotalPrice", "TbMachineCostItem", "总价合计");
        }
        #endregion
	}
}