//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 辅料计划申报明细
    /// </summary>
    [Table("TbValuationDeclareItem")]
    [Serializable]
    public partial class TbValuationDeclareItem : Entity
    {
        #region Model
		private int _ID;
		private string _ValuationDeclareCode;
		private string _OpenItemCode;
		private string _ItemName;
		private string _Unit;
		private decimal _Amount;
		private decimal _Price;
		private decimal _TotalPrice;
		private string _Process;
		private string _Remarks;

		/// <summary>
		/// ID
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 申报编号
		/// </summary>
		[Field("ValuationDeclareCode")]
		public string ValuationDeclareCode
		{
			get{ return _ValuationDeclareCode; }
			set
			{
				this.OnPropertyValueChange("ValuationDeclareCode");
				this._ValuationDeclareCode = value;
			}
		}
		/// <summary>
		/// 开项号
		/// </summary>
		[Field("OpenItemCode")]
		public string OpenItemCode
		{
			get{ return _OpenItemCode; }
			set
			{
				this.OnPropertyValueChange("OpenItemCode");
				this._OpenItemCode = value;
			}
		}
		/// <summary>
		/// 工作项目及费用名称
		/// </summary>
		[Field("ItemName")]
		public string ItemName
		{
			get{ return _ItemName; }
			set
			{
				this.OnPropertyValueChange("ItemName");
				this._ItemName = value;
			}
		}
		/// <summary>
		/// 单位
		/// </summary>
		[Field("Unit")]
		public string Unit
		{
			get{ return _Unit; }
			set
			{
				this.OnPropertyValueChange("Unit");
				this._Unit = value;
			}
		}
		/// <summary>
		/// 数量
		/// </summary>
		[Field("Amount")]
		public decimal Amount
		{
			get{ return _Amount; }
			set
			{
				this.OnPropertyValueChange("Amount");
				this._Amount = value;
			}
		}
		/// <summary>
		/// 单价（元）
		/// </summary>
		[Field("Price")]
		public decimal Price
		{
			get{ return _Price; }
			set
			{
				this.OnPropertyValueChange("Price");
				this._Price = value;
			}
		}
		/// <summary>
		/// 合价（元）
		/// </summary>
		[Field("TotalPrice")]
		public decimal TotalPrice
		{
			get{ return _TotalPrice; }
			set
			{
				this.OnPropertyValueChange("TotalPrice");
				this._TotalPrice = value;
			}
		}
		/// <summary>
		/// 加工工艺
		/// </summary>
		[Field("Process")]
		public string Process
		{
			get{ return _Process; }
			set
			{
				this.OnPropertyValueChange("Process");
				this._Process = value;
			}
		}
		/// <summary>
		/// 备  注
		/// </summary>
		[Field("Remarks")]
		public string Remarks
		{
			get{ return _Remarks; }
			set
			{
				this.OnPropertyValueChange("Remarks");
				this._Remarks = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.ValuationDeclareCode,
				_.OpenItemCode,
				_.ItemName,
				_.Unit,
				_.Amount,
				_.Price,
				_.TotalPrice,
				_.Process,
				_.Remarks,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._ValuationDeclareCode,
				this._OpenItemCode,
				this._ItemName,
				this._Unit,
				this._Amount,
				this._Price,
				this._TotalPrice,
				this._Process,
				this._Remarks,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbValuationDeclareItem");
            /// <summary>
			/// ID
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbValuationDeclareItem", "ID");
            /// <summary>
			/// 申报编号
			/// </summary>
			public readonly static Field ValuationDeclareCode = new Field("ValuationDeclareCode", "TbValuationDeclareItem", "申报编号");
            /// <summary>
			/// 开项号
			/// </summary>
			public readonly static Field OpenItemCode = new Field("OpenItemCode", "TbValuationDeclareItem", "开项号");
            /// <summary>
			/// 工作项目及费用名称
			/// </summary>
			public readonly static Field ItemName = new Field("ItemName", "TbValuationDeclareItem", "工作项目及费用名称");
            /// <summary>
			/// 单位
			/// </summary>
			public readonly static Field Unit = new Field("Unit", "TbValuationDeclareItem", "单位");
            /// <summary>
			/// 数量
			/// </summary>
			public readonly static Field Amount = new Field("Amount", "TbValuationDeclareItem", "数量");
            /// <summary>
			/// 单价（元）
			/// </summary>
			public readonly static Field Price = new Field("Price", "TbValuationDeclareItem", "单价（元）");
            /// <summary>
			/// 合价（元）
			/// </summary>
			public readonly static Field TotalPrice = new Field("TotalPrice", "TbValuationDeclareItem", "合价（元）");
            /// <summary>
			/// 加工工艺
			/// </summary>
			public readonly static Field Process = new Field("Process", "TbValuationDeclareItem", "加工工艺");
            /// <summary>
			/// 备  注
			/// </summary>
			public readonly static Field Remarks = new Field("Remarks", "TbValuationDeclareItem", "备  注");
        }
        #endregion
	}
}