//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36460
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 配送装车订单信息表
    /// </summary>
    [Table("TbDistributionEntOrder")]
    [Serializable]
    public partial class TbDistributionEntOrder : Entity
    {
        #region Model
		private int _ID;
		private string _DistributionCode;
		private string _OrderCode;
		private string _PlanDistributionTime;
		private string _TypeCode;
		private string _TypeName;
		private string _UsePart;
		private string _DistributionAddress;
		private string _SiteCode;
		private string _SiteContacts;
		private string _SiteContactTel;
		private decimal? _SiteWeightTotal;
		private string _DisEntOrderIdentity;
		private string _UnloadingState;
		private string _SignState;
		private int? _OrderFlowState;
		private string _Enclosure;
		private DateTime? _UnloadingStateTiem;
		private DateTime? _SignStateTime;

		/// <summary>
		/// ID
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 配送装车编号
		/// </summary>
		[Field("DistributionCode")]
		public string DistributionCode
		{
			get{ return _DistributionCode; }
			set
			{
				this.OnPropertyValueChange("DistributionCode");
				this._DistributionCode = value;
			}
		}
		/// <summary>
		/// 订单编号
		/// </summary>
		[Field("OrderCode")]
		public string OrderCode
		{
			get{ return _OrderCode; }
			set
			{
				this.OnPropertyValueChange("OrderCode");
				this._OrderCode = value;
			}
		}
		/// <summary>
		/// 计划配送时间
		/// </summary>
		[Field("PlanDistributionTime")]
		public string PlanDistributionTime
		{
			get{ return _PlanDistributionTime; }
			set
			{
				this.OnPropertyValueChange("PlanDistributionTime");
				this._PlanDistributionTime = value;
			}
		}
		/// <summary>
		/// 类型编号
		/// </summary>
		[Field("TypeCode")]
		public string TypeCode
		{
			get{ return _TypeCode; }
			set
			{
				this.OnPropertyValueChange("TypeCode");
				this._TypeCode = value;
			}
		}
		/// <summary>
		/// 类型名称
		/// </summary>
		[Field("TypeName")]
		public string TypeName
		{
			get{ return _TypeName; }
			set
			{
				this.OnPropertyValueChange("TypeName");
				this._TypeName = value;
			}
		}
		/// <summary>
		/// 使用部位
		/// </summary>
		[Field("UsePart")]
		public string UsePart
		{
			get{ return _UsePart; }
			set
			{
				this.OnPropertyValueChange("UsePart");
				this._UsePart = value;
			}
		}
		/// <summary>
		/// 配送地址
		/// </summary>
		[Field("DistributionAddress")]
		public string DistributionAddress
		{
			get{ return _DistributionAddress; }
			set
			{
				this.OnPropertyValueChange("DistributionAddress");
				this._DistributionAddress = value;
			}
		}
		/// <summary>
		/// 站点
		/// </summary>
		[Field("SiteCode")]
		public string SiteCode
		{
			get{ return _SiteCode; }
			set
			{
				this.OnPropertyValueChange("SiteCode");
				this._SiteCode = value;
			}
		}
		/// <summary>
		/// 站点联系人
		/// </summary>
		[Field("SiteContacts")]
		public string SiteContacts
		{
			get{ return _SiteContacts; }
			set
			{
				this.OnPropertyValueChange("SiteContacts");
				this._SiteContacts = value;
			}
		}
		/// <summary>
		/// 站点联系人电话
		/// </summary>
		[Field("SiteContactTel")]
		public string SiteContactTel
		{
			get{ return _SiteContactTel; }
			set
			{
				this.OnPropertyValueChange("SiteContactTel");
				this._SiteContactTel = value;
			}
		}
		/// <summary>
		/// 站点重量合计
		/// </summary>
		[Field("SiteWeightTotal")]
		public decimal? SiteWeightTotal
		{
			get{ return _SiteWeightTotal; }
			set
			{
				this.OnPropertyValueChange("SiteWeightTotal");
				this._SiteWeightTotal = value;
			}
		}
		/// <summary>
		/// 配送装车订单标识列
		/// </summary>
		[Field("DisEntOrderIdentity")]
		public string DisEntOrderIdentity
		{
			get{ return _DisEntOrderIdentity; }
			set
			{
				this.OnPropertyValueChange("DisEntOrderIdentity");
				this._DisEntOrderIdentity = value;
			}
		}
		/// <summary>
		/// 卸货状态
		/// </summary>
		[Field("UnloadingState")]
		public string UnloadingState
		{
			get{ return _UnloadingState; }
			set
			{
				this.OnPropertyValueChange("UnloadingState");
				this._UnloadingState = value;
			}
		}
		/// <summary>
		/// 签收状态
		/// </summary>
		[Field("SignState")]
		public string SignState
		{
			get{ return _SignState; }
			set
			{
				this.OnPropertyValueChange("SignState");
				this._SignState = value;
			}
		}
		/// <summary>
		/// 订单运输流程当前状态（ 2进场 3开始卸货 4卸货完成 5出场）
		/// </summary>
		[Field("OrderFlowState")]
		public int? OrderFlowState
		{
			get{ return _OrderFlowState; }
			set
			{
				this.OnPropertyValueChange("OrderFlowState");
				this._OrderFlowState = value;
			}
		}
		/// <summary>
		/// 附件
		/// </summary>
		[Field("Enclosure")]
		public string Enclosure
		{
			get{ return _Enclosure; }
			set
			{
				this.OnPropertyValueChange("Enclosure");
				this._Enclosure = value;
			}
		}
		/// <summary>
		/// 卸货完成时间
		/// </summary>
		[Field("UnloadingStateTiem")]
		public DateTime? UnloadingStateTiem
		{
			get{ return _UnloadingStateTiem; }
			set
			{
				this.OnPropertyValueChange("UnloadingStateTiem");
				this._UnloadingStateTiem = value;
			}
		}
		/// <summary>
		/// 签收完成时间
		/// </summary>
		[Field("SignStateTime")]
		public DateTime? SignStateTime
		{
			get{ return _SignStateTime; }
			set
			{
				this.OnPropertyValueChange("SignStateTime");
				this._SignStateTime = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.DistributionCode,
				_.OrderCode,
				_.PlanDistributionTime,
				_.TypeCode,
				_.TypeName,
				_.UsePart,
				_.DistributionAddress,
				_.SiteCode,
				_.SiteContacts,
				_.SiteContactTel,
				_.SiteWeightTotal,
				_.DisEntOrderIdentity,
				_.UnloadingState,
				_.SignState,
				_.OrderFlowState,
				_.Enclosure,
				_.UnloadingStateTiem,
				_.SignStateTime,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._DistributionCode,
				this._OrderCode,
				this._PlanDistributionTime,
				this._TypeCode,
				this._TypeName,
				this._UsePart,
				this._DistributionAddress,
				this._SiteCode,
				this._SiteContacts,
				this._SiteContactTel,
				this._SiteWeightTotal,
				this._DisEntOrderIdentity,
				this._UnloadingState,
				this._SignState,
				this._OrderFlowState,
				this._Enclosure,
				this._UnloadingStateTiem,
				this._SignStateTime,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbDistributionEntOrder");
            /// <summary>
			/// ID
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbDistributionEntOrder", "ID");
            /// <summary>
			/// 配送装车编号
			/// </summary>
			public readonly static Field DistributionCode = new Field("DistributionCode", "TbDistributionEntOrder", "配送装车编号");
            /// <summary>
			/// 订单编号
			/// </summary>
			public readonly static Field OrderCode = new Field("OrderCode", "TbDistributionEntOrder", "订单编号");
            /// <summary>
			/// 计划配送时间
			/// </summary>
			public readonly static Field PlanDistributionTime = new Field("PlanDistributionTime", "TbDistributionEntOrder", "计划配送时间");
            /// <summary>
			/// 类型编号
			/// </summary>
			public readonly static Field TypeCode = new Field("TypeCode", "TbDistributionEntOrder", "类型编号");
            /// <summary>
			/// 类型名称
			/// </summary>
			public readonly static Field TypeName = new Field("TypeName", "TbDistributionEntOrder", "类型名称");
            /// <summary>
			/// 使用部位
			/// </summary>
			public readonly static Field UsePart = new Field("UsePart", "TbDistributionEntOrder", "使用部位");
            /// <summary>
			/// 配送地址
			/// </summary>
			public readonly static Field DistributionAddress = new Field("DistributionAddress", "TbDistributionEntOrder", "配送地址");
            /// <summary>
			/// 站点
			/// </summary>
			public readonly static Field SiteCode = new Field("SiteCode", "TbDistributionEntOrder", "站点");
            /// <summary>
			/// 站点联系人
			/// </summary>
			public readonly static Field SiteContacts = new Field("SiteContacts", "TbDistributionEntOrder", "站点联系人");
            /// <summary>
			/// 站点联系人电话
			/// </summary>
			public readonly static Field SiteContactTel = new Field("SiteContactTel", "TbDistributionEntOrder", "站点联系人电话");
            /// <summary>
			/// 站点重量合计
			/// </summary>
			public readonly static Field SiteWeightTotal = new Field("SiteWeightTotal", "TbDistributionEntOrder", "站点重量合计");
            /// <summary>
			/// 配送装车订单标识列
			/// </summary>
			public readonly static Field DisEntOrderIdentity = new Field("DisEntOrderIdentity", "TbDistributionEntOrder", "配送装车订单标识列");
            /// <summary>
			/// 卸货状态
			/// </summary>
			public readonly static Field UnloadingState = new Field("UnloadingState", "TbDistributionEntOrder", "卸货状态");
            /// <summary>
			/// 签收状态
			/// </summary>
			public readonly static Field SignState = new Field("SignState", "TbDistributionEntOrder", "签收状态");
            /// <summary>
			/// 订单运输流程当前状态（ 2进场 3开始卸货 4卸货完成 5出场）
			/// </summary>
			public readonly static Field OrderFlowState = new Field("OrderFlowState", "TbDistributionEntOrder", "订单运输流程当前状态（ 2进场 3开始卸货 4卸货完成 5出场）");
            /// <summary>
			/// 附件
			/// </summary>
			public readonly static Field Enclosure = new Field("Enclosure", "TbDistributionEntOrder", "附件");
            /// <summary>
			/// 卸货完成时间
			/// </summary>
			public readonly static Field UnloadingStateTiem = new Field("UnloadingStateTiem", "TbDistributionEntOrder", "卸货完成时间");
            /// <summary>
			/// 签收完成时间
			/// </summary>
			public readonly static Field SignStateTime = new Field("SignStateTime", "TbDistributionEntOrder", "签收完成时间");
        }
        #endregion
	}
}