//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36460
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 实体类TbDistributionEntItem。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("TbDistributionEntItem")]
    [Serializable]
    public partial class TbDistributionEntItem : Entity
    {
        #region Model
		private int _ID;
		private string _ComponentName;
		private string _MaterialCode;
		private string _Standard;
		private string _MeteringUnit;
		private decimal? _UnitWeight;
		private decimal? _SingletonWeight;
		private int _Number;
		private decimal? _WeightGauge;
		private string _Manufactor;
		private string _HeatNo;
		private string _TestReport;
		private string _DistributionCode;
		private string _MaterialName;
		private int _PlanItemID;
		private int? _PSAmount;
		private int _DataType;
		private int? _ProcessingTechnology;
		private int? _PackagesNumber;
		private int? _PackNumber;
		private int? _GjNumber;
		private string _DisEntOrderIdentity;
		private string _OrderCode;
		private int? _WorkorderdetailId;
		private int? _CanLoadingPackCount;
		private int? _ThisTimePackCount;

		/// <summary>
		/// 配送状态 明细表 标识ID
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 构件名称
		/// </summary>
		[Field("ComponentName")]
		public string ComponentName
		{
			get{ return _ComponentName; }
			set
			{
				this.OnPropertyValueChange("ComponentName");
				this._ComponentName = value;
			}
		}
		/// <summary>
		/// 原材料编号Code
		/// </summary>
		[Field("MaterialCode")]
		public string MaterialCode
		{
			get{ return _MaterialCode; }
			set
			{
				this.OnPropertyValueChange("MaterialCode");
				this._MaterialCode = value;
			}
		}
		/// <summary>
		/// 规格
		/// </summary>
		[Field("Standard")]
		public string Standard
		{
			get{ return _Standard; }
			set
			{
				this.OnPropertyValueChange("Standard");
				this._Standard = value;
			}
		}
		/// <summary>
		/// 计量单位
		/// </summary>
		[Field("MeteringUnit")]
		public string MeteringUnit
		{
			get{ return _MeteringUnit; }
			set
			{
				this.OnPropertyValueChange("MeteringUnit");
				this._MeteringUnit = value;
			}
		}
		/// <summary>
		/// 单位重量
		/// </summary>
		[Field("UnitWeight")]
		public decimal? UnitWeight
		{
			get{ return _UnitWeight; }
			set
			{
				this.OnPropertyValueChange("UnitWeight");
				this._UnitWeight = value;
			}
		}
		/// <summary>
		/// 单件重量
		/// </summary>
		[Field("SingletonWeight")]
		public decimal? SingletonWeight
		{
			get{ return _SingletonWeight; }
			set
			{
				this.OnPropertyValueChange("SingletonWeight");
				this._SingletonWeight = value;
			}
		}
		/// <summary>
		/// 件数
		/// </summary>
		[Field("Number")]
		public int Number
		{
			get{ return _Number; }
			set
			{
				this.OnPropertyValueChange("Number");
				this._Number = value;
			}
		}
		/// <summary>
		/// 重量小计
		/// </summary>
		[Field("WeightGauge")]
		public decimal? WeightGauge
		{
			get{ return _WeightGauge; }
			set
			{
				this.OnPropertyValueChange("WeightGauge");
				this._WeightGauge = value;
			}
		}
		/// <summary>
		/// 厂家
		/// </summary>
		[Field("Manufactor")]
		public string Manufactor
		{
			get{ return _Manufactor; }
			set
			{
				this.OnPropertyValueChange("Manufactor");
				this._Manufactor = value;
			}
		}
		/// <summary>
		/// 炉批号
		/// </summary>
		[Field("HeatNo")]
		public string HeatNo
		{
			get{ return _HeatNo; }
			set
			{
				this.OnPropertyValueChange("HeatNo");
				this._HeatNo = value;
			}
		}
		/// <summary>
		/// 检测报告
		/// </summary>
		[Field("TestReport")]
		public string TestReport
		{
			get{ return _TestReport; }
			set
			{
				this.OnPropertyValueChange("TestReport");
				this._TestReport = value;
			}
		}
		/// <summary>
		/// 配送编号
		/// </summary>
		[Field("DistributionCode")]
		public string DistributionCode
		{
			get{ return _DistributionCode; }
			set
			{
				this.OnPropertyValueChange("DistributionCode");
				this._DistributionCode = value;
			}
		}
		/// <summary>
		/// 原材料名称
		/// </summary>
		[Field("MaterialName")]
		public string MaterialName
		{
			get{ return _MaterialName; }
			set
			{
				this.OnPropertyValueChange("MaterialName");
				this._MaterialName = value;
			}
		}
		/// <summary>
		/// 计划明细ID
		/// </summary>
		[Field("PlanItemID")]
		public int PlanItemID
		{
			get{ return _PlanItemID; }
			set
			{
				this.OnPropertyValueChange("PlanItemID");
				this._PlanItemID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PSAmount")]
		public int? PSAmount
		{
			get{ return _PSAmount; }
			set
			{
				this.OnPropertyValueChange("PSAmount");
				this._PSAmount = value;
			}
		}
		/// <summary>
		/// 数据类型 1配送计划明细 2加工订单明细
		/// </summary>
		[Field("DataType")]
		public int DataType
		{
			get{ return _DataType; }
			set
			{
				this.OnPropertyValueChange("DataType");
				this._DataType = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ProcessingTechnology")]
		public int? ProcessingTechnology
		{
			get{ return _ProcessingTechnology; }
			set
			{
				this.OnPropertyValueChange("ProcessingTechnology");
				this._ProcessingTechnology = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PackagesNumber")]
		public int? PackagesNumber
		{
			get{ return _PackagesNumber; }
			set
			{
				this.OnPropertyValueChange("PackagesNumber");
				this._PackagesNumber = value;
			}
		}
		/// <summary>
		/// 打包数量
		/// </summary>
		[Field("PackNumber")]
		public int? PackNumber
		{
			get{ return _PackNumber; }
			set
			{
				this.OnPropertyValueChange("PackNumber");
				this._PackNumber = value;
			}
		}
		/// <summary>
		/// 构件件数
		/// </summary>
		[Field("GjNumber")]
		public int? GjNumber
		{
			get{ return _GjNumber; }
			set
			{
				this.OnPropertyValueChange("GjNumber");
				this._GjNumber = value;
			}
		}
		/// <summary>
		/// 配送装车订单Id
		/// </summary>
		[Field("DisEntOrderIdentity")]
		public string DisEntOrderIdentity
		{
			get{ return _DisEntOrderIdentity; }
			set
			{
				this.OnPropertyValueChange("DisEntOrderIdentity");
				this._DisEntOrderIdentity = value;
			}
		}
		/// <summary>
		/// 订单编号
		/// </summary>
		[Field("OrderCode")]
		public string OrderCode
		{
			get{ return _OrderCode; }
			set
			{
				this.OnPropertyValueChange("OrderCode");
				this._OrderCode = value;
			}
		}
		/// <summary>
		/// 订单明细id
		/// </summary>
		[Field("WorkorderdetailId")]
		public int? WorkorderdetailId
		{
			get{ return _WorkorderdetailId; }
			set
			{
				this.OnPropertyValueChange("WorkorderdetailId");
				this._WorkorderdetailId = value;
			}
		}
		/// <summary>
		/// 可装车包数
		/// </summary>
		[Field("CanLoadingPackCount")]
		public int? CanLoadingPackCount
		{
			get{ return _CanLoadingPackCount; }
			set
			{
				this.OnPropertyValueChange("CanLoadingPackCount");
				this._CanLoadingPackCount = value;
			}
		}
		/// <summary>
		/// 本次装车包数
		/// </summary>
		[Field("ThisTimePackCount")]
		public int? ThisTimePackCount
		{
			get{ return _ThisTimePackCount; }
			set
			{
				this.OnPropertyValueChange("ThisTimePackCount");
				this._ThisTimePackCount = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.ComponentName,
				_.MaterialCode,
				_.Standard,
				_.MeteringUnit,
				_.UnitWeight,
				_.SingletonWeight,
				_.Number,
				_.WeightGauge,
				_.Manufactor,
				_.HeatNo,
				_.TestReport,
				_.DistributionCode,
				_.MaterialName,
				_.PlanItemID,
				_.PSAmount,
				_.DataType,
				_.ProcessingTechnology,
				_.PackagesNumber,
				_.PackNumber,
				_.GjNumber,
				_.DisEntOrderIdentity,
				_.OrderCode,
				_.WorkorderdetailId,
				_.CanLoadingPackCount,
				_.ThisTimePackCount,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._ComponentName,
				this._MaterialCode,
				this._Standard,
				this._MeteringUnit,
				this._UnitWeight,
				this._SingletonWeight,
				this._Number,
				this._WeightGauge,
				this._Manufactor,
				this._HeatNo,
				this._TestReport,
				this._DistributionCode,
				this._MaterialName,
				this._PlanItemID,
				this._PSAmount,
				this._DataType,
				this._ProcessingTechnology,
				this._PackagesNumber,
				this._PackNumber,
				this._GjNumber,
				this._DisEntOrderIdentity,
				this._OrderCode,
				this._WorkorderdetailId,
				this._CanLoadingPackCount,
				this._ThisTimePackCount,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbDistributionEntItem");
            /// <summary>
			/// 配送状态 明细表 标识ID
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbDistributionEntItem", "配送状态 明细表 标识ID");
            /// <summary>
			/// 构件名称
			/// </summary>
			public readonly static Field ComponentName = new Field("ComponentName", "TbDistributionEntItem", "构件名称");
            /// <summary>
			/// 原材料编号Code
			/// </summary>
			public readonly static Field MaterialCode = new Field("MaterialCode", "TbDistributionEntItem", "原材料编号Code");
            /// <summary>
			/// 规格
			/// </summary>
			public readonly static Field Standard = new Field("Standard", "TbDistributionEntItem", "规格");
            /// <summary>
			/// 计量单位
			/// </summary>
			public readonly static Field MeteringUnit = new Field("MeteringUnit", "TbDistributionEntItem", "计量单位");
            /// <summary>
			/// 单位重量
			/// </summary>
			public readonly static Field UnitWeight = new Field("UnitWeight", "TbDistributionEntItem", "单位重量");
            /// <summary>
			/// 单件重量
			/// </summary>
			public readonly static Field SingletonWeight = new Field("SingletonWeight", "TbDistributionEntItem", "单件重量");
            /// <summary>
			/// 件数
			/// </summary>
			public readonly static Field Number = new Field("Number", "TbDistributionEntItem", "件数");
            /// <summary>
			/// 重量小计
			/// </summary>
			public readonly static Field WeightGauge = new Field("WeightGauge", "TbDistributionEntItem", "重量小计");
            /// <summary>
			/// 厂家
			/// </summary>
			public readonly static Field Manufactor = new Field("Manufactor", "TbDistributionEntItem", "厂家");
            /// <summary>
			/// 炉批号
			/// </summary>
			public readonly static Field HeatNo = new Field("HeatNo", "TbDistributionEntItem", "炉批号");
            /// <summary>
			/// 检测报告
			/// </summary>
			public readonly static Field TestReport = new Field("TestReport", "TbDistributionEntItem", "检测报告");
            /// <summary>
			/// 配送编号
			/// </summary>
			public readonly static Field DistributionCode = new Field("DistributionCode", "TbDistributionEntItem", "配送编号");
            /// <summary>
			/// 原材料名称
			/// </summary>
			public readonly static Field MaterialName = new Field("MaterialName", "TbDistributionEntItem", "原材料名称");
            /// <summary>
			/// 计划明细ID
			/// </summary>
			public readonly static Field PlanItemID = new Field("PlanItemID", "TbDistributionEntItem", "计划明细ID");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PSAmount = new Field("PSAmount", "TbDistributionEntItem", "");
            /// <summary>
			/// 数据类型 1配送计划明细 2加工订单明细
			/// </summary>
			public readonly static Field DataType = new Field("DataType", "TbDistributionEntItem", "数据类型 1配送计划明细 2加工订单明细");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ProcessingTechnology = new Field("ProcessingTechnology", "TbDistributionEntItem", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PackagesNumber = new Field("PackagesNumber", "TbDistributionEntItem", "");
            /// <summary>
			/// 打包数量
			/// </summary>
			public readonly static Field PackNumber = new Field("PackNumber", "TbDistributionEntItem", "打包数量");
            /// <summary>
			/// 构件件数
			/// </summary>
			public readonly static Field GjNumber = new Field("GjNumber", "TbDistributionEntItem", "构件件数");
            /// <summary>
			/// 配送装车订单Id
			/// </summary>
			public readonly static Field DisEntOrderIdentity = new Field("DisEntOrderIdentity", "TbDistributionEntItem", "配送装车订单Id");
            /// <summary>
			/// 订单编号
			/// </summary>
			public readonly static Field OrderCode = new Field("OrderCode", "TbDistributionEntItem", "订单编号");
            /// <summary>
			/// 订单明细id
			/// </summary>
			public readonly static Field WorkorderdetailId = new Field("WorkorderdetailId", "TbDistributionEntItem", "订单明细id");
            /// <summary>
			/// 可装车包数
			/// </summary>
			public readonly static Field CanLoadingPackCount = new Field("CanLoadingPackCount", "TbDistributionEntItem", "可装车包数");
            /// <summary>
			/// 本次装车包数
			/// </summary>
			public readonly static Field ThisTimePackCount = new Field("ThisTimePackCount", "TbDistributionEntItem", "本次装车包数");
        }
        #endregion

        #region 扩展字段

        /// <summary>
        /// 历史配送数量
        /// </summary>
        public int PSAmountOld { get; set; }

        /// <summary>
        /// 加工订单数量
        /// </summary>
        public int OrderAmount { get; set; }

        #endregion
	}
}