//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36460
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace PM.DataEntity
{
    /// <summary>
    /// 实体类TbTransportFlow。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("TbTransportFlow")]
    [Serializable]
    public partial class TbTransportFlow : Entity
    {
        #region Model
		private int _ID;
		private string _DistributionCode;
		private string _VehicleCode;
		private string _Driver;
		private string _Enclosure;
		private int? _FlowType;
		private int? _ArticleId;
		private DateTime _InsertTime;
		private int? _DisEntOrderId;

		/// <summary>
		/// ID
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 配送装车单号
		/// </summary>
		[Field("DistributionCode")]
		public string DistributionCode
		{
			get{ return _DistributionCode; }
			set
			{
				this.OnPropertyValueChange("DistributionCode");
				this._DistributionCode = value;
			}
		}
		/// <summary>
		/// 车牌号
		/// </summary>
		[Field("VehicleCode")]
		public string VehicleCode
		{
			get{ return _VehicleCode; }
			set
			{
				this.OnPropertyValueChange("VehicleCode");
				this._VehicleCode = value;
			}
		}
		/// <summary>
		/// 驾驶员
		/// </summary>
		[Field("Driver")]
		public string Driver
		{
			get{ return _Driver; }
			set
			{
				this.OnPropertyValueChange("Driver");
				this._Driver = value;
			}
		}
		/// <summary>
		/// 附件
		/// </summary>
		[Field("Enclosure")]
		public string Enclosure
		{
			get{ return _Enclosure; }
			set
			{
				this.OnPropertyValueChange("Enclosure");
				this._Enclosure = value;
			}
		}
		/// <summary>
		/// 类型 1出厂 2进场 3开始卸货 4卸货完成 5出场
		/// </summary>
		[Field("FlowType")]
		public int? FlowType
		{
			get{ return _FlowType; }
			set
			{
				this.OnPropertyValueChange("FlowType");
				this._FlowType = value;
			}
		}
		/// <summary>
		/// 问题Id
		/// </summary>
		[Field("ArticleId")]
		public int? ArticleId
		{
			get{ return _ArticleId; }
			set
			{
				this.OnPropertyValueChange("ArticleId");
				this._ArticleId = value;
			}
		}
		/// <summary>
		/// 录入时间
		/// </summary>
		[Field("InsertTime")]
		public DateTime InsertTime
		{
			get{ return _InsertTime; }
			set
			{
				this.OnPropertyValueChange("InsertTime");
				this._InsertTime = value;
			}
		}
		/// <summary>
		/// 配送装车订单信息Id
		/// </summary>
		[Field("DisEntOrderId")]
		public int? DisEntOrderId
		{
			get{ return _DisEntOrderId; }
			set
			{
				this.OnPropertyValueChange("DisEntOrderId");
				this._DisEntOrderId = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.DistributionCode,
				_.VehicleCode,
				_.Driver,
				_.Enclosure,
				_.FlowType,
				_.ArticleId,
				_.InsertTime,
				_.DisEntOrderId,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._DistributionCode,
				this._VehicleCode,
				this._Driver,
				this._Enclosure,
				this._FlowType,
				this._ArticleId,
				this._InsertTime,
				this._DisEntOrderId,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "TbTransportFlow");
            /// <summary>
			/// ID
			/// </summary>
			public readonly static Field ID = new Field("ID", "TbTransportFlow", "ID");
            /// <summary>
			/// 配送装车单号
			/// </summary>
			public readonly static Field DistributionCode = new Field("DistributionCode", "TbTransportFlow", "配送装车单号");
            /// <summary>
			/// 车牌号
			/// </summary>
			public readonly static Field VehicleCode = new Field("VehicleCode", "TbTransportFlow", "车牌号");
            /// <summary>
			/// 驾驶员
			/// </summary>
			public readonly static Field Driver = new Field("Driver", "TbTransportFlow", "驾驶员");
            /// <summary>
			/// 附件
			/// </summary>
			public readonly static Field Enclosure = new Field("Enclosure", "TbTransportFlow", "附件");
            /// <summary>
			/// 类型 1出厂 2进场 3开始卸货 4卸货完成 5出场
			/// </summary>
			public readonly static Field FlowType = new Field("FlowType", "TbTransportFlow", "类型 1出厂 2进场 3开始卸货 4卸货完成 5出场");
            /// <summary>
			/// 问题Id
			/// </summary>
			public readonly static Field ArticleId = new Field("ArticleId", "TbTransportFlow", "问题Id");
            /// <summary>
			/// 录入时间
			/// </summary>
			public readonly static Field InsertTime = new Field("InsertTime", "TbTransportFlow", "录入时间");
            /// <summary>
			/// 配送装车订单信息Id
			/// </summary>
			public readonly static Field DisEntOrderId = new Field("DisEntOrderId", "TbTransportFlow", "配送装车订单信息Id");
        }
        #endregion
	}
}